### PR TITLE
1545 Fix bootstrap tests

### PR DESCRIPTION
**Pull request by alla-blinkova**

### CODE REVIEW

**Comment by mf-code** [comment]
[5306] - gLrlcQLh

**Comment by mf-code** [comment]
[5306] - Z3r25ocx

**Comment by mf-code** [comment]
[5308] - NiMM6Mlb

**Comment by mf-code** [comment]
[5308] - 7ARooi7L

**Comment by mf-code** [comment]
[5308] - GJjtU4bc

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5531164&bid=18128952)

**Comment by mf-code** [comment]
[5308] - Allure report on Netlify: https://5ebe6fdf0a2659f226f45217--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5311] - 6iGAnCPj

**Comment by mf-code** [comment]
[5311] - SMTWKBOe

**Comment by mf-code** [comment]
[5311] - rgnzfuSV

**Comment by mf-code** [comment]
[5311] - Allure report on Netlify: https://5ebe7612c844c0e1e08594ea--musing-swartz-6fc060.netlify.app

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5531164&bid=18128952)

**Comment by mf-code** [comment]
[5314] - agiPslwH

**Comment by mf-code** [comment]
[5314] - 4Amn3VSw

**Comment by mf-code** [comment]
[5314] - Qsd38Ld7

**Comment by mf-code** [comment]
[5314] - Allure report on Netlify: https://5ebe883c1b98edc6ad8ca22e--musing-swartz-6fc060.netlify.app

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5531164&bid=18128952)

**Comment by mf-code** [comment]
[5315] - vn50yj5r

**Comment by mf-code** [comment]
[5315] - zpWfsDM7

**Comment by mf-code** [comment]
[5315] - 7MPsNHz4

**Comment by mf-code** [comment]
[5315] - Allure report on Netlify: https://5ebe902d33a1406e0f8c2a81--musing-swartz-6fc060.netlify.app

**Pull request merged**
