### PR TITLE
#2242 added iOS Picker

### PR DESCRIPTION
**Pull request by alyatertyshnikova**

### CODE REVIEW

**Comment by mf-code** [comment]
[5888] - apFXq3Q4GG1o

**Comment by mf-code** [comment]
[5888] - fwt63jaWkTU1

**Comment by mf-code** [comment]
[5888] - RjTKGIzQ41At

**Comment by mf-code** [comment]
[5888] - sx7TwcIsADn2

**Comment by mf-code** [comment]
[5888] - wXy8jb5cNyXu

**Comment by mf-code** [comment]
[5888] - 9fOoHT3XXpBR

**Comment by mf-code** [comment]
[5888] - ibx4HSZsFAT8

**Comment by mf-code** [comment]
[5888] - mjBOeJddjlEK

**Comment by mf-code** [comment]
[5888] - ZqCOQ7RYKm3s

**Comment by mf-code** [comment]
[5888] - hK4H1SV59Fce

**Comment by mf-code** [comment]
[5888] - pNdGiZxUVNEJ

**Comment by mf-code** [comment]
[5888] - mNHVXWrzHSam

**Comment by mf-code** [comment]
[5888] - Ie4y9uLmQXAt

**Comment by mf-code** [comment]
[5888] - SDzDnbmGg1zA

**Comment by mf-code** [comment]
[5888] - openjdk8 - Allure report on Netlify: https://5f3bd6d535e5e16531252b6e--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5888] - openjdk10 - Allure report on Netlify: https://5f3bd77d35e5e17675252bb5--musing-swartz-6fc060.netlify.app

**Review by alexarm — APPROVED** [review]

**Pull request merged**
