### PR TITLE
2394 action bar impl

### PR DESCRIPTION
**Pull request by Syzygy9**

### CODE REVIEW

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-mobile-tests/src/test/java/nativeapp_android/tests/ActionBarTests.java  1
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/asserts/ActionBarAssert.java  1
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/elements/common/app/android/ActionBar.java  3
         

Clones added
============
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/elements/common/app/android/ActionBar.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6392786&bid=20732745)

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/elements/common/app/android/ActionBar.java  3
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/asserts/ActionBarAssert.java  1
- jdi-light-mobile-tests/src/test/java/nativeapp_android/tests/ActionBarTests.java  1
         

Clones added
============
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/elements/common/app/android/ActionBar.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6392786&bid=20732745)

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/elements/common/app/android/ActionBar.java  3
- jdi-light-mobile-tests/src/test/java/nativeapp_android/tests/ActionBarTests.java  1
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/asserts/ActionBarAssert.java  1
         

Clones added
============
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/elements/common/app/android/ActionBar.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6392786&bid=20732745)

**Comment by mf-code** [comment]
[6408] - AG8AGgj1AK1u

**Comment by mf-code** [comment]
[6408] - dEloVwZ7OcvG

**Comment by mf-code** [comment]
[6408] - 0YQVOMebl85G

**Comment by mf-code** [comment]
[6408] - b3dI2goyNMi2

**Comment by mf-code** [comment]
[6408] - lFh9B50qSruK

**Comment by mf-code** [comment]
[6408] - AKkOxI6GjeqN

**Comment by mf-code** [comment]
[6408] - q7Qlzx51IzmC

**Comment by mf-code** [comment]
[6408] - VT9z5GFQ13u1

**Comment by mf-code** [comment]
[6408] - R0jZMzjDaXW9

**Comment by mf-code** [comment]
[6408] - t194ExZ9HLUy

**Comment by mf-code** [comment]
[6408] - a7oQMmL7myzT

**Comment by mf-code** [comment]
[6408] - ZYOxtdlJvi7N

**Comment by mf-code** [comment]
[6408] - cjbnZsUTFqj1

**Comment by mf-code** [comment]
[6408] - BuPsiW5kMjSp

**Comment by mf-code** [comment]
[6408] - 6qwRFjd6aVyB

**Comment by mf-code** [comment]
[6408] - MgPj2Ibcvmfq

**Comment by mf-code** [comment]
[6408] - zm9qYralEBX5

**Comment by mf-code** [comment]
[6408] - HzI61PFxTDrc

**Comment by mf-code** [comment]
[6408] - openjdk8 - Allure report on Netlify: https://5faa9865578be8cb2aceb147--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6408] - openjdk10 - Allure report on Netlify: https://5faa992e55c530cb0dd9a10b--musing-swartz-6fc060.netlify.app

**Review by alexarm — APPROVED** [review]

**Pull request merged**
