### PR TITLE
Renamed login test.

### PR DESCRIPTION
**Pull request by gbuh**
Renamed login test.

### CODE REVIEW

**Comment by mf-code** [comment]
[6191] - 8hMUU9O8gsKm

**Comment by mf-code** [comment]
[6191] - mghOBsvmYtBD

**Comment by mf-code** [comment]
[6191] - GstIPcY15r5Y

**Comment by mf-code** [comment]
[6191] - wg2glCqB6Nye

**Comment by mf-code** [comment]
[6191] - 3n7ePfhXXFqH

**Comment by mf-code** [comment]
[6191] - 38h030Cd2OTr

**Comment by mf-code** [comment]
[6191] - NzumZ0VOjEBX

**Comment by mf-code** [comment]
[6191] - dmWi6Hf3E3As

**Comment by mf-code** [comment]
[6191] - xMolFNQQCbxr

**Comment by mf-code** [comment]
[6191] - qxdyLgZUqFDf

**Comment by mf-code** [comment]
[6191] - jNGyIEWyrtxH

**Comment by mf-code** [comment]
[6191] - ZzE55JAeD7xu

**Comment by mf-code** [comment]
[6191] - hkJABX9Qd3K6

**Comment by mf-code** [comment]
[6191] - HTTS5aCr5xKD

**Comment by mf-code** [comment]
[6191] - 6V5cNNyaqlQ2

**Comment by mf-code** [comment]
[6191] - CQxKdqdrHU08

**Comment by mf-code** [comment]
[6191] - Zb3bJuy9iTH5

**Comment by mf-code** [comment]
[6191] - agurDR257ldo

**Comment by mf-code** [comment]
[6191] - GtDlSAbNfOSV

**Comment by mf-code** [comment]
[6191] - qvfcXOkCfCin

**Comment by mf-code** [comment]
[6191] - openjdk8 - Allure report on Netlify: https://5f7073f3a28201dddfb1fb85--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6191] - openjdk10 - Allure report on Netlify: https://5f7075f5879ac76571d43282--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6197] - VOys1SQq3Vdz

**Comment by mf-code** [comment]
[6197] - FtvZtZzFfn8T

**Comment by mf-code** [comment]
[6197] - openjdk8 - Allure report on Netlify: https://5f7431f48f237a501a83c747--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6197] - openjdk10 - Allure report on Netlify: https://5f7432877b6f6e518337b5a4--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6198] - w730qyQdbb6V

**Comment by mf-code** [comment]
[6198] - W24dw2TydlB3

**Comment by mf-code** [comment]
[6198] - openjdk8 - Allure report on Netlify: https://5f743678846ede50af9aa46a--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6198] - openjdk10 - Allure report on Netlify: https://5f74368deca35e4b9c33ab9b--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6199] - 6xBBH47omBi2

**Comment by mf-code** [comment]
[6199] - X2ainEQx4Lxi

**Comment by mf-code** [comment]
[6199] - openjdk8 - Allure report on Netlify: https://5f743f8dcb94ea7794974614--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6199] - openjdk10 - Allure report on Netlify: https://5f743fa449960f75388eb560--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6200] - Rk57HeGKFLlG

**Comment by mf-code** [comment]
[6200] - qQfgW40CYpYa

**Comment by mf-code** [comment]
[6200] - openjdk8 - Allure report on Netlify: https://5f744585201e957f3eab83d4--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6200] - openjdk10 - Allure report on Netlify: https://5f74459d49960f7f1a8eb64d--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6201] - keN5bK0tN7eo

**Comment by mf-code** [comment]
[6201] - lJXdw1wt6I4W

**Comment by mf-code** [comment]
[6201] - openjdk8 - Allure report on Netlify: https://5f7450c75317587a17f1afe9--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6201] - openjdk10 - Allure report on Netlify: https://5f7450eaeca35e7b56339990--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6202] - zS8UbrmwicaF

**Comment by mf-code** [comment]
[6202] - b0pZ6cSEgjmW

**Comment by mf-code** [comment]
[6202] - openjdk8 - Allure report on Netlify: https://5f745ea5b142ef8c064985ed--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6202] - openjdk10 - Allure report on Netlify: https://5f745f00b142ef8ceb49857b--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6203] - x9j2MTbIUYUc

**Comment by mf-code** [comment]
[6203] - WzhSkvPXDoon

**Comment by mf-code** [comment]
[6203] - openjdk8 - Allure report on Netlify: https://5f746b99ff011e9d8e5643f2--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6203] - openjdk10 - Allure report on Netlify: https://5f746c23ff011e9077564916--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6204] - EHPtdjWAXB8w

**Comment by mf-code** [comment]
[6204] - OVF0luVw1Whl

**Comment by mf-code** [comment]
[6204] - nK3Iu2tnTVpo

**Comment by mf-code** [comment]
[6204] - 2A2jL19EjZDo

**Comment by mf-code** [comment]
[6204] -

**Comment by mf-code** [comment]
[6204] - 9TSaVbZqx0IB

**Comment by mf-code** [comment]
[6204] - jmrAjyc2O6mm

**Comment by mf-code** [comment]
[6204] - HL6pt9L9pDe0

**Comment by mf-code** [comment]
[6204] - P1EecGbGP4oJ

**Comment by mf-code** [comment]
[6204] - FappfygzxFjj

**Comment by mf-code** [comment]
[6204] - JHa0hUiNQYhi

**Comment by mf-code** [comment]
[6204] - 2Z7xRalSRDKv

**Comment by mf-code** [comment]
[6204] - 6EQcey5NldLG

**Comment by mf-code** [comment]
[6204] - OpTwlXSy6PvD

**Comment by mf-code** [comment]
[6204] - Kq5tSAo2Gvic

**Comment by mf-code** [comment]
[6206] - C6NzzSYWGlZR

**Comment by mf-code** [comment]
[6206] - uFOybphsm6tB

**Comment by mf-code** [comment]
[6206] - r3gHN3RFBL53

**Comment by mf-code** [comment]
[6206] - 5Ko8nsrhnye8

**Comment by mf-code** [comment]
[6206] - Mgjxe4KbpU7M

**Comment by mf-code** [comment]
[6206] - GECJ7grEKayT

**Comment by mf-code** [comment]
[6206] - 2nI7bdXvKjTO

**Comment by mf-code** [comment]
[6206] - DQGwfgINH9qt

**Comment by mf-code** [comment]
[6206] - zjcqE0dd7hVr

**Comment by mf-code** [comment]
[6206] - l0sJWPwrXMvm

**Comment by mf-code** [comment]
[6206] - 4GWRqoFdQYGt

**Comment by mf-code** [comment]
[6206] - MR8LTMwutx3U

**Comment by mf-code** [comment]
[6206] - db4eNJQEhQEs

**Comment by mf-code** [comment]
[6206] - 0zMgjRjelQLi

**Comment by mf-code** [comment]
[6206] - UF78p8kiUURV

**Comment by mf-code** [comment]
[6206] - openjdk8 - Allure report on Netlify: https://5f749acd9bb81a0133cb3965--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6206] - openjdk10 - Allure report on Netlify: https://5f749bc0ae899800ad0a7c46--musing-swartz-6fc060.netlify.app

**Comment by RomanIovlev** [comment]
Merged into (pull_request_for_Roman

**Pull request closed without merging**
