### PR TITLE
Added Angular Datepicker element and test cases.

### PR DESCRIPTION
**Pull request by gbuh**
Added Angular Datepicker element and test cases.

### CODE REVIEW

**Comment by mf-code** [comment]
[5920] - L9U5sKwP4jbX

**Comment by mf-code** [comment]
[5920] - 8zkaJ1h1nvrQ

**Comment by mf-code** [comment]
[5920] - YX6ESI5hdxeQ

**Comment by mf-code** [comment]
[5920] - W2P3YSkgAud8

**Comment by mf-code** [comment]
[5920] - BpUf6FQCU990

**Comment by mf-code** [comment]
[5920] - 41J2H1Nv8Q7d

**Comment by mf-code** [comment]
[5920] - 6z3DrkGoKWEL

**Comment by mf-code** [comment]
[5920] - spLwAQkp0GQS

**Comment by mf-code** [comment]
[5920] - 5Y3t7kr50lIj

**Comment by mf-code** [comment]
[5920] - xdo2cDkSpaKb

**Comment by mf-code** [comment]
[5920] - WOLRbONTsSHB

**Comment by mf-code** [comment]
[5920] - i7iwNTCY7CzQ

**Comment by mf-code** [comment]
[5921] - XsaKSvBoto2p

**Comment by mf-code** [comment]
[5921] - 10DPVako9umQ

**Comment by mf-code** [comment]
[5921] - rgbIs3Uw8Xv5

**Review by AlexSoftt — APPROVED** [review]

**Comment by mf-code** [comment]
[5921] - bSneKx24wKMX

**Comment by mf-code** [comment]
[5921] - gdzb58naqhe0

**Comment by mf-code** [comment]
[5921] - eLqNbKGpuFlq

**Comment by mf-code** [comment]
[5921] - ilYhb01y8fvg

**Comment by mf-code** [comment]
[5921] - vLmESlej2xR7

**Comment by mf-code** [comment]
[5921] - MFGpNH5bwaQH

**Comment by mf-code** [comment]
[5921] - AjBTGpqyXYMc

**Comment by mf-code** [comment]
[5921] - ouLaYv1H5qAp

**Comment by mf-code** [comment]
[5921] - qvmESoCHIcnG

**Comment by mf-code** [comment]
[5924] - KrGlEc1rjvqK

**Comment by mf-code** [comment]
[5924] - tUhxmcgBn9lq

**Comment by mf-code** [comment]
[5924] - FR3rwfyBvmPt

**Comment by mf-code** [comment]
[5924] - qYNycy4jMxMm

**Comment by mf-code** [comment]
[5924] - 88lV6Fycz57o

**Comment by mf-code** [comment]
[5924] - yQtJynkxcBmE

**Comment by mf-code** [comment]
[5924] - yOWLzUYks5gQ

**Comment by mf-code** [comment]
[5924] - gFyKLpcMgt1E

**Comment by mf-code** [comment]
[5924] - oZiNeMnvtmI9

**Comment by mf-code** [comment]
[5924] - RUmYp6UwdNIA

**Comment by mf-code** [comment]
[5924] - ngCmeKJCGHzr

**Comment by mf-code** [comment]
[5930] - fcLh9HBeooyL

**Comment by mf-code** [comment]
[5930] - SOBS3LPAdB6a

**Comment by mf-code** [comment]
[5930] - Ugng3wIiWhet

**Comment by mf-code** [comment]
[5930] - GBXANvPWjqKi

**Comment by mf-code** [comment]
[5930] - JW7zcxYixNFW

**Comment by mf-code** [comment]
[5930] - MYVCfm2zrYLw

**Comment by mf-code** [comment]
[5930] - XDK8JZ7aRIpF

**Comment by mf-code** [comment]
[5930] - SdrqW9Sicugm

**Comment by mf-code** [comment]
[5930] - WQAiG46KgJH0

**Comment by mf-code** [comment]
[5930] - AfJdj4mAwJYH

**Comment by mf-code** [comment]
[5930] - xpenw3SjX92P

**Comment by mf-code** [comment]
[5930] - JQKU07VD4jT0

**Comment by mf-code** [comment]
[5941] - 7M7Qy4ZTTQsc

**Comment by mf-code** [comment]
[5941] - vRejgZIkfzk5

**Comment by mf-code** [comment]
[5941] - a6mFA1PIeXqx

**Comment by mf-code** [comment]
[5941] - sGeSdZymOhsV

**Comment by mf-code** [comment]
[5941] - PfDSIWBIdgJS

**Comment by mf-code** [comment]
[5941] - abvTWX0L3xZb

**Comment by mf-code** [comment]
[5941] - GXqkQMqHOQKL

**Comment by mf-code** [comment]
[5941] - yB3gRzi6Iilc

**Comment by mf-code** [comment]
[5941] - Ef5tM8w0HY1n

**Comment by mf-code** [comment]
[5941] - e8FUMADcQajJ

**Comment by mf-code** [comment]
[5941] - QuMDvCsAhiDN

**Comment by mf-code** [comment]
[5941] - jHryGh1tEOUN

**Comment by mf-code** [comment]
[5941] - YUzKPnIj9qma

**Comment by mf-code** [comment]
[5941] - wLE8WTYinS9v

**Comment by mf-code** [comment]
[5941] - YobUsXL4LIkn

**Comment by mf-code** [comment]
[5941] - z0GsKz39FsZj

**Comment by mf-code** [comment]
[5941] - FjvlLzT16Au9

**Comment by mf-code** [comment]
[5941] - dAcQs9j4u4IQ

**Comment by mf-code** [comment]
[5941] - CyP5NQvxeACI

**Comment by mf-code** [comment]
[5941] - p5E85jf8LHcg

**Comment by mf-code** [comment]
[5941] - KXjEvB7z5pnn

**Comment by mf-code** [comment]
[5941] - Sc3o8KnrIMs3

**Comment by mf-code** [comment]
[5941] - 0g09XmvuhvmC

**Comment by mf-code** [comment]
[5941] - IkmDkd1iH22m

**Comment by mf-code** [comment]
[5941] - 0ZYemuRvswLi

**Comment by mf-code** [comment]
[5941] - kZbnq60Jk488

**Comment by mf-code** [comment]
[5941] - ZqMah8CAFXJ8

**Comment by mf-code** [comment]
[5941] - D1peeVbS0Dtr

**Comment by mf-code** [comment]
[5941] - e01UeIPDqfhw

**Comment by mf-code** [comment]
[5943] - FHOSMgIxJmGc

**Comment by mf-code** [comment]
[5943] - M0kVUwlBuo7n

**Comment by mf-code** [comment]
[5943] - cNrypJ82m3Oo

**Comment by mf-code** [comment]
[5943] - CHWHLK7uBBXl

**Comment by mf-code** [comment]
[5943] - Vq7FFYXccXYz

**Comment by mf-code** [comment]
[5943] - B3yMbO6Kd6Lo

**Comment by mf-code** [comment]
[5943] - mer3jkyJTUJv

**Comment by mf-code** [comment]
[5943] - IZSo1aUwtII8

**Comment by mf-code** [comment]
[5943] - HiUVUPBQpOFc

**Comment by mf-code** [comment]
[5943] - kiEIxNGb1R8p

**Comment by mf-code** [comment]
[5943] - TnaBiZevqUCa

**Comment by mf-code** [comment]
[5943] - DmFVNdxjISNd

**Comment by mf-code** [comment]
[5943] - OAEixIsGzl6a

**Comment by mf-code** [comment]
[5943] - Aa23AxxVPG1h

**Comment by mf-code** [comment]
[5943] - RlpoXTw23qfn

**Comment by mf-code** [comment]
[5945] - MTgvqiDl0p48

**Comment by mf-code** [comment]
[5945] - Z6udHXBhxTHR

**Comment by mf-code** [comment]
[5945] - zw1GPSedtfIt

**Comment by mf-code** [comment]
[5945] - gusEiffY7UmJ

**Comment by mf-code** [comment]
[5945] - 8XPdmQznWyc4

**Comment by mf-code** [comment]
[5945] - FUTVQ67R4esW

**Comment by mf-code** [comment]
[5945] - ErIQH0JyHn8q

**Comment by mf-code** [comment]
[5945] - eqUd65DSutzO

**Comment by mf-code** [comment]
[5945] - QELDV4RqZNAr

**Comment by mf-code** [comment]
[5945] - IFsFsfQX4ePj

**Comment by mf-code** [comment]
[5945] - SnkIFF1UCRpA

**Comment by mf-code** [comment]
[5945] - YDCLq5cjt183

**Comment by mf-code** [comment]
[5945] - LfH9qTGiZ40n

**Comment by mf-code** [comment]
[5945] - UipFwPUhfOIO

**Comment by mf-code** [comment]
[5945] - XoTg5VGh0ugB

**Comment by mf-code** [comment]
[5945] - 8E63tu4C0p5H

**Comment by mf-code** [comment]
[5945] - openjdk8 - Allure report on Netlify: https://5f48e294e40cfad36b4017c0--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5945] - openjdk10 - Allure report on Netlify: https://5f48e3cd9e9d7700919c9f6d--musing-swartz-6fc060.netlify.app

**Pull request merged**
