### PR TITLE
fix null pointer issues

### PR DESCRIPTION
**Pull request by RomanIovlev**

### CODE REVIEW

**Comment by mf-code** [comment]
[6021] - XTEKVEvv1zsr

**Comment by mf-code** [comment]
[6021] - 825i7xc7RQcw

**Comment by mf-code** [comment]
[6021] - 58wiCrIueyqk

**Review by AlexSofft — APPROVED** [review]

**Comment by mf-code** [comment]
[6021] - DxdzXGyPtyYy

**Comment by mf-code** [comment]
[6021] - QOgJRdtiWHlG

**Comment by mf-code** [comment]
[6021] - TRV0mYovjYbn

**Comment by mf-code** [comment]
[6021] - w6jDLiHeX9qD

**Comment by mf-code** [comment]
[6021] - 28g3k9uC1RLh

**Comment by mf-code** [comment]
[6021] - phIyjMdzBXyE

**Comment by mf-code** [comment]
[6021] - b8iYnl24Qxlr

**Comment by mf-code** [comment]
[6021] - DXDUe3FznyWR

**Comment by mf-code** [comment]
[6021] - RF5cRMLzQLxt

**Comment by mf-code** [comment]
[6021] - m2ZSuwnvX4Gw

**Comment by mf-code** [comment]
[6021] - A6K9y1Wy1S0z

**Comment by mf-code** [comment]
[6021] - WoH0XrRBwd5U

**Comment by mf-code** [comment]
[6021] - NiYCARxadBCt

**Comment by mf-code** [comment]
[6021] - ulD547czrYC6

**Comment by mf-code** [comment]
[6022] - SqrH10JhceYa

**Comment by mf-code** [comment]
[6021] - V8MUL8ES8p4F

**Comment by mf-code** [comment]
[6022] - ge3kZWJp55iR

**Comment by mf-code** [comment]
[6022] - 9ghPi8Y6bpyx

**Comment by mf-code** [comment]
[6022] - gbOIKCeTGC9q

**Comment by mf-code** [comment]
[6022] - LDm3QRXW5aZz

**Comment by mf-code** [comment]
[6022] - Pyys5064cSTp

**Comment by mf-code** [comment]
[6021] - openjdk10 - Allure report on Netlify: https://5f514c5556c9691b47ba9aa4--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6022] - mZnXCZkR7gb7

**Comment by mf-code** [comment]
[6022] - 9fw3Y1DnCRHU

**Comment by mf-code** [comment]
[6022] - epo6s2ihgNxP

**Comment by mf-code** [comment]
[6022] - 9zuS0coK8YbP

**Comment by mf-code** [comment]
[6022] - V1OwqpWXVQaT

**Comment by mf-code** [comment]
[6022] - M3WWpLBJ77SN

**Comment by mf-code** [comment]
[6022] - xcZbfKQKGggZ

**Comment by mf-code** [comment]
[6022] - 4qiWapOIQjGe

**Comment by mf-code** [comment]
[6022] - dcsPgRDsK3DU

**Comment by mf-code** [comment]
[6022] - rfyIbG9Zu1il

**Comment by mf-code** [comment]
[6022] - OMAE6lpxh5Mh

**Comment by mf-code** [comment]
[6023] - dbZ7yuuHGuGY

**Comment by mf-code** [comment]
[6023] - Oftoss6L071o

**Comment by mf-code** [comment]
[6023] - BtCskyI4yxKg

**Comment by mf-code** [comment]
[6022] - openjdk8 - Allure report on Netlify: https://5f5155fccf855401422b2a82--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6023] - fBruKNernI3d

**Comment by mf-code** [comment]
[6022] - openjdk10 - Allure report on Netlify: https://5f515789e43fb50990ad8539--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6023] - HqK5hGp0VX1O

**Comment by mf-code** [comment]
[6023] - y4SswwCTi41T

**Comment by mf-code** [comment]
[6023] - 3gixXRncCS43

**Comment by mf-code** [comment]
[6023] - p9eBiRjP7t6X

**Comment by mf-code** [comment]
[6023] - 5spbtRTSm53X

**Comment by mf-code** [comment]
[6023] - MBdTNZlW0gbE

**Pull request merged**
