### PR TITLE
Fixing html tests

### PR DESCRIPTION
**Pull request by Innokentiy945**

### CODE REVIEW

**Comment by mf-code** [comment]
[6311] - NqUVOEvXsvJQ

**Comment by mf-code** [comment]
[6311] - cMjs8fItxDlb

**Comment by mf-code** [comment]
[6311] - nzRFsK3tYvzl

**Comment by mf-code** [comment]
[6311] - vj5u8AIexzfp

**Comment by mf-code** [comment]
[6311] - k6v6MzLOlVZq

**Comment by mf-code** [comment]
[6311] - rBMRscfft9YJ

**Comment by mf-code** [comment]
[6311] - M6PGhkTN2K7A

**Comment by mf-code** [comment]
[6311] - PSlaPSEJIBgN

**Comment by mf-code** [comment]
[6311] - iKulx19zBsuJ

**Comment by mf-code** [comment]
[6311] - 4uasSluP3Jfr

**Comment by mf-code** [comment]
[6311] - rv3laBd3qY2d

**Comment by mf-code** [comment]
[6311] - XfTc7TreHnWx

**Comment by mf-code** [comment]
[6311] - tezQPJQByc5a

**Comment by mf-code** [comment]
[6311] - f3x7wBZOjeuG

**Comment by mf-code** [comment]
[6312] - 53YxLYeUviMM

**Comment by mf-code** [comment]
[6312] - VPqYTLRglzwf

**Comment by mf-code** [comment]
[6312] - AmgzJNTNaRtb

**Comment by mf-code** [comment]
[6312] - NntwKR9cNlOn

**Comment by mf-code** [comment]
[6312] - wsyMiIEXG0Y4

**Comment by mf-code** [comment]
[6312] - i7HBumP68zMS

**Comment by mf-code** [comment]
[6312] - EyVIwn9js5ZO

**Comment by mf-code** [comment]
[6312] - DH9NiG3nPzZN

**Comment by mf-code** [comment]
[6312] - wwLL75uG7fNc

**Comment by mf-code** [comment]
[6312] - gFuoPSzNELzz

**Comment by mf-code** [comment]
[6312] - 6wpbNYZFX5xc

**Comment by mf-code** [comment]
[6312] - TaaPpbOlrlBF

**Comment by mf-code** [comment]
[6312] - BOTOR9lZvOAT

**Comment by mf-code** [comment]
[6312] - USiwMrAijahn

**Comment by Innokentiy945** [comment]
Useless task. Closed.

**Pull request closed without merging**
