### PR TITLE
Run and fix angular tests on java11, 12, 13

### PR DESCRIPTION
**Pull request by Innokentiy945**

### CODE REVIEW

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/BottomSheetTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6344598&bid=20606024)

**Comment by mf-code** [comment]
[6294] - 2XzaCXRE9xDu

**Comment by mf-code** [comment]
[6294] - 6zOFSkoYybGF

**Comment by mf-code** [comment]
[6294] - hK4vfapkHinC

**Comment by mf-code** [comment]
[6294] - EeZ4FX9QJAti

**Comment by mf-code** [comment]
[6294] - 1EMXaliL0IAW

**Comment by mf-code** [comment]
[6294] - S1jltbMHGW7b

**Comment by mf-code** [comment]
[6294] - V4PYjNRqtXtX

**Comment by mf-code** [comment]
[6294] - sdr1fCx2XZtJ

**Comment by mf-code** [comment]
[6294] - FutV4V2uq3bJ

**Comment by mf-code** [comment]
[6294] - FTWJRFD9DWhq

**Comment by mf-code** [comment]
[6294] - MxwGenSHSH2G

**Comment by mf-code** [comment]
[6294] - QezWmhCRrvYv

**Comment by mf-code** [comment]
[6294] - JmlDogVy5MvU

**Comment by mf-code** [comment]
[6294] - zr0KGrQHskcN

**Comment by Innokentiy945** [comment]
Removed because there are some commits from past PR. I will create new branch & PR

**Pull request closed without merging**
