### PR TITLE
2038::Specifying multiple jdks in .travis.yml

### PR DESCRIPTION
**Pull request by clockworkbanana**
- according to https://docs.travis-ci.com/user/languages/java/
  this should run tests against multiple JDKs
- removed JAVA_HOME in line #31 - it should not be needed

### CODE REVIEW

**Comment by mf-code** [comment]
[5439] - Ujr0IhwI

**Comment by mf-code** [comment]
[5439] - odq7pGPc

**Comment by mf-code** [comment]
[5439] - H5brShM4

**Comment by mf-code** [comment]
[5439] - 5QRwMf7B

**Comment by mf-code** [comment]
[5439] - yGxVuTOP

**Comment by mf-code** [comment]
[5439] - 6SSVwbr3

**Comment by mf-code** [comment]
[5439] - lYHIfj9H

**Comment by mf-code** [comment]
[5439] - 1gaSAF03

**Comment by mf-code** [comment]
[5439] - VVqEeqAA

**Comment by mf-code** [comment]
[5439] - H0OkZxzi

**Comment by mf-code** [comment]
[5439] - gix32mWs

**Comment by mf-code** [comment]
[5439] - vMo1bv3p

**Comment by mf-code** [comment]
[5439] - VvQ6OEcZ

**Comment by mf-code** [comment]
[5439] - 3ZMG1iPv

**Comment by mf-code** [comment]
[5439] - 114j7T2r

**Comment by mf-code** [comment]
[5439] - jpEZcdT0

**Comment by mf-code** [comment]
[5439] - bVBh2N3t

**Comment by mf-code** [comment]
[5439] - fOjE9k3p

**Comment by mf-code** [comment]
[5439] - O9r5BVzt

**Comment by mf-code** [comment]
[5439] - CHmrAhJH

**Comment by mf-code** [comment]
[5439] - aHYJcgl4

**Comment by mf-code** [comment]
[5444] - uoLogyQN

**Comment by mf-code** [comment]
[5444] - 6j8L9Kel

**Comment by mf-code** [comment]
[5444] - Wc99yvKX

**Comment by mf-code** [comment]
[5444] - WWHT7ape

**Comment by mf-code** [comment]
[5444] - cM2mtMzY

**Comment by mf-code** [comment]
[5444] - 6XgKDpqe

**Comment by mf-code** [comment]
[5444] - 8HNvflb3

**Comment by mf-code** [comment]
[5444] - WqL1CX2m

**Comment by mf-code** [comment]
[5444] - MmlYabZw

**Comment by mf-code** [comment]
[5444] - UFUr0IAx

**Comment by mf-code** [comment]
[5444] - Y50SX44r

**Comment by mf-code** [comment]
[5444] - qv7PSrHi

**Comment by mf-code** [comment]
[5444] - Si2U6pet

**Comment by mf-code** [comment]
[5444] - fCJLj92L

**Comment by mf-code** [comment]
[5445] - Vf7QlGfX

**Comment by mf-code** [comment]
[5445] - qZoihPjX

**Comment by mf-code** [comment]
[5445] - ardgt9Oc

**Comment by mf-code** [comment]
[5445] - m63BuwNI

**Comment by mf-code** [comment]
[5445] - 8kkFI8h5

**Comment by mf-code** [comment]
[5445] - 2oXvu2Yh

**Comment by mf-code** [comment]
[5445] - ox2bJryv

**Comment by mf-code** [comment]
[5445] - Allure report on Netlify: https://5ecfad3538bc5d020b89429a--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5447] - ouVjhZzM

**Comment by mf-code** [comment]
[5447] - SKSZdCa9

**Comment by mf-code** [comment]
[5447] - smnu3FDH

**Comment by mf-code** [comment]
[5447] - sf8wsaCT

**Comment by mf-code** [comment]
[5447] - XIapwDBe

**Comment by mf-code** [comment]
[5447] - gWiRDYr5

**Comment by mf-code** [comment]
[5447] - oOX6Rxv3

**Comment by mf-code** [comment]
[5447] - vmji58Kf

**Comment by mf-code** [comment]
[5447] - qJLyAt7x

**Comment by mf-code** [comment]
[5447] - Allure report on Netlify: https://5ecfb888aede4c01e455fb96--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5448] - ChofVvmc

**Comment by mf-code** [comment]
[5448] - 4jvWIEVf

**Comment by mf-code** [comment]
[5448] - QuQIT5zs

**Comment by mf-code** [comment]
[5448] - SLaOzCHK

**Comment by mf-code** [comment]
[5448] - qTkmskx7

**Comment by mf-code** [comment]
[5448] - ZsxCdSjf

**Comment by mf-code** [comment]
[5448] - mFMmeWXV

**Comment by mf-code** [comment]
[5448] - 0uXSol7C

**Comment by mf-code** [comment]
[5448] - Ti38WaUw

**Comment by mf-code** [comment]
[5448] - 6liM6GG0

**Comment by mf-code** [comment]
[5448] - SbA78obp

**Comment by mf-code** [comment]
[5448] - mTmrZgHQ

**Comment by mf-code** [comment]
[5448] - WiJM3ODm

**Comment by mf-code** [comment]
[5448] - PeEB2Ya3

**Comment by mf-code** [comment]
[5448] - vB7EQsbS

**Comment by mf-code** [comment]
[5448] - 3NghE3S9

**Comment by mf-code** [comment]
[5448] - qkkda1bN

**Comment by mf-code** [comment]
[5448] - 4F9oLquG

**Comment by mf-code** [comment]
[5448] - 6wBumTjB

**Comment by mf-code** [comment]
[5448] - 0kc9iG3N

**Comment by mf-code** [comment]
[5448] - hUFqREBv

**Comment by mf-code** [comment]
[5449] - CIAckoBQ

**Comment by mf-code** [comment]
[5449] - gCg5XBZp

**Comment by mf-code** [comment]
[5449] - X9BkvNGx

**Comment by mf-code** [comment]
[5449] - 83DD7K6f

**Comment by mf-code** [comment]
[5449] - 0WmxU4pn

**Comment by mf-code** [comment]
[5449] - xSb7ComN

**Comment by mf-code** [comment]
[5450] - ydJ2ND7c

**Comment by mf-code** [comment]
[5450] - s4EE6lMj

**Comment by mf-code** [comment]
[5450] - kzczQt6q

**Comment by mf-code** [comment]
[5450] - nGKKNKiU

**Comment by mf-code** [comment]
[5450] - nWGIcvxf

**Comment by mf-code** [comment]
[5450] - Eq5ZaOJJ

**Comment by mf-code** [comment]
[5450] - wqJZgPq7

**Comment by mf-code** [comment]
[5450] - fziFITzd

**Comment by mf-code** [comment]
[5450] - h9jMAzVq

**Comment by mf-code** [comment]
[5450] - Allure report on Netlify: https://5ed026277861aa683b09ff99--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5451] - QQbNDJRf

**Comment by mf-code** [comment]
[5451] - 2lbrP4fM

**Comment by mf-code** [comment]
[5451] - eTR0YCfE

**Comment by mf-code** [comment]
[5451] - fUbWMtSF

**Comment by mf-code** [comment]
[5451] - lkkHDxps

**Comment by mf-code** [comment]
[5451] - dvyWU3cG

**Comment by mf-code** [comment]
[5451] - AsKGNMUK

**Comment by mf-code** [comment]
[5451] - OiPW12BR

**Comment by mf-code** [comment]
[5451] - XATdToMS

**Comment by mf-code** [comment]
[5451] - iJZ2ts6C

**Comment by mf-code** [comment]
[5451] - PZThC4XL

**Comment by mf-code** [comment]
[5451] - wubBre5J

**Comment by mf-code** [comment]
[5451] - 3pg59Mlx

**Comment by mf-code** [comment]
[5451] - lEvQWe2s

**Comment by mf-code** [comment]
[5451] - wrPsuXdJ

**Comment by mf-code** [comment]
[5451] - zqUazTjE

**Comment by mf-code** [comment]
[5451] - d7SuWinw

**Comment by mf-code** [comment]
[5451] - 5Ig955Yv

**Comment by mf-code** [comment]
[5451] - OBdSmGvY

**Comment by mf-code** [comment]
[5451] - QYwu41Pj

**Comment by mf-code** [comment]
[5451] - AKxpdAi6

**Comment by mf-code** [comment]
[5451] - FclqyDAW

**Comment by mf-code** [comment]
[5451] - 09VJ6BdX

**Comment by mf-code** [comment]
[5451] - 63iEccr1

**Comment by mf-code** [comment]
[5451] - RzkEd93B

**Comment by mf-code** [comment]
[5451] - 43M37ASJ

**Comment by mf-code** [comment]
[5451] - p1fTYbPR

**Comment by mf-code** [comment]
[5451] - 8fwrnkut

**Comment by mf-code** [comment]
[5451] - oBa6fCGg

**Comment by mf-code** [comment]
[5451] - aIkasoQs

**Comment by mf-code** [comment]
[5451] - ZEj7FppQ

**Comment by mf-code** [comment]
[5451] - JghJitoN

**Comment by mf-code** [comment]
[5451] - Ni4MlvNf

**Comment by mf-code** [comment]
[5451] - nJC0gIxT

**Comment by mf-code** [comment]
[5451] - p5SIXSkW

**Comment by mf-code** [comment]
[5451] - zRbZ2xJq

**Comment by mf-code** [comment]
[5451] - kReeEOm2

**Comment by mf-code** [comment]
[5451] - ryAAPJNh

**Comment by mf-code** [comment]
[5451] - eIWT1mck

**Comment by mf-code** [comment]
[5451] - o5hDv7x0

**Comment by mf-code** [comment]
[5451] - lLFug86t

**Comment by mf-code** [comment]
[5451] - isMrnfNX

**Comment by mf-code** [comment]
[5460] - r6cKGNxA

**Comment by mf-code** [comment]
[5460] - kXLkptrz

**Comment by mf-code** [comment]
[5460] - 4OEzDRKt

**Comment by mf-code** [comment]
[5460] - wOjuZ09W

**Comment by mf-code** [comment]
[5460] - 5msNRw29

**Comment by mf-code** [comment]
[5460] - xZMikBp6

**Comment by mf-code** [comment]
[5461] - 6TSZ5Smr

**Comment by mf-code** [comment]
[5461] - KVw3hDl5

**Comment by mf-code** [comment]
[5462] - D63ER5ET

**Comment by mf-code** [comment]
[5462] - FDBaTnBa

**Comment by mf-code** [comment]
[5462] - pMAhRn3p

**Comment by mf-code** [comment]
[5462] - XLdbCZmB

**Comment by mf-code** [comment]
[5462] - 5bxg3pys

**Comment by mf-code** [comment]
[5462] - SMW4xu1l

**Comment by mf-code** [comment]
[5464] - z6K8lzeB

**Comment by mf-code** [comment]
[5464] - 8iZ1llZm

**Comment by mf-code** [comment]
[5464] - lHjDQMIq

**Comment by mf-code** [comment]
[5464] - fAqxAze4

**Comment by mf-code** [comment]
[5464] - U7ZGu1NI

**Comment by mf-code** [comment]
[5464] - ZURj1pbn

**Comment by mf-code** [comment]
[5464] - 7hM7HWbm

**Comment by mf-code** [comment]
[5464] - a72KS0C8

**Comment by mf-code** [comment]
[5464] - q581UvWB

**Comment by mf-code** [comment]
[5464] - Allure report on Netlify: https://5ed12540f204f7852fbe3aea--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5465] - 7GabiloV

**Comment by mf-code** [comment]
[5465] - jRX6AA48

**Comment by mf-code** [comment]
[5465] - q1jWnYjA

**Comment by mf-code** [comment]
[5465] - X7svO8xl

**Comment by mf-code** [comment]
[5465] - 3uM0YCGh

**Comment by mf-code** [comment]
[5465] - zzFM100w

**Comment by mf-code** [comment]
[5465] - 4SFhIUMv

**Comment by mf-code** [comment]
[5465] - Sqrw12cq

**Comment by mf-code** [comment]
[5465] - BCUzIqg2

**Comment by mf-code** [comment]
[5465] - Allure report on Netlify: https://5ed129307b08208904bcc7ce--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5466] - Rh8nhtoF

**Comment by mf-code** [comment]
[5466] - DwPbpj1a

**Comment by mf-code** [comment]
[5466] - jYa6oovT

**Comment by mf-code** [comment]
[5466] - SnUZ5M4R

**Comment by mf-code** [comment]
[5466] - Sl0slLSw

**Comment by mf-code** [comment]
[5466] - BAGcDc9i

**Comment by mf-code** [comment]
[5466] - 860QuCBu

**Comment by mf-code** [comment]
[5466] - 7dYTAiWl

**Comment by mf-code** [comment]
[5466] - zkZ9Y5xC

**Comment by mf-code** [comment]
[5466] - ewd7uY77

**Comment by mf-code** [comment]
[5466] - ZO3SyQuU

**Comment by mf-code** [comment]
[5467] - LOiYOcVU

**Comment by mf-code** [comment]
[5467] - gUlrCuPx

**Comment by mf-code** [comment]
[5467] - jZiKwhXC

**Comment by mf-code** [comment]
[5467] - 7crUj1vo

**Comment by mf-code** [comment]
[5467] - OChDYt4w

**Comment by mf-code** [comment]
[5467] - sLV2e8BE

**Comment by mf-code** [comment]
[5467] - FsuNp9qN

**Comment by mf-code** [comment]
[5467] - yZTzDHfj

**Comment by mf-code** [comment]
[5467] - ulHoIR9Z

**Comment by mf-code** [comment]
[5467] - LlqdG1Gr

**Comment by mf-code** [comment]
[5467] - tSA9kWfi

**Comment by mf-code** [comment]
[5467] - LmFfRqOA

**Comment by mf-code** [comment]
[5467] - Hzr62QLQ

**Comment by mf-code** [comment]
[5467] - xlxVCr2M

**Comment by mf-code** [comment]
[5467] - Allure report on Netlify: https://5ed1334ec5c7a97dc91a5092--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5468] - OuoClqzb

**Comment by mf-code** [comment]
[5468] - cIDTB5RA

**Comment by mf-code** [comment]
[5468] - YcCSpIEI

**Comment by mf-code** [comment]
[5468] - LYHKC1tq

**Comment by mf-code** [comment]
[5468] - b2IrA0VG

**Comment by mf-code** [comment]
[5468] - G4x8PJAD

**Comment by mf-code** [comment]
[5468] - JMsqxizS

**Comment by mf-code** [comment]
[5468] - HbU9CXlz

**Comment by mf-code** [comment]
[5468] - IAgl6oyF

**Comment by mf-code** [comment]
[5468] - zdQXXaG6

**Comment by mf-code** [comment]
[5468] - jetEp8a0

**Comment by mf-code** [comment]
[5468] - kcE6aFqh

**Comment by mf-code** [comment]
[5468] - cYZN9TCv

**Comment by mf-code** [comment]
[5468] - S8AqNkqt

**Comment by mf-code** [comment]
[5468] - odPXPuKW

**Comment by mf-code** [comment]
[5468] - NkQ0zhqL

**Comment by mf-code** [comment]
[5468] - 0DNWlZoJ

**Comment by mf-code** [comment]
[5468] - 9M3UOOIQ

**Comment by mf-code** [comment]
[5484] - e4RjuwqJ

**Comment by mf-code** [comment]
[5484] - CW8XuNJl

**Comment by mf-code** [comment]
[5484] - pITZZrtz

**Comment by mf-code** [comment]
[5484] - NMcQyjVH

**Comment by mf-code** [comment]
[5484] - IvBjioAd

**Comment by mf-code** [comment]
[5484] - g4a5q1dS

**Comment by mf-code** [comment]
[5484] - 1dyJpmJS

**Comment by mf-code** [comment]
[5484] - T67R19rp

**Comment by mf-code** [comment]
[5484] - Or69nRVw

**Comment by mf-code** [comment]
[5484] - iPflqM4j

**Comment by mf-code** [comment]
[5484] - B6Ijta8L

**Comment by mf-code** [comment]
[5484] - 0a7pfmlL

**Comment by mf-code** [comment]
[5484] - qL2Fr4bM

**Comment by mf-code** [comment]
[5484] - ZJvturIi

**Comment by mf-code** [comment]
[5484] - bSR0R49Z

**Comment by mf-code** [comment]
[5484] - BWkAWh3c

**Comment by mf-code** [comment]
[5484] - iH2grS5Y

**Comment by mf-code** [comment]
[5484] - vahYdqYt

**Comment by mf-code** [comment]
[5484] - oFLGxGcf

**Comment by mf-code** [comment]
[5484] - a5unadQD

**Comment by mf-code** [comment]
[5489] - WvEoo9cj

**Comment by mf-code** [comment]
[5489] - BtHaCDJl

**Comment by mf-code** [comment]
[5489] - JiJXTbhI

**Comment by mf-code** [comment]
[5489] - DkESGW5W

**Comment by mf-code** [comment]
[5489] - 4IFnlybf

**Comment by mf-code** [comment]
[5489] - c0yLPtKn

**Comment by mf-code** [comment]
[5489] - Lju6QLfM

**Comment by mf-code** [comment]
[5489] - yCI5s0Tk

**Comment by mf-code** [comment]
[5489] - uUvLCZAM

**Comment by mf-code** [comment]
[5489] - heMSsf8O

**Comment by mf-code** [comment]
[5489] - uYMCYR1U

**Comment by mf-code** [comment]
[5490] - MvyeIYg9

**Comment by mf-code** [comment]
[5490] - 0TDWHsw8

**Comment by mf-code** [comment]
[5490] - 6zygFcmv

**Comment by mf-code** [comment]
[5490] - chG03JQd

**Comment by mf-code** [comment]
[5490] - R6GU1Wlp

**Comment by mf-code** [comment]
[5490] - OJphxgSo

**Comment by mf-code** [comment]
[5490] - MFm6mYzs

**Comment by mf-code** [comment]
[5490] - p5xkMjzh

**Comment by mf-code** [comment]
[5490] - 0m8OeB5B

**Comment by mf-code** [comment]
[5490] - mkhysvrg

**Comment by mf-code** [comment]
[5490] - pKkK3m6x

**Comment by mf-code** [comment]
[5490] - K0SKTc02

**Comment by mf-code** [comment]
[5490] - ft71mizz

**Comment by mf-code** [comment]
[5490] - o3hOXEdB

**Comment by mf-code** [comment]
[5490] - FRN7OOSz

**Comment by mf-code** [comment]
[5490] - esTrN0Bu

**Comment by mf-code** [comment]
[5490] - LKWEwty1

**Comment by mf-code** [comment]
[5490] - EqShDS1F

**Comment by mf-code** [comment]
[5490] - b2ByGmih

**Comment by mf-code** [comment]
[5502] - 6CAO4Cob

**Comment by mf-code** [comment]
[5502] - fcYPTr5z

**Comment by mf-code** [comment]
[5502] - R6Qc9Dzv

**Comment by mf-code** [comment]
[5502] - Allure report on Netlify: https://5ed67d7064600de4fed3f0fb--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5503] - TLGzz9vR

**Comment by mf-code** [comment]
[5503] - oqXxENkN

**Comment by mf-code** [comment]
[5503] - Allure report on Netlify: https://5ed684a0661e514cef20a595--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5504] - eLB2aXZX

**Comment by mf-code** [comment]
[5504] - rS659GWt

**Comment by mf-code** [comment]
[5504] - Allure report on Netlify: https://5ed68b04edc914019525cfb0--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5505] - 7w4pDpyg

**Comment by mf-code** [comment]
[5505] - 6HSWdtZC

**Comment by mf-code** [comment]
[5505] - jMhFUV38

**Comment by mf-code** [comment]
[5505] - Allure report on Netlify: https://5ed76a199a339761d9d27814--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5507] - fsxGvC5A

**Comment by mf-code** [comment]
[5507] - OnNPs3Xn

**Comment by mf-code** [comment]
[5507] - FBkF255u

**Comment by mf-code** [comment]
[5507] - R6ptsyHB

**Comment by mf-code** [comment]
[5507] - Lazq5pfW

**Comment by mf-code** [comment]
[5507] - Vdu4W9JD

**Comment by mf-code** [comment]
[5507] - Lko5ymuy

**Comment by mf-code** [comment]
[5507] - CzoRkA04

**Comment by mf-code** [comment]
[5507] - 6isES9Gi

**Comment by mf-code** [comment]
[5507] - BQ20cnbx

**Comment by mf-code** [comment]
[5507] - 7BDWJAxa

**Comment by mf-code** [comment]
[5510] - jjK3uAEM

**Comment by mf-code** [comment]
[5510] - OKbYqrjO

**Comment by mf-code** [comment]
[5510] - I5jbJhC4

**Comment by mf-code** [comment]
[5510] - HthJEoBM

**Comment by mf-code** [comment]
[5510] - B0oNdk49

**Comment by mf-code** [comment]
[5510] - jnPjiVaU

**Comment by mf-code** [comment]
[5511] - Dyd1oXrO

**Comment by mf-code** [comment]
[5511] - 1VJx9jtB

**Comment by mf-code** [comment]
[5511] - GWxlsFXZ

**Comment by mf-code** [comment]
[5511] - lMYWjC7Q

**Comment by mf-code** [comment]
[5511] - c7qvbYkd

**Comment by mf-code** [comment]
[5511] - CkEqcfBk

**Comment by mf-code** [comment]
[5511] - Allure report on Netlify: https://5ed78d95a3cd23ee6d4997dd--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5517] - cJ786Jvk

**Comment by mf-code** [comment]
[5517] - Z5mQcOXQ

**Comment by mf-code** [comment]
[5517] - A8T5BcvL

**Comment by mf-code** [comment]
[5517] - SwYszRGl

**Comment by mf-code** [comment]
[5517] - 4Q2BQtOM

**Comment by mf-code** [comment]
[5517] - 2lfQUFQj

**Comment by mf-code** [comment]
[5517] - YQwm2Mo8

**Comment by mf-code** [comment]
[5517] - bLkrHNzz

**Comment by mf-code** [comment]
[5517] - 4hZP4Bd4

**Comment by mf-code** [comment]
[5517] - QoIMdi6p

**Comment by mf-code** [comment]
[5517] - aN086QPF

**Comment by mf-code** [comment]
[5517] - Uh1PRgvZ

**Comment by mf-code** [comment]
[5517] - GysJc64W

**Comment by mf-code** [comment]
[5517] - Allure report on Netlify: https://5ed7bcd87efbaa7d18d48924--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5523] - W577D7sl

**Comment by mf-code** [comment]
[5523] - qUls10qM

**Comment by mf-code** [comment]
[5523] - mIW8p7t3

**Comment by mf-code** [comment]
[5523] - bycnhKC5

**Comment by mf-code** [comment]
[5523] - BWswij8t

**Comment by mf-code** [comment]
[5523] - anUonpll

**Comment by mf-code** [comment]
[5523] - 3jPdrSqZ

**Comment by mf-code** [comment]
[5523] - zu95fAte

**Comment by mf-code** [comment]
[5523] - WTK1ED9z

**Comment by mf-code** [comment]
[5523] - 8kHDBPXx

**Comment by mf-code** [comment]
[5523] - EwSokJmI

**Comment by mf-code** [comment]
[5524] - 37jkWMIS

**Comment by mf-code** [comment]
[5524] - hPSePQYE

**Comment by mf-code** [comment]
[5524] - 19RRqtHd

**Comment by mf-code** [comment]
[5524] - Allure report on Netlify: https://5ed7d542b392f5021498b0a6--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5525] - ucFXHhSI

**Comment by mf-code** [comment]
[5525] - 7IsrosHJ

**Comment by mf-code** [comment]
[5525] - Pu7t2PwU

**Comment by mf-code** [comment]
[5525] - 6jxNb5Ub

**Comment by mf-code** [comment]
[5525] - Allure report on Netlify: https://5ed8036c7bc41201e0c2d8c5--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5526] - aBymgaRC

**Comment by mf-code** [comment]
[5526] - fRq5BZVg

**Comment by mf-code** [comment]
[5526] - 49x8GqTl

**Comment by mf-code** [comment]
[5526] - hJqzd9th

**Comment by mf-code** [comment]
[5526] - Allure report on Netlify: https://5ed80b5d9fc65b8dbe62ef5a--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5527] - ioYOcH70

**Comment by mf-code** [comment]
[5527] - DfHWCwUh

**Comment by mf-code** [comment]
[5527] - Qo8T4ogP

**Comment by mf-code** [comment]
[5527] - t9B5WHHo

**Comment by mf-code** [comment]
[5527] - Allure report on Netlify: https://5ed8124346577f01c080fb47--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5528] - SfgZLCqW

**Comment by mf-code** [comment]
[5528] - dklF8wtr

**Comment by mf-code** [comment]
[5528] - i4PcjEdx

**Comment by mf-code** [comment]
[5528] - FZViatem

**Comment by mf-code** [comment]
[5528] - Allure report on Netlify:

**Comment by mf-code** [comment]
[5528] - Allure report on Netlify:

**Comment by mf-code** [comment]
[5528] - Allure report on Netlify:

**Comment by mf-code** [comment]
[5529] - uRmU9BoC

**Comment by mf-code** [comment]
[5529] - e5fUX2Zh

**Comment by mf-code** [comment]
[5529] - mdkrJTVy

**Comment by mf-code** [comment]
[5529] - XhUYvPh4

**Comment by mf-code** [comment]
[5529] - Allure report on Netlify:

**Comment by mf-code** [comment]
[5529] - Allure report on Netlify:

**Comment by mf-code** [comment]
[5529] - Allure report on Netlify:

**Comment by mf-code** [comment]
[5530] - ScuWxSPJ

**Comment by mf-code** [comment]
[5530] - YPO1zPBw

**Comment by mf-code** [comment]
[5530] - 9S8D86yR

**Comment by mf-code** [comment]
[5530] - CPNuAu57

**Comment by mf-code** [comment]
[5530] - Allure report on Netlify: https://5ed8286c6616f7b978d8417c--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5530] - Allure report on Netlify: https://5ed8287d5d406880c1bbf323--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5530] - Allure report on Netlify: https://5ed8288a99c6218bdbecb9e7--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5531] - oRBs7FPW

**Comment by mf-code** [comment]
[5531] - FYCGDVea

**Comment by mf-code** [comment]
[5531] - LDTvTD23

**Comment by mf-code** [comment]
[5531] - OXhAJQiv

**Comment by mf-code** [comment]
[5531] - openjdk8 - Allure report on Netlify: https://5ed8301aa9898cfe1264c42c--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5531] - openjdk10 - Allure report on Netlify: https://5ed8302aa9898cf72f64c790--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5531] - openjdk11 - Allure report on Netlify: https://5ed83035ae20140921102ba7--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5533] - nw4KtAK4

**Comment by mf-code** [comment]
[5533] - IP7QrmSY

**Comment by mf-code** [comment]
[5533] - jcBTOHzq

**Comment by mf-code** [comment]
[5533] - IRoCRC7p

**Comment by mf-code** [comment]
[5533] - { - Allure report on Netlify: RESULT:

**Comment by mf-code** [comment]
[5533] - { - Allure report on Netlify: RESULT:

**Comment by mf-code** [comment]
[5533] - { - Allure report on Netlify: RESULT:

**Comment by mf-code** [comment]
[5535] - 4Ge8N6n0

**Comment by mf-code** [comment]
[5535] - emnilgCl

**Comment by mf-code** [comment]
[5535] - MWEflt00

**Comment by mf-code** [comment]
[5535] - Aor49jWY

**Comment by mf-code** [comment]
[5535] - of - Allure report on Netlify: Start

**Comment by mf-code** [comment]
[5535] - of - Allure report on Netlify: Start

**Comment by mf-code** [comment]
[5535] - of - Allure report on Netlify: Start

**Comment by mf-code** [comment]
[5536] - YQQJVOxN

**Comment by mf-code** [comment]
[5536] - krDDifa5

**Comment by mf-code** [comment]
[5536] - ARR5Wpkf

**Comment by mf-code** [comment]
[5536] - HuKwURki

**Comment by mf-code** [comment]
[5536] - openjdk8 - Allure report on Netlify: https://5ed8cbb99f98c83025b71a5d--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5536] - openjdk10 - Allure report on Netlify: https://5ed8cbc67b43e69855e5bebf--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5536] - openjdk11 - Allure report on Netlify: https://5ed8cbd199c621d975ecb984--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5537] - w0xSntAE

**Comment by mf-code** [comment]
[5537] - kW3abA0v

**Comment by mf-code** [comment]
[5537] - NT5Mnj6l

**Comment by mf-code** [comment]
[5537] - FYohjcGT

**Comment by mf-code** [comment]
[5537] - zQ3owr8o

**Comment by mf-code** [comment]
[5537] - DdmkAO7M

**Comment by mf-code** [comment]
[5537] - Tf305vJ9

**Comment by mf-code** [comment]
[5537] - openjdk8 - Allure report on Netlify: https://5ed8d15b99c6216c2decb705--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5537] - openjdk10 - Allure report on Netlify: https://5ed8d17399c62120bcecb9b7--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5537] - openjdk11 - Allure report on Netlify: https://5ed8d1c799c6216791ecb823--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5539] - 0C32RRVN

**Comment by mf-code** [comment]
[5539] - Bfi5Jxuq

**Comment by mf-code** [comment]
[5539] - Itqn7LDx

**Comment by mf-code** [comment]
[5539] - 3smOWz3v

**Comment by mf-code** [comment]
[5539] - 5SKJ8t1l

**Comment by mf-code** [comment]
[5539] - lTbID5PX

**Comment by mf-code** [comment]
[5539] - P9zSCDGk

**Comment by mf-code** [comment]
[5539] -  - Allure report on Netlify: openjdk8

**Comment by mf-code** [comment]
[5539] -  - Allure report on Netlify: openjdk10

**Comment by mf-code** [comment]
[5539] -  - Allure report on Netlify: openjdk11

**Comment by mf-code** [comment]
[5540] - qj63f8Ku

**Comment by mf-code** [comment]
[5540] - jmvUK0hf

**Comment by mf-code** [comment]
[5540] - nHuLsJiu

**Comment by mf-code** [comment]
[5540] - jqy72X9J

**Comment by mf-code** [comment]
[5540] - qmPQEOp8

**Comment by mf-code** [comment]
[5540] - rCAvaesj

**Comment by mf-code** [comment]
[5540] - 5W9x4WBA

**Comment by mf-code** [comment]
[5540] - uBp187Jd

**Comment by mf-code** [comment]
[5540] - xZIU45Hx

**Comment by mf-code** [comment]
[5540] - 2C6QuSw9

**Comment by mf-code** [comment]
[5540] - openjdk8 - Allure report on Netlify: https://5ed8e218a9898ce3e064c3c6--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5540] - openjdk10 - Allure report on Netlify: https://5ed8e2791522738fa2b01181--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5540] - openjdk11 - Allure report on Netlify: https://5ed8e2dd7b43e69a52e5bf3d--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5563] - yEQpCI7b

**Comment by mf-code** [comment]
[5563] - QNIEFQjE

**Comment by mf-code** [comment]
[5563] - HkkM4EmA

**Comment by mf-code** [comment]
[5563] - qi1lmi6N

**Comment by mf-code** [comment]
[5563] - 1Aa1LKie

**Comment by mf-code** [comment]
[5563] - QRMqygFm

**Comment by mf-code** [comment]
[5563] - PL1OTUT2

**Comment by mf-code** [comment]
[5563] - 6TxbWX7Z

**Comment by mf-code** [comment]
[5563] - a9Bma5qz

**Comment by mf-code** [comment]
[5563] - openjdk8 - Allure report on Netlify: https://5eda735179ccc3881c1b28cf--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5563] - openjdk10 - Allure report on Netlify: https://5eda73614fca8e6d54705ade--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5563] - openjdk11 - Allure report on Netlify: https://5eda73b34fca8ea6f07057ec--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5564] - 9wuUGi7a

**Comment by mf-code** [comment]
[5564] - no8WhuLX

**Comment by mf-code** [comment]
[5564] - 5LgXolP2

**Comment by mf-code** [comment]
[5564] - ue6KI90j

**Comment by mf-code** [comment]
[5564] - Ewusgo5b

**Comment by mf-code** [comment]
[5564] - nSMbTUme

**Comment by mf-code** [comment]
[5564] - defxLamo

**Comment by mf-code** [comment]
[5564] - YlCi2Oh5

**Comment by mf-code** [comment]
[5564] - vFlDZ47a

**Comment by mf-code** [comment]
[5564] - openjdk8 - Allure report on Netlify: https://5eda7da29834a30fcd003071--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5564] - openjdk10 - Allure report on Netlify: https://5eda7db1b186b60bc55a1760--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5564] - openjdk11 - Allure report on Netlify: https://5eda7e01f5a8b06b09ce7ee7--musing-swartz-6fc060.netlify.app

**Comment by clockworkbanana** [comment]
Closing this PR as it is no longer needed.
All changes are located in #2065

**Pull request closed without merging**
