### PR TITLE
1523 textfield html example

### PR DESCRIPTION
**Pull request by hellokitties**
#1606

### CODE REVIEW

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/example/common/TextFieldExampleTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/42_/jdi-light/pullRequest?prid=4724970&bid=15774440)

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/example/common/TextFieldExampleTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/42_/jdi-light/pullRequest?prid=4724970&bid=15774440)

**Comment by mf-code** [comment]
[4333] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4333] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4333] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4333] - Allure report on Netlify: https://5e00ef53e91cba3888f913af--musing-swartz-6fc060.netlify.com

**Comment by mf-code** [comment]
[4337] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4337] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4337] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4337] - Allure report on Netlify: https://5e00fc38e9ce84f13b2ae224--musing-swartz-6fc060.netlify.com

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/example/common/TextFieldExampleTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/42_/jdi-light/pullRequest?prid=4724970&bid=15774440)

**Comment by mf-code** [comment]
[4380] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4380] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4380] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4380] - Allure report on Netlify: https://5e036f3cde0510a44a4bc4ec--musing-swartz-6fc060.netlify.com

**Pull request merged**
