### PR TITLE
1533 html example MultiSelector

### PR DESCRIPTION
**Pull request by ArKhmeln**

### CODE REVIEW

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/example/complex/MultiSelectorExampleTests.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=4738145&bid=15815673)

**Comment by mf-code** [comment]
[4397] - https://transfer.sh/eLNdb/jdi-light-examples.tar.gz

**Comment by mf-code** [comment]
[4397] - https://transfer.sh/7rTcb/jdi-performance.tar.gz

**Comment by mf-code** [comment]
[4397] - https://transfer.sh/Zzwhq/jdi-light-html-tests.tar.gz

**Comment by mf-code** [comment]
[4397] - Allure report on Netlify: https://5e05fdf82799fc01d2d448f9--musing-swartz-6fc060.netlify.com

**Pull request merged**
