### PR TITLE
pull request for Roman corrections

### PR DESCRIPTION
**Pull request by AlexSofft**
@AfterMethod added into BottomSheetTests and BottomSheetUnotTests to make them work out: after hook remove floating element that blocks further tests execution

### CODE REVIEW

**Comment by mf-code** [comment]
[6388] - EZ3rWoeKgiWq

**Comment by mf-code** [comment]
[6388] - VumAQVhdnPif

**Comment by mf-code** [comment]
[6388] - mcQ2QddkqJXN

**Comment by mf-code** [comment]
[6388] - y66rznvneYqq

**Comment by mf-code** [comment]
[6388] - MgGpslEfhQNg

**Comment by mf-code** [comment]
[6388] - xMRX2h9UojTu

**Comment by mf-code** [comment]
[6388] - ffFVadniv6rA

**Comment by mf-code** [comment]
[6388] - 49cctgMBEBzP

**Comment by mf-code** [comment]
[6388] - aPmktK2AlgTi

**Comment by mf-code** [comment]
[6388] - W6aQeoqavzCc

**Comment by mf-code** [comment]
[6388] - Ifgi1sYmrn43

**Comment by mf-code** [comment]
[6388] - 5c6bbGgVOVko

**Comment by mf-code** [comment]
[6388] - VFHRn5k51Ses

**Comment by RomanIovlev** [comment]
Outdated

**Pull request closed without merging**
