### PR TITLE
1955 tree

### PR DESCRIPTION
**Pull request by vsevolod-adrianov**
expand tree node by name

### CODE REVIEW

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/MaterialTreeTests.java  1
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/MaterialTree.java  3
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6314927&bid=20531743)

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/TreeAssert.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/MaterialTreeTests.java  1
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/MaterialTree.java  3
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6314927&bid=20531743)

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/MaterialTree.java  3
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/TreeAssert.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/MaterialTreeTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6314927&bid=20531743)

**Comment by mf-code** [comment]
[6273] - kL5JfNbV5Nd5

**Comment by mf-code** [comment]
[6273] - M8I2FJuDVB5G

**Comment by mf-code** [comment]
[6273] - hyCAcdkFtXfa

**Comment by mf-code** [comment]
[6273] - gbUFSGnJTRIR

**Comment by mf-code** [comment]
[6273] - jSniDUGvw57e

**Comment by mf-code** [comment]
[6273] - pKIzbrdupN3S

**Comment by mf-code** [comment]
[6273] - wQqCV0iT4n4f

**Comment by mf-code** [comment]
[6273] - ic14xlJ8xZW0

**Comment by mf-code** [comment]
[6273] - 7TZD4FPxhGFe

**Comment by mf-code** [comment]
[6273] - iLGmNhrudtWk

**Comment by mf-code** [comment]
[6273] - IZkqfCzPqa8U

**Comment by mf-code** [comment]
[6273] - 7z7iv1HsRutF

**Comment by mf-code** [comment]
[6273] - sNExrXtPDL4f

**Comment by mf-code** [comment]
[6273] - MsYN0WVAQrug

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/MaterialTree.java  3
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/TreeAssert.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/MaterialTreeTests.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6314927&bid=20531743)

**Comment by mf-code** [comment]
[6282] - 6bYws2wDLKUT

**Comment by mf-code** [comment]
[6282] - OTmoAiAexOX2

**Comment by mf-code** [comment]
[6282] - LC8r9WbzZgCm

**Comment by mf-code** [comment]
[6282] - 1nXH8he1igSJ

**Comment by mf-code** [comment]
[6282] - DqXieVwRwzJh

**Comment by mf-code** [comment]
[6282] - m85UIf7qeOBW

**Comment by mf-code** [comment]
[6282] - RHLGpNrIZiuK

**Comment by mf-code** [comment]
[6282] - GdAFYe7VtxSX

**Comment by mf-code** [comment]
[6282] - Pz1XT9pjRoCA

**Comment by mf-code** [comment]
[6282] - sJdhwJnJC4PF

**Comment by mf-code** [comment]
[6282] - DPZpMR0n4odU

**Comment by mf-code** [comment]
[6282] - 4A5hBoDv2g77

**Comment by mf-code** [comment]
[6282] - 5RLkcGP1BUpF

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/MaterialTreeTests.java  1
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/MaterialTree.java  3
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/TreeAssert.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6314927&bid=20531743)

**Comment by mf-code** [comment]
[6283] - 8st4PmjMaDpa

**Comment by mf-code** [comment]
[6283] - gMaaVeKV2yl5

**Comment by mf-code** [comment]
[6283] - D4cssrPnWB2s

**Comment by mf-code** [comment]
[6283] - sv3LoC5ZGhXo

**Comment by mf-code** [comment]
[6283] - BHlFzIH0vMmR

**Comment by mf-code** [comment]
[6283] - s3nHiF0bnPfY

**Comment by mf-code** [comment]
[6283] - 1wF5qmHzLxdA

**Comment by mf-code** [comment]
[6283] - m7ZVL5bphffW

**Comment by mf-code** [comment]
[6283] - Jxlj1PeDLwv4

**Comment by mf-code** [comment]
[6283] - HHPmAGRm6duk

**Comment by mf-code** [comment]
[6283] - TPqcYvWx14lo

**Comment by mf-code** [comment]
[6283] - WiizWxCDnzst

**Comment by mf-code** [comment]
[6283] - xacMhib1olV8

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/TreeAssert.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/MaterialTreeTests.java  1
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/MaterialTree.java  3
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6314927&bid=20531743)

**Comment by mf-code** [comment]
[6285] - VGJNKlFchrp8

**Comment by mf-code** [comment]
[6285] - QxPTmA2nqYZg

**Comment by mf-code** [comment]
[6285] - WsC71uzF4uXX

**Comment by mf-code** [comment]
[6285] - z7rd5R7qhDdO

**Comment by mf-code** [comment]
[6285] - cHMbWRzYq1zR

**Comment by mf-code** [comment]
[6285] - YsCGUHYthLtV

**Comment by mf-code** [comment]
[6285] - zNB7zXBJJthP

**Comment by mf-code** [comment]
[6285] - xPEWzzlqX6MQ

**Comment by mf-code** [comment]
[6285] - GQ3dNLvqfPQC

**Comment by mf-code** [comment]
[6285] - 6CNQOft9foSo

**Comment by mf-code** [comment]
[6285] - XXCvzI37WpSm

**Comment by mf-code** [comment]
[6285] - tND5CHtiKa0y

**Comment by mf-code** [comment]
[6285] - ayfWElBUex6E

**Comment by mf-code** [comment]
[6285] - SzW1r0Zji7cf

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/MaterialTree.java  3
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/MaterialTreeTests.java  1
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/TreeAssert.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6314927&bid=20531743)

**Comment by mf-code** [comment]
[6296] - sFX8wfxgCOLP

**Comment by mf-code** [comment]
[6296] - CktzS6oE7SHn

**Comment by mf-code** [comment]
[6296] - KPUUQIuYUIhU

**Comment by mf-code** [comment]
[6296] - SjUCOZZYg8Lh

**Comment by mf-code** [comment]
[6296] - Af9B51Z3CUEE

**Comment by mf-code** [comment]
[6296] - E5vZZoNLS0CW

**Comment by mf-code** [comment]
[6296] - B27pum0eJsW3

**Comment by mf-code** [comment]
[6296] - WJYQn9901T71

**Comment by mf-code** [comment]
[6296] - pCPs6pBxQjsa

**Comment by mf-code** [comment]
[6296] - U91l81YmpzUL

**Comment by mf-code** [comment]
[6296] - q2xdxf52gifu

**Comment by mf-code** [comment]
[6296] - DfMzbOxPH3xU

**Comment by mf-code** [comment]
[6296] - sT4GEUxDgpDn

**Comment by mf-code** [comment]
[6296] - zM9dqSLaTPT4

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/TreeAssert.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/MaterialTreeTests.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/MaterialTree.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6314927&bid=20531743)

**Comment by mf-code** [comment]
[6301] - jw9sXwQo9YOQ

**Comment by mf-code** [comment]
[6301] - VHHz2WGS8x2E

**Comment by mf-code** [comment]
[6301] - 2rz4M5DpsJ3b

**Comment by mf-code** [comment]
[6301] - no0oYJvlP5it

**Comment by mf-code** [comment]
[6301] - lyCE7j6ujm5i

**Comment by mf-code** [comment]
[6301] - 4NXjgObwzEnm

**Comment by mf-code** [comment]
[6301] - F3a2gfk0fSbA

**Comment by mf-code** [comment]
[6301] - 17CT8GStfpFC

**Comment by mf-code** [comment]
[6301] - 9iN0wRsZ1E2u

**Comment by mf-code** [comment]
[6301] - 9cOWZdIHn0Qu

**Comment by mf-code** [comment]
[6301] - 6T7ta8YD8nLS

**Comment by mf-code** [comment]
[6301] - EzuAJ6VwiWNT

**Comment by mf-code** [comment]
[6301] - 1c6Jzj2eRwVK

**Comment by mf-code** [comment]
[6301] - HqZKjZ0iTktU

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/TreeAssert.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TreeUnitTests.java  1
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/MaterialTree.java  3
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/MaterialTreeTests.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6314927&bid=20531743)

**Comment by mf-code** [comment]
[6310] - C7nOHT4nHnIE

**Comment by mf-code** [comment]
[6310] - tdEPiSENa2TT

**Comment by mf-code** [comment]
[6310] - WfvPgUocZeay

**Comment by mf-code** [comment]
[6310] - 0QmLDeNqlphs

**Comment by mf-code** [comment]
[6310] - 7L5WCfiEXeb8

**Comment by mf-code** [comment]
[6310] - kBOsMagOVYkq

**Comment by mf-code** [comment]
[6310] - FJbXuhe5YnPM

**Comment by mf-code** [comment]
[6310] - F1h0XmLFpK8n

**Comment by mf-code** [comment]
[6310] - 4dRcSZ4EEu1D

**Comment by mf-code** [comment]
[6310] - yiply4fv4Ic1

**Comment by mf-code** [comment]
[6310] - hozMHyPjhQdf

**Comment by mf-code** [comment]
[6310] - wxxVI2Bzdtc5

**Comment by mf-code** [comment]
[6310] - ykcbwEl5qMSM

**Comment by mf-code** [comment]
[6310] - nhEI2HBkGfpQ

**Comment by mf-code** [comment]
[6310] - qjgRtrYoDcrS

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TreeUnitTests.java  1
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/MaterialTree.java  3
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/MaterialTreeTests.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/TreeAssert.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6314927&bid=20531743)

**Comment by mf-code** [comment]
[6314] - 6QY3Zd659268

**Comment by mf-code** [comment]
[6314] - D8rWP8IxHrv5

**Comment by mf-code** [comment]
[6314] - EQW0AVStZVV9

**Comment by mf-code** [comment]
[6314] - H9vuVB75KgRj

**Comment by mf-code** [comment]
[6314] - mkVVW8sMrZCz

**Comment by mf-code** [comment]
[6314] - DKvhAT9TblMB

**Comment by mf-code** [comment]
[6314] - v2dbBMAF91A9

**Comment by mf-code** [comment]
[6314] - MnA0MziNNp50

**Comment by mf-code** [comment]
[6314] - smSqwWaiXZl1

**Comment by mf-code** [comment]
[6314] - gmoRYjekzjAc

**Comment by mf-code** [comment]
[6314] - fIPmYYKHKYHE

**Comment by mf-code** [comment]
[6314] - eO6SvZKWGIAY

**Comment by mf-code** [comment]
[6314] - 0w5m16e2OCAd

**Comment by mf-code** [comment]
[6314] - tmbwsihj2JSI

**Comment by mf-code** [comment]
[6314] - 2FyMGL42LLqu

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/MaterialTree.java  4
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/TreeAssert.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TreeUnitTests.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/MaterialTreeTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6314927&bid=20531743)

**Comment by mf-code** [comment]
[6316] - l8ieAX3hQh3j

**Comment by mf-code** [comment]
[6316] - 30OCC7Q6VLsE

**Comment by mf-code** [comment]
[6316] - eY5ajESGnOGl

**Comment by mf-code** [comment]
[6316] - h4P4ZmxTOlo9

**Comment by mf-code** [comment]
[6316] - pQhy7FhtPSFo

**Comment by mf-code** [comment]
[6316] - ZI247Lo1eUOJ

**Comment by mf-code** [comment]
[6316] - a1DXZFMiDa3D

**Comment by mf-code** [comment]
[6316] - G5mu0ja3oeWX

**Comment by mf-code** [comment]
[6316] - Fg77NVmRH1mR

**Comment by mf-code** [comment]
[6316] - zFVhk2BIklaX

**Comment by mf-code** [comment]
[6316] - gmgZPYLx4c3Y

**Comment by mf-code** [comment]
[6316] - G8EqdRzeMrBQ

**Comment by mf-code** [comment]
[6316] - ZMwk2Yi7hviU

**Comment by mf-code** [comment]
[6316] - Rt4ouyX84iuw

**Comment by mf-code** [comment]
[6316] - ECtambQ13E5y

**Comment by mf-code** [comment]
[6316] - pkvlOiqGmlpJ

**Comment by mf-code** [comment]
[6316] - 8xQZej1NFAjm

**Comment by mf-code** [comment]
[6316] - GPUO2gucUPJB

**Comment by mf-code** [comment]
[6316] - y88f958QH8jl

**Comment by mf-code** [comment]
[6316] - WVa0O508L2sy

**Comment by mf-code** [comment]
[6316] - GUM1WoWTvTPY

**Comment by mf-code** [comment]
[6316] - s9sz92tcPJSi

**Comment by mf-code** [comment]
[6316] - 8WeqX4sMD6pg

**Comment by mf-code** [comment]
[6316] - PcyAJ9nTcOFd

**Comment by mf-code** [comment]
[6316] - KuwhAAErx0B4

**Comment by mf-code** [comment]
[6316] - kP7syS3KyWZG

**Comment by mf-code** [comment]
[6316] - qNDTD4fCDdVT

**Comment by mf-code** [comment]
[6316] - eF0olI0LNOSu

**Comment by mf-code** [comment]
[6316] - TI12OtoHmbmo

**Comment by mf-code** [comment]
[6316] - 4asfiMez7YmV

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/MaterialTreeTests.java  1
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/TreeAssert.java  1
- jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/MaterialTree.java  4
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TreeUnitTests.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6314927&bid=20531743)

**Comment by mf-code** [comment]
[6331] - KZf6z8jZnL36

**Comment by mf-code** [comment]
[6331] - ENiBbfOPu7JN

**Comment by mf-code** [comment]
[6331] - u1xtivkEWP0z

**Comment by mf-code** [comment]
[6331] - lMcsztsAHLXg

**Comment by mf-code** [comment]
[6331] - SS2u55uxk6DC

**Comment by mf-code** [comment]
[6331] - 3Mm5l4peXhIK

**Comment by mf-code** [comment]
[6331] - 7p9kSeRotiua

**Comment by mf-code** [comment]
[6331] - RC8HtWsjcQIj

**Comment by mf-code** [comment]
[6331] - MDtoSXlyPGGg

**Comment by mf-code** [comment]
[6331] - BGrLoFcJuOmK

**Comment by mf-code** [comment]
[6331] - K9AJPBNxsCUX

**Comment by mf-code** [comment]
[6331] - YERnmJrq2YBV

**Comment by mf-code** [comment]
[6331] - PRHIGvGjhwtV

**Comment by mf-code** [comment]
[6331] - rUHFumbqRSwj

**Comment by RomanIovlev** [comment]
Merged into pull_request_for_Roman

**Pull request closed without merging**
