### PR TITLE
Adjusted MaterialSelectorContainer and DatepickerContainer classes.

### PR DESCRIPTION
**Pull request by gbuh**
Adjusted MaterialSelectorContainer class.

### CODE REVIEW

**Comment by mf-code** [comment]
[5969] - zsGKmdkHbdly

**Comment by mf-code** [comment]
[5969] - n0ejp4UrqBS3

**Comment by mf-code** [comment]
[5969] - K5Uz1thxhquU

**Comment by mf-code** [comment]
[5969] - JvScMTRwl1y0

**Comment by mf-code** [comment]
[5969] - ICJ00u3vodix

**Comment by mf-code** [comment]
[5969] - yExzE76d5GW4

**Comment by mf-code** [comment]
[5969] - rqjSLyuDzDFw

**Comment by mf-code** [comment]
[5969] - UflAnDS6qIsW

**Comment by mf-code** [comment]
[5969] - TYxEMvkPyd9A

**Comment by mf-code** [comment]
[5969] - CQmdeaSru8g5

**Comment by mf-code** [comment]
[5969] - k2lpfJVNbOMU

**Comment by mf-code** [comment]
[5969] - dvQmzpFK1dV0

**Comment by mf-code** [comment]
[5969] - irrwPW4TQuyP

**Comment by mf-code** [comment]
[5969] - bZ360k4HcH1W

**Comment by mf-code** [comment]
[5969] - FyKfqhCIr4e5

**Comment by mf-code** [comment]
[5969] - CVUV0tMMxnZm

**Comment by mf-code** [comment]
[5969] - 9ImzD28f8vjW

**Comment by mf-code** [comment]
[5969] - 1tpLIT9Gjxcm

**Comment by mf-code** [comment]
[5969] - openjdk8 - Allure report on Netlify: https://5f4cd4efe2799f0ae0169ee2--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5969] - openjdk10 - Allure report on Netlify: https://5f4cd667e2799f094016a2e8--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5974] - ONks8FXPIIB9

**Comment by mf-code** [comment]
[5974] - v8RmLpvCyxiV

**Comment by mf-code** [comment]
[5974] - KlAR24bhtAJO

**Comment by mf-code** [comment]
[5974] - wAmSnkBnoVOY

**Comment by mf-code** [comment]
[5974] - ijWybApr99La

**Comment by mf-code** [comment]
[5974] - hQWzhYgk0MTm

**Comment by mf-code** [comment]
[5974] - pWPoFgymnew3

**Comment by mf-code** [comment]
[5974] - zjZY2J53Y5hc

**Comment by mf-code** [comment]
[5974] - lAQa4tfQgtxL

**Comment by mf-code** [comment]
[5974] - cWhV2yqa7YBI

**Comment by mf-code** [comment]
[5974] - VqrLXDGbQWuD

**Comment by mf-code** [comment]
[5974] - Kx3t3s2dNFVM

**Comment by mf-code** [comment]
[5974] - 1Tnd0v9Mmqmc

**Comment by mf-code** [comment]
[5974] - tYZPWQYyPwms

**Comment by mf-code** [comment]
[5974] - wTuadLysiLjP

**Comment by mf-code** [comment]
[5974] - mXK6qz0RCu6Q

**Comment by mf-code** [comment]
[5974] - F26nZiyFCP98

**Comment by mf-code** [comment]
[5974] - ZnTzaQfCtcXz

**Comment by mf-code** [comment]
[5974] - openjdk8 - Allure report on Netlify: https://5f4d068a35dfbb486da680c3--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5974] - openjdk10 - Allure report on Netlify: https://5f4d0817d572723ebe7074e7--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5977] - uS0YeyUJPs6d

**Comment by mf-code** [comment]
[5977] - YmkAijbBq0Ji

**Comment by mf-code** [comment]
[5977] - zNzNIhkcvRxf

**Comment by mf-code** [comment]
[5977] - bje1U86zqScb

**Comment by mf-code** [comment]
[5977] - irSO1xKGTpFe

**Comment by mf-code** [comment]
[5977] - QOkySUKsNbkF

**Comment by mf-code** [comment]
[5977] - BspoGfWELR8T

**Comment by mf-code** [comment]
[5977] - ebYqIX9lEGic

**Comment by mf-code** [comment]
[5977] - 5P4llUU1aoEr

**Comment by mf-code** [comment]
[5977] - vY63Dh8yPwBn

**Comment by mf-code** [comment]
[5977] - Lu9KK5ky3hMl

**Comment by mf-code** [comment]
[5977] - kc6nEkZw6Xvz

**Comment by mf-code** [comment]
[5977] - iTRSsJNfwft5

**Comment by mf-code** [comment]
[5977] - w9Jx6qZy78OV

**Comment by mf-code** [comment]
[5977] - 2e7eAzVWAT4x

**Comment by mf-code** [comment]
[5977] - UoEpnLdqGheK

**Comment by mf-code** [comment]
[5977] - 84zWv6Dy00Vz

**Comment by mf-code** [comment]
[5977] - nNcQ68WqbZ0A

**Comment by mf-code** [comment]
[5977] - openjdk8 - Allure report on Netlify: https://5f4e24a1529e1ac4c784b5df--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5977] - openjdk10 - Allure report on Netlify: https://5f4e2612ef6c12c04ce05ff8--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5980] - h7tEqcTvqJ8W

**Comment by mf-code** [comment]
[5980] - O8P0x0vNCjHV

**Comment by mf-code** [comment]
[5980] - BOaTbxaKGnjY

**Comment by mf-code** [comment]
[5980] - WwUdiqddB1fR

**Comment by mf-code** [comment]
[5980] - 4tG245YqYsri

**Comment by mf-code** [comment]
[5980] - AwhbtNiBqDfI

**Comment by mf-code** [comment]
[5980] - h1YBYHPxo69x

**Comment by mf-code** [comment]
[5980] - ZeoWVA3Jjfk9

**Comment by mf-code** [comment]
[5980] - d442Z4Dw4FPJ

**Comment by mf-code** [comment]
[5980] - hZkAESJhiqYH

**Comment by mf-code** [comment]
[5980] - RRgAhDrDdcWf

**Comment by mf-code** [comment]
[5980] - LwZJ6oufZ2Wd

**Comment by mf-code** [comment]
[5980] - cHgL2BSwbcTx

**Comment by mf-code** [comment]
[5980] - fPUv3kmCDtZS

**Comment by mf-code** [comment]
[5980] - sjoyXjXTGlEc

**Comment by mf-code** [comment]
[5980] - w56y3G9YQN6X

**Comment by mf-code** [comment]
[5980] - 1dcvPtI6j1LI

**Comment by mf-code** [comment]
[5980] - q2CMBsoGHy5s

**Comment by mf-code** [comment]
[5980] - tLxNfHNAnXDA

**Comment by mf-code** [comment]
[5980] - GUGGNjC9PAcW

**Comment by mf-code** [comment]
[5980] - vYbySSr1wDIH

**Comment by mf-code** [comment]
[5980] - UPvZGoqMQ59k

**Comment by mf-code** [comment]
[5980] - openjdk8 - Allure report on Netlify: https://5f4ec31db4a6eb00a7a7eddd--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5980] - openjdk10 - Allure report on Netlify: https://5f4ec4e8d5a7ef012fc5097f--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5980] - openjdk10 - Allure report on Netlify: https://5f4f37f2e3b6fa57e00f8bb4--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5988] - Z9sd0YgVTpH5

**Comment by mf-code** [comment]
[5988] - pjQMm1b0qmfo

**Comment by mf-code** [comment]
[5988] - iJBqUfi9fxSl

**Comment by mf-code** [comment]
[5988] - UCicuPRBcN1E

**Comment by mf-code** [comment]
[5988] - mpdtcoYzkcTs

**Comment by mf-code** [comment]
[5988] - hmhRxO2KUdBK

**Comment by mf-code** [comment]
[5988] - q6qJCIjGhhi6

**Comment by mf-code** [comment]
[5988] - bRuqEQk0RQdq

**Comment by mf-code** [comment]
[5988] - dVhIPk1fjbNg

**Comment by mf-code** [comment]
[5988] - BWzRF8fbmgAt

**Comment by mf-code** [comment]
[5988] - kTVS7YGfmhV5

**Comment by mf-code** [comment]
[5988] - 3TwmWFhgZngR

**Comment by mf-code** [comment]
[5988] - ajt2WqI8KAWO

**Comment by mf-code** [comment]
[5988] - NjSu28DWWgEV

**Comment by mf-code** [comment]
[5988] - n3hT0Giy5mDv

**Comment by mf-code** [comment]
[5988] - rwULvf1nGUTF

**Comment by mf-code** [comment]
[5988] - ZdF9UvDl7FyW

**Comment by mf-code** [comment]
[5988] - gRFSOR6ctEeh

**Comment by mf-code** [comment]
[5988] - openjdk8 - Allure report on Netlify: https://5f4f52dc119f0781cad2a922--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5988] - openjdk10 - Allure report on Netlify: https://5f4f5476e3b6fa773e0f8d0b--musing-swartz-6fc060.netlify.app

**Comment by gbuh** [comment]
[6000] - openjdk8 - Allure report on Netlify: https://5f4f93753c5e2907c3f47416--musing-swartz-6fc060.netlify.app
[6000] - openjdk10 - Allure report on Netlify: https://5f4f94616823e408ef8bfd0b--musing-swartz-6fc060.netlify.app

**Pull request merged**
