### PR TITLE
1532 html example check list

### PR DESCRIPTION
**Pull request by ArKhmeln**

### CODE REVIEW

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/example/complex/CheckListExampleTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/42_/jdi-light/pullRequest?prid=4734062&bid=15805020)

**Comment by mf-code** [comment]
[4392] - https://transfer.sh/3I46p/jdi-light-examples.tar.gz

**Comment by mf-code** [comment]
[4392] - https://transfer.sh/iewEU/jdi-performance.tar.gz

**Comment by mf-code** [comment]
[4392] - https://transfer.sh/DyVEt/jdi-light-html-tests.tar.gz

**Comment by mf-code** [comment]
[4392] - Allure report on Netlify: https://5e04c089de051021c64bc4d6--musing-swartz-6fc060.netlify.com

**Pull request merged**
