### PR TITLE
[DO NOT MERGE] 2038 Demonstration of Possibility to run tests on multiple JDKs

### PR DESCRIPTION
**Pull request by clockworkbanana**
This PR contains .travis.yml and reports.sh files that make Travis execute tests against multiple JDKs and publish separate allure report for each version of JDK.

Below is an example of results retreived by [Travis build 5565](https://travis-ci.com/github/jdi-testing/jdi-light/builds/169932280) for openjdk versions from 8 till 13 inclusively.

Links to reports are published as comments from user mf-code:
 
- openjdk8: https://5eda941e4fca8eb116705375--musing-swartz-6fc060.netlify.app/
- openjdk9: https://5eda951b3a487cd0981d89d2--musing-swartz-6fc060.netlify.app/
- openjdk10: https://5eda96174fca8eb0b270588a--musing-swartz-6fc060.netlify.app/
- openjdk11: https://5eda96def5a8b0de7fce7ec8--musing-swartz-6fc060.netlify.app/
- openjdk12: https://5eda9815163295fce1b08a48--musing-swartz-6fc060.netlify.app/
- openjdk13: https://5eda99089834a35de5003853--musing-swartz-6fc060.netlify.app/

### CODE REVIEW

**Comment by mf-code** [comment]
[5542] - F3dqbyjp

**Comment by mf-code** [comment]
[5542] - h3RC5B1Z

**Comment by mf-code** [comment]
[5542] - nbzjCzp0

**Comment by mf-code** [comment]
[5542] - GXdXYzXn

**Comment by mf-code** [comment]
[5542] - YHjd2E4E

**Comment by mf-code** [comment]
[5542] - JXG3o68R

**Comment by mf-code** [comment]
[5542] - openjdk10 - Allure report on Netlify: https://5ed9090777ee976bfd465a62--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5555] - 6lqhpMgW

**Comment by mf-code** [comment]
[5555] - FXHWlEhZ

**Comment by mf-code** [comment]
[5555] - kCR7udmL

**Comment by mf-code** [comment]
[5555] - OmK2tpmG

**Comment by mf-code** [comment]
[5555] - 1dTZVHDW

**Comment by mf-code** [comment]
[5555] - OqFLZ9Yx

**Comment by mf-code** [comment]
[5555] - zIYiGgNF

**Comment by mf-code** [comment]
[5555] - hF0QXOws

**Comment by mf-code** [comment]
[5555] - WGLNpXfk

**Comment by mf-code** [comment]
[5555] - CL1VHnhz

**Comment by mf-code** [comment]
[5555] - daRNMbRN

**Comment by mf-code** [comment]
[5555] - 50OizVP4

**Comment by mf-code** [comment]
[5555] - 8bLGES9n

**Comment by mf-code** [comment]
[5555] - Lr4iiQFZ

**Comment by mf-code** [comment]
[5555] - GBXss4kl

**Comment by mf-code** [comment]
[5555] - 5qYat3sf

**Comment by mf-code** [comment]
[5555] - NrKRAu8V

**Comment by mf-code** [comment]
[5555] - aAq3b67G

**Comment by mf-code** [comment]
[5555] - qs8E4xBH

**Comment by mf-code** [comment]
[5555] - N04Ut8oa

**Comment by mf-code** [comment]
[5555] - 29rRfPdt

**Comment by mf-code** [comment]
[5555] - 5MUxFEFV

**Comment by mf-code** [comment]
[5555] - 63RuKfbl

**Comment by mf-code** [comment]
[5555] - 2eUEMqKb

**Comment by mf-code** [comment]
[5555] - eUqC7Yf1

**Comment by mf-code** [comment]
[5555] - V0WJ87ms

**Comment by mf-code** [comment]
[5555] - JTwzpG2O

**Comment by mf-code** [comment]
[5555] - y340SlTu

**Comment by mf-code** [comment]
[5555] - XcP8clRH

**Comment by mf-code** [comment]
[5555] - 23KZ6NFH

**Comment by mf-code** [comment]
[5555] - openjdk8 - Allure report on Netlify: https://5ed97b537bf07143a447c6e5--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5555] - openjdk9 - Allure report on Netlify: https://5ed97c37f6fc278be0194ac5--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5555] - openjdk10 - Allure report on Netlify: https://5ed97d6ca6897370c682d6e3--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5555] - openjdk11 - Allure report on Netlify: https://5ed97e4c70101618b7c4104b--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5555] - openjdk12 - Allure report on Netlify: https://5ed97f3208c2ccbd002319fc--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5555] - openjdk13 - Allure report on Netlify: https://5ed98079a1b5840203fbcc13--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5565] - q2yUOVq8

**Comment by mf-code** [comment]
[5565] - mj9l5JWk

**Comment by mf-code** [comment]
[5565] - aeU0bM23

**Comment by mf-code** [comment]
[5565] - a5eLb03n

**Comment by mf-code** [comment]
[5565] - g9KUNtnI

**Comment by mf-code** [comment]
[5565] - M9aOLapM

**Comment by mf-code** [comment]
[5565] - Iby5tNyw

**Comment by mf-code** [comment]
[5565] - HAFEyooN

**Comment by mf-code** [comment]
[5565] - enVvThxQ

**Comment by mf-code** [comment]
[5565] - Fk2K6BRO

**Comment by mf-code** [comment]
[5565] - Ew7h3eaf

**Comment by mf-code** [comment]
[5565] - XFy0I21x

**Comment by mf-code** [comment]
[5565] - uARq431o

**Comment by mf-code** [comment]
[5565] - rFQs8TYX

**Comment by mf-code** [comment]
[5565] - GQsr5Shu

**Comment by mf-code** [comment]
[5565] - Hj5KTIVk

**Comment by mf-code** [comment]
[5565] - pnSkkaRl

**Comment by mf-code** [comment]
[5565] - UadE1mir

**Comment by mf-code** [comment]
[5565] - sniyuwRj

**Comment by mf-code** [comment]
[5565] - 4QXhjoTL

**Comment by mf-code** [comment]
[5565] - XI6nYKfH

**Comment by mf-code** [comment]
[5565] - in9m5CeJ

**Comment by mf-code** [comment]
[5565] - Oba317nt

**Comment by mf-code** [comment]
[5565] - HFxbfhO8

**Comment by mf-code** [comment]
[5565] - vq9sgLRl

**Comment by mf-code** [comment]
[5565] - Wd0tqUFL

**Comment by mf-code** [comment]
[5565] - 3QywgZY4

**Comment by mf-code** [comment]
[5565] - H35nTnMY

**Comment by mf-code** [comment]
[5565] - k17Ha2xe

**Comment by mf-code** [comment]
[5565] - OLmK2ELK

**Comment by mf-code** [comment]
[5565] - RUDqT6d4

**Comment by mf-code** [comment]
[5565] - MYKuZVXe

**Comment by mf-code** [comment]
[5565] - SaudlWEl

**Comment by mf-code** [comment]
[5565] - YRDSulKQ

**Comment by mf-code** [comment]
[5565] - XvdfxdS3

**Comment by mf-code** [comment]
[5565] - VmYgCnEM

**Comment by mf-code** [comment]
[5565] - PQcLDlHC

**Comment by mf-code** [comment]
[5565] - TMy4nWNv

**Comment by mf-code** [comment]
[5565] - ZJC6R1wQ

**Comment by mf-code** [comment]
[5565] - G4HNboQF

**Comment by mf-code** [comment]
[5565] - 4sLz2LDE

**Comment by mf-code** [comment]
[5565] - GgWsbdu6

**Comment by mf-code** [comment]
[5565] - openjdk8 - Allure report on Netlify: https://5eda941e4fca8eb116705375--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5565] - openjdk9 - Allure report on Netlify: https://5eda951b3a487cd0981d89d2--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5565] - openjdk10 - Allure report on Netlify: https://5eda96174fca8eb0b270588a--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5565] - openjdk11 - Allure report on Netlify: https://5eda96def5a8b0de7fce7ec8--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5565] - openjdk12 - Allure report on Netlify: https://5eda9815163295fce1b08a48--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5565] - openjdk13 - Allure report on Netlify: https://5eda99089834a35de5003853--musing-swartz-6fc060.netlify.app

**Comment by clockworkbanana** [comment]
**Please don't merge this PR until https://github.com/jdi-testing/jdi-light/issues/2071 is completed**

**Comment by clockworkbanana** [comment]
All the changes of this branch were implemented in **cronjob-debug** and were successfully merged into **master**.

**Pull request closed without merging**
