### PR TITLE
#2499 fix android tests

### PR DESCRIPTION
**Pull request by AleksandraMalygina**

### CODE REVIEW

**Comment by mf-code** [comment]
[6415] - olwcEpzotMCA

**Comment by mf-code** [comment]
[6415] - o2UEUZmqVyjq

**Comment by mf-code** [comment]
[6415] - AdbHQqINRZIi

**Comment by mf-code** [comment]
[6415] - oFw0v5dwY3Ct

**Comment by mf-code** [comment]
[6415] - yeUPiBm1JGA5

**Comment by mf-code** [comment]
[6415] - 3AjCidY294Na

**Comment by mf-code** [comment]
[6415] - s9p4yEUgxCus

**Comment by mf-code** [comment]
[6415] - wzp5C2mxnz1z

**Comment by mf-code** [comment]
[6415] - 7biPcVMF1b6n

**Comment by mf-code** [comment]
[6415] - p46LWLhBFjth

**Comment by mf-code** [comment]
[6415] - L8W3rILhcEsk

**Comment by mf-code** [comment]
[6415] - VEft6D3xvEh4

**Comment by mf-code** [comment]
[6415] - WlTqtqttIsqi

**Comment by mf-code** [comment]
[6415] - aeRRicAFpzJM

**Comment by mf-code** [comment]
[6415] - GUO8GsavwWdw

**Comment by mf-code** [comment]
[6415] - fqRneqzXbyHv

**Comment by mf-code** [comment]
[6415] - FgV5rMWi51kL

**Comment by mf-code** [comment]
[6416] - iy4WLIRcjMWb

**Comment by mf-code** [comment]
[6415] - TW5fLrdarrme

**Comment by mf-code** [comment]
[6416] - 8WRy3hnUa3kt

**Comment by mf-code** [comment]
[6416] - 7eve81otNYcL

**Comment by mf-code** [comment]
[6416] - 0j1z5ihWFuqB

**Comment by mf-code** [comment]
[6415] - openjdk8 - Allure report on Netlify: https://5fb2b5ce9ef0010cc15ab2fa--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6415] - openjdk10 - Allure report on Netlify: https://5fb2b6d542f02c09fcdc768a--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6416] - bkJL3dCpINk5

**Comment by mf-code** [comment]
[6416] - rvI6anobTRnk

**Comment by mf-code** [comment]
[6416] - a586w3hyqV5q

**Comment by mf-code** [comment]
[6416] - JRetv7SfDEWB

**Comment by mf-code** [comment]
[6416] - DDoUPkVaK6z2

**Comment by mf-code** [comment]
[6416] - EeXVguddJBHt

**Comment by mf-code** [comment]
[6416] - 7rq3XEEQzsfd

**Comment by mf-code** [comment]
[6416] - 6LXo1lNEoB40

**Comment by mf-code** [comment]
[6416] - t8hw6S6wumem

**Comment by mf-code** [comment]
[6416] - StEDaT0D2v4D

**Comment by mf-code** [comment]
[6416] - lZAjBDtFItb4

**Comment by mf-code** [comment]
[6416] - ruMj0uuRkNPN

**Comment by mf-code** [comment]
[6416] - B0P5aSqMLoe5

**Comment by mf-code** [comment]
[6416] - TEEJT1mSY0nj

**Comment by mf-code** [comment]
[6416] - openjdk8 - Allure report on Netlify: https://5fb2c44628258c1ea20630a6--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6416] - openjdk10 - Allure report on Netlify: https://5fb2c5211506b722179a51a4--musing-swartz-6fc060.netlify.app

**Review by alexarm — APPROVED** [review]

**Pull request merged**
