### PR TITLE
Travis - Fix one page GitHub comments read

### PR DESCRIPTION
**Pull request by AkioFaris**

### CODE REVIEW

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5531053&bid=18128383)

**Comment by mf-code** [comment]
[5303] - ITaFRr6I

**Comment by mf-code** [comment]
[5303] - LiNgayn6

**Comment by mf-code** [comment]
[5303] - Allure report on Netlify: https://5ebe62d243a042aa6846c29e--musing-swartz-6fc060.netlify.app

**Pull request merged**
