### PR TITLE
2047 Properties changes to master

### PR DESCRIPTION
**Pull request by AkioFaris**
Properties new functionality

### CODE REVIEW

**Comment by mf-code** [comment]
[5544] - vP2fKfyF

**Comment by mf-code** [comment]
[5544] - OpDBjKZ7

**Comment by mf-code** [comment]
[5545] - GvK8eCra

**Comment by mf-code** [comment]
[5545] - dmGLLxKu

**Comment by mf-code** [comment]
[5545] - BV9YHYze

**Comment by mf-code** [comment]
[5546] - q9P6u1

**Comment by mf-code** [comment]
[5546] - p1Brz8XX

**Comment by mf-code** [comment]
[5544] - zXLfMW

**Comment by mf-code** [comment]
[5546] - 1AIIGZ8q

**Comment by mf-code** [comment]
[5545] - TD86JImT

**Comment by mf-code** [comment]
[5546] - 1etylOlb

**Comment by mf-code** [comment]
[5552] - kU8tKljo

**Comment by mf-code** [comment]
[5552] - Dru01TJ4

**Comment by mf-code** [comment]
[5552] - cLqUpI5H

**Comment by mf-code** [comment]
[5566] - fmNABaaI

**Comment by mf-code** [comment]
[5566] - uBNENz7E

**Comment by mf-code** [comment]
[5566] - uyGxDzNV

**Comment by mf-code** [comment]
[5567] - JnF6U5tV

**Comment by mf-code** [comment]
[5567] - gxMuFYLm

**Comment by mf-code** [comment]
[5567] - wC0Nyy4u

**Comment by mf-code** [comment]
[5567] - nNK7tYXB

**Comment by mf-code** [comment]
[5567] - Allure report on Netlify: https://5edabdae563b4d0285bbf22f--musing-swartz-6fc060.netlify.app

**Comment by AkioFaris** [comment]
TODO: 
- resolve conflicts with master
- remove the separate "issue" package
- instead of using Property enum use additional-jdi-light-configuration-metadata.json

**Comment by mf-code** [comment]
[5621] - zBrvltL1

**Comment by mf-code** [comment]
[5621] - 614BAn2n

**Comment by mf-code** [comment]
[5621] - VO30WibO

**Comment by mf-code** [comment]
[5621] - IroyCkNd

**Comment by mf-code** [comment]
[5621] - z2Hn7vRz

**Comment by mf-code** [comment]
[5621] - m9lF5mna

**Comment by mf-code** [comment]
[5621] - wxYdAkcB

**Comment by mf-code** [comment]
[5621] - W9S7j4KA

**Comment by mf-code** [comment]
[5621] - CuhOQMAR

**Comment by mf-code** [comment]
[5621] - OA0S1H2v

**Comment by mf-code** [comment]
[5628] - jnVgZfTo

**Comment by mf-code** [comment]
[5628] - Xqm1N9Va

**Comment by mf-code** [comment]
[5628] - Xt99eYKW

**Comment by mf-code** [comment]
[5628] - hmkM09Kr

**Comment by mf-code** [comment]
[5628] - h6GIoUVY

**Comment by mf-code** [comment]
[5628] - u4BRXIFH

**Comment by mf-code** [comment]
[5628] - 000YhfLA

**Comment by mf-code** [comment]
[5628] - 9Yj01E4v

**Comment by mf-code** [comment]
[5628] - iZ5ZYY0a

**Comment by mf-code** [comment]
[5628] - RvxW9lRz

**Comment by mf-code** [comment]
[5629] - XKo5e06M

**Comment by mf-code** [comment]
[5629] - zozBsSYT

**Comment by mf-code** [comment]
[5629] - knzhiF9U

**Comment by mf-code** [comment]
[5629] - IWevWNXr

**Comment by mf-code** [comment]
[5629] - rbe7W8ks

**Comment by mf-code** [comment]
[5629] - ePUSMvVK

**Comment by mf-code** [comment]
[5629] - 7eFCdloT

**Comment by mf-code** [comment]
[5629] - SAJSKsSF

**Comment by mf-code** [comment]
[5629] - StmOM25f

**Comment by mf-code** [comment]
[5629] - JV6RvMDv

**Comment by mf-code** [comment]
[5630] - cFHWuf8h

**Comment by mf-code** [comment]
[5630] - 5y91DOhU

**Comment by mf-code** [comment]
[5630] - J15g7OS6

**Comment by mf-code** [comment]
[5630] - CyvqfaNY

**Comment by mf-code** [comment]
[5630] - GeQstcmw

**Comment by mf-code** [comment]
[5630] - C1X9Ke9G

**Comment by mf-code** [comment]
[5630] - vFKWNFE7

**Comment by mf-code** [comment]
[5630] - zACIPGKY

**Comment by mf-code** [comment]
[5630] - detOL38g

**Comment by mf-code** [comment]
[5630] - gOsavWDf

**Comment by mf-code** [comment]
[5631] - dVCONHXP

**Comment by mf-code** [comment]
[5631] - X5vpjhIP

**Comment by mf-code** [comment]
[5631] - vpcxmaQ0

**Comment by mf-code** [comment]
[5631] - maCw7dVG

**Comment by mf-code** [comment]
[5631] - x5A3PIKu

**Comment by mf-code** [comment]
[5631] - tFOPwghV

**Comment by mf-code** [comment]
[5631] - leUOG0Fy

**Comment by mf-code** [comment]
[5631] - R1KgJ1Ue

**Comment by mf-code** [comment]
[5631] - dZjpBWvw

**Comment by mf-code** [comment]
[5631] - 2OU5mo4P

**Comment by mf-code** [comment]
[5631] - 5f6NpjBL

**Comment by mf-code** [comment]
[5631] - df05q9xj

**Comment by mf-code** [comment]
[5633] - RzCkzXLM

**Comment by mf-code** [comment]
[5633] - fSvdUV8R

**Comment by mf-code** [comment]
[5633] - xi5jldd7

**Comment by mf-code** [comment]
[5633] - NIE9nj9H

**Comment by mf-code** [comment]
[5633] - 5hxoyY0N

**Comment by mf-code** [comment]
[5633] - lIDqMhF9

**Comment by mf-code** [comment]
[5633] - ZaOzq438

**Comment by mf-code** [comment]
[5633] - uErRI9EX

**Comment by mf-code** [comment]
[5633] - VNKtNmlM

**Comment by mf-code** [comment]
[5633] - yYJX8Zxl

**Comment by mf-code** [comment]
[5633] - 2GVovjFt

**Comment by mf-code** [comment]
[5633] - 9tLazjnp

**Comment by mf-code** [comment]
[5633] - openjdk8 - Allure report on Netlify: https://5ee8e960521af96cf10ada1c--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5633] - openjdk10 - Allure report on Netlify: https://5ee8eaaf521af995670ad723--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5644] - a4HGpY7i

**Comment by mf-code** [comment]
[5644] - pcMMjxpS

**Comment by mf-code** [comment]
[5644] - 0AxfaL8t

**Comment by mf-code** [comment]
[5644] - ivXKnO8b

**Comment by mf-code** [comment]
[5644] - lxqeNEtX

**Comment by mf-code** [comment]
[5644] - s98vq40E

**Comment by mf-code** [comment]
[5644] - vMvDVi04

**Comment by mf-code** [comment]
[5644] - qqk531og

**Comment by mf-code** [comment]
[5644] - vemA8dbv

**Comment by mf-code** [comment]
[5644] - rx3UKpHl

**Comment by mf-code** [comment]
[5644] - gNGQekle

**Comment by mf-code** [comment]
[5644] - tLewWJ6N

**Comment by mf-code** [comment]
[5644] - A6iOSBlk

**Comment by mf-code** [comment]
[5644] - w3fJzptF

**Comment by mf-code** [comment]
[5644] - openjdk8 - Allure report on Netlify: https://5eeb15a148b9dc2633a84a0d--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5644] - openjdk10 - Allure report on Netlify: https://5eeb16a6fab490e64533926c--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5655] - 8MsXqNFL

**Comment by mf-code** [comment]
[5655] - VIX0wAcF

**Comment by mf-code** [comment]
[5655] - YWnhJ3bw

**Comment by mf-code** [comment]
[5655] - t81bJ3Yy

**Comment by mf-code** [comment]
[5655] - ipN3x8Y3

**Comment by mf-code** [comment]
[5655] - dXHcoFMU

**Comment by mf-code** [comment]
[5655] - JBmreHWt

**Comment by mf-code** [comment]
[5655] - 7RL0BUTn

**Comment by mf-code** [comment]
[5655] - iQ8QYWM8

**Comment by mf-code** [comment]
[5655] - ea0mg9FO

**Comment by mf-code** [comment]
[5655] - aiu1CBbv

**Comment by mf-code** [comment]
[5655] - jj2jg5Tk

**Comment by mf-code** [comment]
[5655] - It9jgfOs

**Comment by mf-code** [comment]
[5655] - fRi7ulLq

**Comment by mf-code** [comment]
[5655] - openjdk8 - Allure report on Netlify: https://5eecda4aeb967d8271a3fc48--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5655] - openjdk10 - Allure report on Netlify: https://5eecdb96233b8f8590df1b53--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5666] - DSkTJyyU

**Comment by mf-code** [comment]
[5666] - iWsOd6kR

**Comment by mf-code** [comment]
[5666] - EdzlAGNN

**Comment by mf-code** [comment]
[5666] - HWqCIUKr

**Comment by mf-code** [comment]
[5666] - apxTXWZO

**Comment by mf-code** [comment]
[5666] - Om63bLSN

**Comment by mf-code** [comment]
[5666] - Wkr1aFlc

**Comment by mf-code** [comment]
[5666] - X0plG3SW

**Comment by mf-code** [comment]
[5666] - wJ9SZDbK

**Comment by mf-code** [comment]
[5666] - YIa8AnqG

**Comment by mf-code** [comment]
[5666] - 95zUuYEF

**Comment by mf-code** [comment]
[5666] - uw2faEDp

**Comment by mf-code** [comment]
[5666] - txbjdpsY

**Comment by mf-code** [comment]
[5666] - D0EQ8JaS

**Comment by mf-code** [comment]
[5666] - openjdk8 - Allure report on Netlify: https://5ef249841e53b7028edc21fa--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5666] - openjdk10 - Allure report on Netlify: https://5ef24a8bd259d501debecaf2--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5675] - V0Y9VpMR

**Comment by mf-code** [comment]
[5675] - mZUuyeud

**Comment by mf-code** [comment]
[5675] - Bnu6rlFW

**Comment by mf-code** [comment]
[5675] - 0ySCOHm5

**Comment by mf-code** [comment]
[5675] - omN8GrNc

**Comment by mf-code** [comment]
[5675] - wnSnIkNc

**Comment by mf-code** [comment]
[5675] - GXW0YHfe

**Comment by mf-code** [comment]
[5675] - eWM4A0Fi

**Comment by mf-code** [comment]
[5675] - VxXQ7iUZ

**Comment by mf-code** [comment]
[5675] - JTAH1UQs

**Comment by mf-code** [comment]
[5675] - fIjnCkLq

**Comment by mf-code** [comment]
[5675] - Z5y31h18

**Comment by mf-code** [comment]
[5675] - XSDcMYQ9

**Comment by mf-code** [comment]
[5675] - rko8PEwf

**Comment by mf-code** [comment]
[5675] - openjdk8 - Allure report on Netlify: https://5ef5b84c1834aedd13d0f2c5--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5675] - openjdk10 - Allure report on Netlify: https://5ef5b93719366a5e81b3832d--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5686] - ERcwGeT6

**Comment by mf-code** [comment]
[5686] - 6LLLQrf2

**Comment by mf-code** [comment]
[5686] - wGmk1WHO

**Comment by mf-code** [comment]
[5686] - bCH5UGlU

**Comment by mf-code** [comment]
[5686] - k8o3r8Tp

**Comment by mf-code** [comment]
[5686] - XXFCPmoS

**Comment by mf-code** [comment]
[5686] - yNe3h9uE

**Comment by mf-code** [comment]
[5686] - xy7opJhE

**Comment by mf-code** [comment]
[5686] - AzJM9xwE

**Comment by mf-code** [comment]
[5686] - mq6MKNh4

**Comment by mf-code** [comment]
[5686] - ZVnZBDlP

**Comment by mf-code** [comment]
[5686] - bQAeB4wY

**Comment by mf-code** [comment]
[5686] - EEBt5WR0

**Comment by mf-code** [comment]
[5686] - Mjw0xcJI

**Comment by mf-code** [comment]
[5696] - THq4YVI0

**Comment by mf-code** [comment]
[5696] - QfdDEx97

**Comment by mf-code** [comment]
[5696] - ii8nIqXP

**Comment by mf-code** [comment]
[5696] - 9tGRndtc

**Comment by mf-code** [comment]
[5696] - VN6wrPxL

**Comment by mf-code** [comment]
[5696] - kGFSLNzY

**Comment by mf-code** [comment]
[5696] - l31M3aUg

**Comment by mf-code** [comment]
[5696] - jMgm0Gpg

**Comment by mf-code** [comment]
[5696] - 3FwgmDpF

**Comment by mf-code** [comment]
[5696] - NHcImKRi

**Comment by mf-code** [comment]
[5696] - q8TrSWXN

**Comment by mf-code** [comment]
[5696] - EzM464ev

**Comment by mf-code** [comment]
[5696] - zuJV1Mlm

**Comment by mf-code** [comment]
[5696] - mFCB6Z8i

**Comment by mf-code** [comment]
[5696] - openjdk8 - Allure report on Netlify: https://5efb062e635cb6971e0d1858--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5696] - openjdk10 - Allure report on Netlify: https://5efb074d5cedec8c1e44b0f9--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5858] - CVxAxBAavjF8

**Comment by mf-code** [comment]
[5858] - Qwyr8EWZg6Vo

**Comment by mf-code** [comment]
[5858] - LUFbOdGsPT9g

**Comment by mf-code** [comment]
[5858] - T4xLFzTjS9lG

**Comment by mf-code** [comment]
[5858] - 8SDZEBOrM79G

**Comment by mf-code** [comment]
[5858] - Kce9TfLCdjvG

**Comment by mf-code** [comment]
[5858] - 43wr7jlCrIjk

**Comment by mf-code** [comment]
[5858] - TTdVRMIvnTkz

**Comment by mf-code** [comment]
[5858] - OrUlM77P32hc

**Comment by mf-code** [comment]
[5858] - fNcM8bFsQocb

**Comment by mf-code** [comment]
[5858] - PfKj6UkEbhGZ

**Comment by mf-code** [comment]
[5858] - sxWBOPjMEGKW

**Comment by mf-code** [comment]
[5858] - CcK7ai5FZms9

**Comment by mf-code** [comment]
[5858] - YQAqGButVwOA

**Comment by mf-code** [comment]
[5858] - HmkuWNTe07bc

**Comment by mf-code** [comment]
[5858] - ZCgKQ4o6A6nH

**Comment by mf-code** [comment]
[5858] - openjdk8 - Allure report on Netlify: https://5f22f97efd565bcbf926f780--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5858] - openjdk10 - Allure report on Netlify: https://5f22faabd5178a28112dd7e2--musing-swartz-6fc060.netlify.app

**Comment by vklonin** [comment]
outdated

**Pull request closed without merging**
