### PR TITLE
Changed method names in DownloadDriverManager and DriverInfo classes.

### PR DESCRIPTION
**Pull request by gbuh**
Changed the names of the methods in the DownloadDriverManager and DriverInfo classes in accordance with the external source.

### CODE REVIEW

**Comment by mf-code** [comment]
[5905] - S3HR54nuCVdS

**Comment by mf-code** [comment]
[5905] - Pk45BWmMXNn9

**Comment by mf-code** [comment]
[5905] - wjSgZCuYDXEn

**Comment by mf-code** [comment]
[5905] - NkyEZzqAEhqg

**Comment by mf-code** [comment]
[5905] - X6rJ5l9Ms1tT

**Comment by mf-code** [comment]
[5905] - nREaucUA95pw

**Review by Vtablos — COMMENTED** [review]
submitted

**Pull request merged**
