### PR TITLE
1564 fix html, examples tests

### PR DESCRIPTION
**Pull request by alla-blinkova**

### CODE REVIEW

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 55
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5551142&bid=18201237)

**Comment by mf-code** [comment]
[5352] - 5SuBxhof

**Comment by mf-code** [comment]
[5352] - LlI9q7mf

**Comment by mf-code** [comment]
[5352] - HjQ8uYNU

**Comment by mf-code** [comment]
[5352] - wC6CqhL9

**Comment by mf-code** [comment]
[5352] - 4TJ8JBe0

**Comment by mf-code** [comment]
[5352] - eBV7qNOJ

**Comment by mf-code** [comment]
[5352] - Allure report on Netlify: https://5ec3fc5778ebf4cec3da75f0--musing-swartz-6fc060.netlify.app

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 55
           

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/test/data/FurnitureTableData.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5551142&bid=18201237)

**Comment by mf-code** [comment]
[5357] - 5hoyI9nW

**Comment by mf-code** [comment]
[5357] - fjMVjMrn

**Comment by mf-code** [comment]
[5357] - aI4KpB9m

**Comment by mf-code** [comment]
[5357] - o6JFz89H

**Comment by mf-code** [comment]
[5357] - qDdWCwJl

**Comment by mf-code** [comment]
[5357] - nyg9vE4i

**Comment by mf-code** [comment]
[5357] - Allure report on Netlify: https://5ec501be7b0b539e922816ab--musing-swartz-6fc060.netlify.app

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 71
           

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/test/data/FurnitureTableData.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5551142&bid=18201237)

**Comment by mf-code** [comment]
[5359] - IYAwFr3t

**Comment by mf-code** [comment]
[5359] - p2ESuhG5

**Comment by mf-code** [comment]
[5359] - DKzjG25i

**Comment by mf-code** [comment]
[5359] - Y5cKsrOW

**Comment by mf-code** [comment]
[5359] - YMgttCgP

**Comment by mf-code** [comment]
[5359] - 2WqjkUIb

**Comment by mf-code** [comment]
[5359] - Allure report on Netlify: https://5ec53d2eaf451e0ac6038239--musing-swartz-6fc060.netlify.app

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 71
           

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/test/data/FurnitureTableData.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5551142&bid=18201237)

**Comment by mf-code** [comment]
[5365] - u0KGesYS

**Comment by mf-code** [comment]
[5365] - NLPZFwqi

**Comment by mf-code** [comment]
[5365] - OXn2oDUV

**Comment by mf-code** [comment]
[5365] - cHey9qfP

**Comment by mf-code** [comment]
[5365] - 0MuyDyzn

**Comment by mf-code** [comment]
[5365] - E7mmil1w

**Comment by mf-code** [comment]
[5365] - Allure report on Netlify: https://5ec63d96fd1cc6198cc618d8--musing-swartz-6fc060.netlify.app

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 86
           

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/test/data/FurnitureTableData.java  1
- jdi-bdd/src/main/java/com/epam/jdi/bdd/elements/CustomMenu.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5551142&bid=18201237)

**Comment by mf-code** [comment]
[5371] - lxrIwIsu

**Comment by mf-code** [comment]
[5371] - xEtoljlB

**Comment by mf-code** [comment]
[5371] - hacOWVor

**Comment by mf-code** [comment]
[5371] - 42jiOhAm

**Comment by mf-code** [comment]
[5371] - 3n7UaEYM

**Comment by mf-code** [comment]
[5371] - rAXf86WA

**Comment by mf-code** [comment]
[5371] - Allure report on Netlify: https://5ec6932da9c378ae66122e08--musing-swartz-6fc060.netlify.app

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 78
           

Complexity increasing per file
==============================
- jdi-bdd/src/main/java/com/epam/jdi/bdd/elements/CustomMenu.java  1
- jdi-light-html-tests/src/test/java/io/github/epam/test/data/FurnitureTableData.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5551142&bid=18201237)

**Comment by mf-code** [comment]
[5400] - BcgrQGf1

**Comment by mf-code** [comment]
[5400] - 44lFUMf0

**Comment by mf-code** [comment]
[5400] - KnNmJbE0

**Comment by mf-code** [comment]
[5400] - OK4HU7bP

**Comment by mf-code** [comment]
[5400] - 6j4T3uU2

**Comment by mf-code** [comment]
[5400] - zKC0mPCj

**Comment by mf-code** [comment]
[5400] - Allure report on Netlify: https://5ecbad2cf5ea88e216d61404--musing-swartz-6fc060.netlify.app

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 78
           

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/test/data/FurnitureTableData.java  1
- jdi-bdd/src/main/java/com/epam/jdi/bdd/elements/CustomMenu.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5551142&bid=18201237)

**Comment by mf-code** [comment]
[5413] - 9JXiPJKk

**Comment by mf-code** [comment]
[5413] - weocTXYK

**Comment by mf-code** [comment]
[5413] - OxVEfNV4

**Comment by mf-code** [comment]
[5413] - 2hYaJpqP

**Comment by mf-code** [comment]
[5413] - TiCI1Yeh

**Comment by mf-code** [comment]
[5413] - 1EXK7Rri

**Comment by mf-code** [comment]
[5413] - Allure report on Netlify: https://5eccd8319424d35a657fceb9--musing-swartz-6fc060.netlify.app

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 78
           

Complexity increasing per file
==============================
- jdi-bdd/src/main/java/com/epam/jdi/bdd/elements/CustomMenu.java  1
- jdi-light-html-tests/src/test/java/io/github/epam/test/data/FurnitureTableData.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5551142&bid=18201237)

**Comment by mf-code** [comment]
[5421] - ZHiwTlbe

**Comment by mf-code** [comment]
[5421] - 0XA4FDjY

**Comment by mf-code** [comment]
[5421] - m1izSrmp

**Comment by mf-code** [comment]
[5421] - h1bBUBHx

**Comment by mf-code** [comment]
[5421] - TaaXCmxV

**Comment by mf-code** [comment]
[5421] - wY29a04I

**Comment by mf-code** [comment]
[5421] - Allure report on Netlify: https://5ece356cd562c606d93d7968--musing-swartz-6fc060.netlify.app

**Comment by alla-blinkova** [comment]
All failed tests were fixed except the following: 

1. rootTest in examples module. Seems to be unstable, sometimes can not perform login
2. dataColumnNameTest and valueTest in html module
- dataColumnNameTest - next row is returned instead of expected, because getRowIndexByName() uses jsColumn locator which can not be specified for the table. So, for the furniture table the header is considered as the 1st extra row.
- valueTest - getValue() returns wrong values for empty cells - WebList[...] instead of empty string.

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 74
           

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/test/data/FurnitureTableData.java  1
- jdi-bdd/src/main/java/com/epam/jdi/bdd/elements/CustomMenu.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5551142&bid=18201237)

**Comment by mf-code** [comment]
[5441] - z5Fhu9VP

**Comment by mf-code** [comment]
[5441] - xL5KFMMx

**Comment by mf-code** [comment]
[5441] - 37HR9A8a

**Comment by mf-code** [comment]
[5441] - JeQRvsrP

**Comment by mf-code** [comment]
[5441] - GNzgQf8h

**Comment by mf-code** [comment]
[5441] - uBx2erLc

**Comment by mf-code** [comment]
[5441] - jGEvFRtP

**Comment by mf-code** [comment]
[5441] - Allure report on Netlify: https://5ecf89f2074acc696470090d--musing-swartz-6fc060.netlify.app

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 78
           

Complexity increasing per file
==============================
- jdi-bdd/src/main/java/com/epam/jdi/bdd/elements/CustomMenu.java  1
- jdi-light-html-tests/src/test/java/io/github/epam/test/data/FurnitureTableData.java  1
         

Complexity decreasing per file
==============================
+ test-examples/jdi-light-examples/src/test/java/io/github/epam/tests/google/WaitJListTests.java  -1
+ jdi-light-html-tests/src/test/java/io/github/epam/html/tests/elements/complex/list/WaitDataListTests.java  -1
+ jdi-light-html-tests/src/test/java/io/github/epam/html/tests/elements/complex/list/WaitJListTests.java  -1
+ test-examples/jdi-light-examples/src/test/java/io/github/epam/tests/google/WaitDataListTests.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5551142&bid=18201237)

**Comment by mf-code** [comment]
[5443] - T4v04lFH

**Comment by mf-code** [comment]
[5443] - 6KxJC5Sv

**Comment by mf-code** [comment]
[5443] - Zo3Ao0q3

**Comment by mf-code** [comment]
[5443] - 0t5QgCx4

**Comment by mf-code** [comment]
[5443] - KTu7zqe0

**Comment by mf-code** [comment]
[5443] - QFAUXjoY

**Comment by mf-code** [comment]
[5443] - J8RsVyxP

**Comment by mf-code** [comment]
[5443] - Allure report on Netlify: https://5ecf99a43aba606fb41a0602--musing-swartz-6fc060.netlify.app

**Pull request merged**
