### PR TITLE
1571 Allure HTML logging implementation

### PR DESCRIPTION
**Pull request by splekhanov**
#1571

### CODE REVIEW

**Comment by mf-code** [comment]
[4087] - https://transfer.sh/blsvE/jdi-performance.tar.gz

**Comment by mf-code** [comment]
[4087] - https://transfer.sh/KprZL/jdi-light-html-tests.tar.gz

**Comment by mf-code** [comment]
[4087] - https://transfer.sh/C56Vw/jdi-light-examples.tar.gz

**Comment by mf-code** [comment]
[4088] - https://transfer.sh/1AhoF/jdi-light-html-tests.tar.gz

**Comment by mf-code** [comment]
[4087] - Allure report on Netlify: https://5df785c88bf43c017a67b848--musing-swartz-6fc060.netlify.com

**Comment by mf-code** [comment]
[4088] - https://transfer.sh/m5vvv/jdi-light-examples.tar.gz

**Comment by mf-code** [comment]
[4088] - https://transfer.sh/rMQZ6/jdi-performance.tar.gz

**Comment by mf-code** [comment]
[4088] - Allure report on Netlify: https://5df787733a99390180d33791--musing-swartz-6fc060.netlify.com

**Comment by OBraunEPAM** [comment]
Review is in progress.

**Pull request merged**
