### PR TITLE
1962 progress bar tests

### PR DESCRIPTION
**Pull request by Ammar-Barry**

### CODE REVIEW

**Comment by mf-code** [comment]
[6174] - wQTcdjnrhLmX

**Comment by mf-code** [comment]
[6174] - wPLdetqrRgdh

**Comment by mf-code** [comment]
[6174] - XODmWrqbUXKj

**Comment by mf-code** [comment]
[6174] - 7G3TLgUN2wKb

**Comment by mf-code** [comment]
[6174] - w5uR74jbitGK

**Comment by mf-code** [comment]
[6174] - zxEzT8kn1B5j

**Comment by mf-code** [comment]
[6174] - p7GlHXjptHG3

**Comment by mf-code** [comment]
[6174] - IO4bQKXqtU5u

**Comment by mf-code** [comment]
[6174] - VGWeXmCV740K

**Comment by mf-code** [comment]
[6174] - b2Qo8IrXAF75

**Comment by mf-code** [comment]
[6174] - OVdQrU616zbd

**Comment by mf-code** [comment]
[6174] - jNSnLThDdUJJ

**Comment by mf-code** [comment]
[6174] - n8YupwjUDJo7

**Comment by mf-code** [comment]
[6174] - dLhNFjMHiZSt

**Comment by mf-code** [comment]
[6174] - A5KxlMG882mN

**Comment by mf-code** [comment]
[6174] - 5aeDyNUF6cRe

**Comment by mf-code** [comment]
[6174] - mI8a5ISOR0En

**Comment by mf-code** [comment]
[6174] - wc0hxboXDTkb

**Comment by mf-code** [comment]
[6176] - A1ITtDxzk8CU

**Comment by mf-code** [comment]
[6176] - qVTZQzGfxXC5

**Comment by mf-code** [comment]
[6176] - IRBaeSv45cnX

**Comment by mf-code** [comment]
[6176] - sydVq2vhrkbV

**Comment by mf-code** [comment]
[6176] - nXoaZiaF9LrQ

**Comment by mf-code** [comment]
[6176] - 7g2sbPgSQg6j

**Comment by mf-code** [comment]
[6176] - E38sFmhXAj3P

**Comment by mf-code** [comment]
[6176] - QaoCSZKsM3lE

**Review by AlexSofft — APPROVED** [review]

**Comment by mf-code** [comment]
[6176] - D9mjmOVrIPs0

**Comment by mf-code** [comment]
[6176] - zXAmUWGQvU8M

**Comment by mf-code** [comment]
[6176] - YGKyevJilhgZ

**Comment by mf-code** [comment]
[6176] - 6XqnVxy0IRls

**Comment by mf-code** [comment]
[6176] - lzkTBTLJFru5

**Comment by mf-code** [comment]
[6176] - tdZ4Pwel2iyK

**Comment by mf-code** [comment]
[6176] - OVpZYn7C5pmy

**Comment by mf-code** [comment]
[6176] - YjRrBns24zZ0

**Comment by mf-code** [comment]
[6180] - oQ5LvGZ7n4bm

**Comment by mf-code** [comment]
[6180] - PTIZze2sqEWG

**Comment by mf-code** [comment]
[6180] - igK8gyk7BqKc

**Comment by mf-code** [comment]
[6180] - Dk8v2SG8R4j0

**Comment by mf-code** [comment]
[6180] - 5BxI6v2cs8tP

**Comment by mf-code** [comment]
[6180] - Oi40fhWZG1iS

**Comment by mf-code** [comment]
[6180] - xVwuMHpHBKBE

**Comment by mf-code** [comment]
[6180] - PQjwBd8N5V8W

**Comment by mf-code** [comment]
[6180] - CYdaqrwrR5u9

**Comment by mf-code** [comment]
[6180] - iLrF58GfFB2s

**Comment by mf-code** [comment]
[6180] - 9W3Jm7ISeQj2

**Comment by mf-code** [comment]
[6180] - 9NJ1nnwcayC3

**Comment by mf-code** [comment]
[6180] - v28A5PBOKcva

**Comment by mf-code** [comment]
[6180] - 9v6w3mXGCagM

**Comment by mf-code** [comment]
[6180] - RXnWEYfujYac

**Comment by mf-code** [comment]
[6180] - a52i5a9WXgrp

**Comment by mf-code** [comment]
[6180] - 07jKmMMFzVki

**Comment by mf-code** [comment]
[6180] - SQ4QqKvydQ7I

**Comment by mf-code** [comment]
[6186] - BfuB7lkxsQaK

**Comment by mf-code** [comment]
[6186] - k9plOzJjXfp0

**Comment by mf-code** [comment]
[6186] - YYhgqlLUxiJt

**Comment by mf-code** [comment]
[6186] - 5aKrw7nYMAlQ

**Comment by mf-code** [comment]
[6186] - 6eCN1M0XOjEX

**Comment by mf-code** [comment]
[6186] - 0efKFDSKRgnF

**Comment by mf-code** [comment]
[6186] - 7I8B9Nl7leTL

**Comment by mf-code** [comment]
[6186] - gluE6mveRsGN

**Comment by mf-code** [comment]
[6186] - xBM7BYuyesAH

**Comment by mf-code** [comment]
[6186] - m79gUyIV3oND

**Comment by mf-code** [comment]
[6186] - u6s7xZrw17ja

**Comment by mf-code** [comment]
[6186] - LPgByJ6fSFKB

**Comment by mf-code** [comment]
[6186] - J3swLhf0eL0o

**Comment by mf-code** [comment]
[6186] - zdXVaT9F2da0

**Comment by mf-code** [comment]
[6186] - sANmRvj0U58r

**Comment by mf-code** [comment]
[6186] - wJqcTFd3esn6

**Comment by mf-code** [comment]
[6186] - UcrNdb8ux8v4

**Comment by mf-code** [comment]
[6186] - 5KSzQEjN2Lm3

**Comment by mf-code** [comment]
[6186] - openjdk8 - Allure report on Netlify: https://5f6b1b2a86dd94dbbce5873c--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6186] - openjdk10 - Allure report on Netlify: https://5f6b1c5ed4e80fe3c368f328--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6186] - jwKt6cv5lRVK

**Comment by mf-code** [comment]
[6186] - t5APPxDU6AJR

**Comment by mf-code** [comment]
[6186] - Tw11brbyydz3

**Comment by mf-code** [comment]
[6186] - TMRJKiGXMXVK

**Comment by mf-code** [comment]
[6186] - g3v7q11S1viT

**Comment by mf-code** [comment]
[6186] - O5goQmo3b3Co

**Comment by mf-code** [comment]
[6186] - N6Kt9T1wAZsI

**Comment by mf-code** [comment]
[6186] - u8Xpkf5SaWIx

**Comment by mf-code** [comment]
[6186] - 7otkb0VLL4Y9

**Comment by mf-code** [comment]
[6186] - xpZwuOru4odK

**Comment by mf-code** [comment]
[6186] - QTWyTARyHeGc

**Comment by mf-code** [comment]
[6186] - sUm6alIccByR

**Comment by mf-code** [comment]
[6186] - XdWyAfBR2XXO

**Comment by mf-code** [comment]
[6186] - wI19sG76e0ey

**Comment by mf-code** [comment]
[6186] - RGyKhmyHs7o3

**Comment by mf-code** [comment]
[6186] - 0bCq5q3KdtBq

**Comment by mf-code** [comment]
[6186] - RUUQzXLAcAD1

**Comment by mf-code** [comment]
[6186] - zizIgVmGoitx

**Comment by mf-code** [comment]
[6186] - openjdk8 - Allure report on Netlify: https://5f6b9da39bf55f1b17298711--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6186] - openjdk10 - Allure report on Netlify: https://5f6b9f870c54141e77f2c0bb--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6189] - Nb5r7fEba6hA

**Comment by mf-code** [comment]
[6189] - thcz51VAPUu4

**Comment by mf-code** [comment]
[6189] - xg5yekr4n6BL

**Comment by mf-code** [comment]
[6189] - SlAYw49UuDcy

**Comment by mf-code** [comment]
[6189] - jPdHMNyZBZNG

**Comment by mf-code** [comment]
[6189] - gwDrP6xOvLdt

**Comment by mf-code** [comment]
[6189] - dZWaCCopdnD9

**Comment by mf-code** [comment]
[6189] - jeRVGBJj5MQs

**Comment by mf-code** [comment]
[6189] - AVzoAu4rBzWv

**Comment by mf-code** [comment]
[6189] - VGHjLzZgCask

**Comment by mf-code** [comment]
[6189] - ti0TtJgN2osR

**Comment by mf-code** [comment]
[6189] - GwWh17e3lLDi

**Comment by mf-code** [comment]
[6189] - UAZFSsK5VHBi

**Comment by mf-code** [comment]
[6189] - 9xZbG4spDZc3

**Comment by mf-code** [comment]
[6189] - zV07j5ipBm0s

**Comment by mf-code** [comment]
[6189] - JCrkymb61gjZ

**Comment by mf-code** [comment]
[6189] - VOMXGnt4gslM

**Comment by mf-code** [comment]
[6189] - I5oY69tXroAP

**Comment by mf-code** [comment]
[6189] - openjdk8 - Allure report on Netlify: https://5f6bd2b73f1f77011215b92e--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6189] - openjdk10 - Allure report on Netlify: https://5f6bd3ea563cad0126adec5e--musing-swartz-6fc060.netlify.app

**Pull request merged**
