### PR TITLE
New parameters covered with tests

### PR DESCRIPTION
**Pull request by RomE-HK**
Task https://github.com/jdi-testing/jdi-light/issues/1744

### CODE REVIEW

**Comment by RomE-HK** [comment]
On daily meeting we decided to add this tests to 'bootstrap' branch

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light/src/test/java/io/github/epam/properties/RequestsStrategyTests.java  2
- jdi-light/src/test/java/io/github/epam/properties/AllureStepsTests.java  2
- jdi-light/src/test/java/io/github/epam/properties/HtmlCodeStrategyTests.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5133531&bid=16868941)

**Comment by mf-code** [comment]
[4899] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4899] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4899] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4899] - Allure report on Netlify: https://5e6228949fd9853ccb425cfe--musing-swartz-6fc060.netlify.com

**Comment by RomanIovlev** [comment]
The important pull request, I will review later

**Comment by RomanIovlev** [comment]
Closed because code is obsolete but required changes will be done in #1878 and #1879

**Pull request closed without merging**
