### PR TITLE
#2400 Fix long time waiting for tearDown tests of native app

### PR DESCRIPTION
**Pull request by BraveLittleTapok**
Fix long time waiting for tearDown tests of native app

### CODE REVIEW

**Comment by mf-code** [comment]
[6248] - BQTFaXoAoXvj

**Comment by mf-code** [comment]
[6248] - SB20R9Qt1CKf

**Comment by mf-code** [comment]
[6248] - SG9hWn9bPO83

**Comment by mf-code** [comment]
[6248] - SnAhuBeSSeiW

**Comment by mf-code** [comment]
[6248] - 8L30yODg1bcG

**Comment by mf-code** [comment]
[6248] - HOAjnsiBiIBT

**Comment by mf-code** [comment]
[6248] - wbb2zzaYGEF6

**Comment by mf-code** [comment]
[6248] - mYJ68FYIN7Ts

**Comment by mf-code** [comment]
[6248] - OGC1yhjHXgM1

**Comment by mf-code** [comment]
[6248] - Yb38RRbumdpD

**Comment by mf-code** [comment]
[6248] - zL87hQZQlvUE

**Comment by mf-code** [comment]
[6248] - Lyz41ckkXSfW

**Comment by mf-code** [comment]
[6248] - 7t2K9dC1Wy6c

**Comment by mf-code** [comment]
[6248] - ztjEE0zUE0SK

**Comment by mf-code** [comment]
[6248] - epMxtYA1B8LA

**Comment by mf-code** [comment]
[6248] - v3Tv5AfoCy51

**Comment by mf-code** [comment]
[6248] - tMg9uhC8mYpq

**Comment by mf-code** [comment]
[6248] - xfHM68e9zUD6

**Comment by mf-code** [comment]
[6248] - openjdk8 - Allure report on Netlify: https://5f8044c649fb25838d8a695e--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6248] - openjdk10 - Allure report on Netlify: https://5f8045f9e7112275edfd6956--musing-swartz-6fc060.netlify.app

**Review by alexarm — APPROVED** [review]

**Pull request merged**
