### PR TITLE
1531 DataList html example 

### PR DESCRIPTION
**Pull request by ArKhmeln**
#1609

### CODE REVIEW

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/example/complex/DataListExampleTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/42_/jdi-light/pullRequest?prid=4729303&bid=15790594)

**Comment by mf-code** [comment]
[4351] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4351] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4351] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4351] - Allure report on Netlify: https://5e0212a8e0f80a8591286a74--musing-swartz-6fc060.netlify.com

**Pull request merged**
