### PR TITLE
Separate module for tests with mocks

### PR DESCRIPTION
**Pull request by AkioFaris**
Merge after #2048

### CODE REVIEW

**Comment by mf-code** [comment]
[5637] - eOGlaabu

**Comment by mf-code** [comment]
[5637] - BXdZpm0W

**Comment by mf-code** [comment]
[5637] - fvh070i8

**Comment by mf-code** [comment]
[5637] - KxFOZyI8

**Comment by mf-code** [comment]
[5637] - AAT22tKW

**Comment by mf-code** [comment]
[5637] - u1Ky9Mpx

**Comment by mf-code** [comment]
[5637] - ZYLETMnf

**Comment by mf-code** [comment]
[5637] - him0Kwmh

**Comment by mf-code** [comment]
[5637] - Y8jw41JK

**Comment by mf-code** [comment]
[5637] - n4y3NTKC

**Comment by mf-code** [comment]
[5637] - FsdwJU2a

**Comment by mf-code** [comment]
[5637] - yAG7qTjo

**Comment by mf-code** [comment]
[5637] - Xd4p38Gf

**Comment by mf-code** [comment]
[5637] - hZtV7j1v

**Comment by mf-code** [comment]
[5637] - openjdk8 - Allure report on Netlify: https://5eea0a3b141d271364671a66--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5637] - openjdk10 - Allure report on Netlify: https://5eea0b34e35daf7d29a5a548--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5643] - lNsRFnFU

**Comment by mf-code** [comment]
[5643] - aPu2UrGT

**Comment by mf-code** [comment]
[5643] - vpe6hwxo

**Comment by mf-code** [comment]
[5643] - PdSXhm0z

**Comment by mf-code** [comment]
[5643] - U43Rwhrx

**Comment by mf-code** [comment]
[5643] - Fjbsce8Y

**Comment by mf-code** [comment]
[5643] - 3SJY67c8

**Comment by mf-code** [comment]
[5643] - yO5xTZyt

**Comment by mf-code** [comment]
[5643] - 2AeAl3KB

**Comment by mf-code** [comment]
[5643] - kxTpdj51

**Comment by mf-code** [comment]
[5643] - Ov4mvks8

**Comment by mf-code** [comment]
[5643] - QIYmEvOQ

**Comment by mf-code** [comment]
[5643] - 3PT8jUj3

**Comment by mf-code** [comment]
[5643] - lSGDX5vI

**Comment by mf-code** [comment]
[5643] - openjdk8 - Allure report on Netlify: https://5eeb10a248b9dcf2c0a845e5--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5643] - openjdk10 - Allure report on Netlify: https://5eeb117048b9dccdb8a847b2--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5656] - SmY9s7ld

**Comment by mf-code** [comment]
[5656] - NqKNC2Wz

**Comment by mf-code** [comment]
[5656] - vpE7syIJ

**Comment by mf-code** [comment]
[5656] - BYA7XCtD

**Comment by mf-code** [comment]
[5656] - ZeDpoidO

**Comment by mf-code** [comment]
[5656] - dUEFnhuA

**Comment by mf-code** [comment]
[5656] - nzGDvaDh

**Comment by mf-code** [comment]
[5656] - KRQJmDgk

**Comment by mf-code** [comment]
[5656] - yPBxTbnW

**Comment by mf-code** [comment]
[5656] - 5Thzg6jl

**Comment by mf-code** [comment]
[5656] - ngLBpF5c

**Comment by mf-code** [comment]
[5656] - Z733XKfK

**Comment by mf-code** [comment]
[5656] - LztTHEtA

**Comment by mf-code** [comment]
[5656] - 3oqtZBcV

**Comment by mf-code** [comment]
[5656] - openjdk8 - Allure report on Netlify: https://5eecdf966b4b9491b2f5c401--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5656] - openjdk10 - Allure report on Netlify: https://5eece09fb9ab1186cd027ce1--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5677] - YnbgpZiv

**Comment by mf-code** [comment]
[5677] - moqhPc9T

**Comment by mf-code** [comment]
[5677] - rqnn4aID

**Comment by mf-code** [comment]
[5677] - HJUeeMEe

**Comment by mf-code** [comment]
[5677] - mXnJB0p3

**Comment by mf-code** [comment]
[5677] - 2DHhvNzD

**Comment by mf-code** [comment]
[5677] - ITyUfkqx

**Comment by mf-code** [comment]
[5677] - 3XHYmCVj

**Comment by mf-code** [comment]
[5677] - 8dlQfJ8w

**Comment by mf-code** [comment]
[5677] - zwbB6Nwz

**Comment by mf-code** [comment]
[5677] - QoZJH6AP

**Comment by mf-code** [comment]
[5677] - dO6w3iD0

**Comment by mf-code** [comment]
[5677] - RUkYRhcQ

**Comment by mf-code** [comment]
[5677] - FmbWs9Ed

**Comment by mf-code** [comment]
[5677] - openjdk8 - Allure report on Netlify: https://5ef5c2aeffd58a64b2bfe316--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5677] - openjdk10 - Allure report on Netlify: https://5ef5c3b593a68ea502287e6f--musing-swartz-6fc060.netlify.app

**Comment by RomanIovlev** [comment]
Please remove mockito dependencies from dependencies and build section of the original angular tests

**Comment by mf-code** [comment]
[5682] - eo8Kiqdz

**Comment by mf-code** [comment]
[5682] - oYw2Oruh

**Comment by mf-code** [comment]
[5682] - poe3GXKV

**Comment by mf-code** [comment]
[5682] - oMFzABRm

**Comment by mf-code** [comment]
[5682] - fSPMjQhr

**Comment by mf-code** [comment]
[5682] - hOTL6C3d

**Comment by mf-code** [comment]
[5682] - kAo6MgiM

**Comment by mf-code** [comment]
[5682] - hSLwKzAR

**Comment by mf-code** [comment]
[5682] - zx6th3gM

**Comment by mf-code** [comment]
[5682] - ZlRHo1oB

**Comment by mf-code** [comment]
[5682] - EF3W9eLU

**Comment by mf-code** [comment]
[5682] - E5zvSvX4

**Comment by mf-code** [comment]
[5682] - A0QNRE6a

**Comment by mf-code** [comment]
[5682] - crORmYaS

**Comment by mf-code** [comment]
[5682] - openjdk8 - Allure report on Netlify: https://5ef766d71131783ceebb0bba--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5682] - openjdk10 - Allure report on Netlify: https://5ef767ca06d3b4d436c5af6a--musing-swartz-6fc060.netlify.app

**Pull request merged**
