### PR TITLE
Android native radio button tests

### PR DESCRIPTION
**Pull request by Innokentiy945**
Implementing Radio Buttons tests

### CODE REVIEW

**Comment by mf-code** [comment]
[6404] - a8WkGjJehyrL

**Comment by mf-code** [comment]
[6404] - BsajHs556Ttu

**Comment by mf-code** [comment]
[6404] - eglLPAco4pIn

**Comment by mf-code** [comment]
[6404] - BYQ7sIYSPAYo

**Comment by mf-code** [comment]
[6404] - POUla9QSTt3j

**Comment by mf-code** [comment]
[6404] - 8i1u6z5dsRXD

**Comment by mf-code** [comment]
[6404] - 5yoRjc4PXo8W

**Comment by mf-code** [comment]
[6404] - QLuIUZ3ZZ348

**Comment by mf-code** [comment]
[6404] - rQGBFrq3gZ1E

**Comment by mf-code** [comment]
[6404] - ZDlGtplpVXfv

**Comment by mf-code** [comment]
[6404] - vaKS2BgJr6c9

**Comment by mf-code** [comment]
[6404] - DfhamCpbPuah

**Comment by mf-code** [comment]
[6404] - Za69Se7bF3Y7

**Comment by mf-code** [comment]
[6404] - gP7TPdWWgzKh

**Comment by mf-code** [comment]
[6404] - IbnFD4dpGHNB

**Comment by mf-code** [comment]
[6404] - 4Orfy6tulviH

**Comment by mf-code** [comment]
[6404] - mMNgM8Km0MAg

**Comment by mf-code** [comment]
[6404] - Rz9kV2nuOR8d

**Comment by mf-code** [comment]
[6404] - openjdk8 - Allure report on Netlify: https://5fa955520b8561e0f2aab55e--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6404] - openjdk10 - Allure report on Netlify: https://5fa9565a2629f4ca694d5aaf--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6407] - obUkc1EMjrmi

**Comment by mf-code** [comment]
[6407] - zNhilBGN0pD3

**Comment by mf-code** [comment]
[6407] - AdUuWTz7sk2S

**Comment by mf-code** [comment]
[6407] - cWmZhEDXt9ux

**Comment by mf-code** [comment]
[6407] - 04fSduvwy0Wv

**Comment by mf-code** [comment]
[6407] - U97vT2hpizOb

**Comment by mf-code** [comment]
[6407] - 5HDu8NXp6K4w

**Comment by mf-code** [comment]
[6407] - xGX9oY4N7zyN

**Comment by mf-code** [comment]
[6407] - Thh0rvaJ0Dhp

**Comment by mf-code** [comment]
[6407] - qAuLqHcEd2lf

**Comment by mf-code** [comment]
[6407] - FrZbjkSmPI6P

**Comment by mf-code** [comment]
[6407] - u7pV8UPGw78B

**Comment by mf-code** [comment]
[6407] - 0e05QK6M8eHR

**Comment by mf-code** [comment]
[6407] - fdFv3hKir2rx

**Comment by mf-code** [comment]
[6407] - KHFmGU0L9LAI

**Comment by mf-code** [comment]
[6407] - Ozw2uvxIVTYw

**Comment by mf-code** [comment]
[6407] - kwN5CUlD2ZAB

**Comment by mf-code** [comment]
[6407] - uFyVklUq7Tll

**Comment by mf-code** [comment]
[6407] - openjdk8 - Allure report on Netlify: https://5fa989a5e90686fb84476d5d--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6407] - openjdk10 - Allure report on Netlify: https://5fa98b12eaef0921ca979d73--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6411] - H0HqbrI2uIJP

**Comment by mf-code** [comment]
[6411] - NgrCq4OTLzRe

**Comment by mf-code** [comment]
[6411] - eg5pchXctGWy

**Comment by mf-code** [comment]
[6411] - drrmICgEVphS

**Comment by mf-code** [comment]
[6411] - agKfEWHCZsHI

**Comment by mf-code** [comment]
[6411] - ZA9IbQmFypBJ

**Comment by mf-code** [comment]
[6411] - vPUOx0Y5EPJk

**Comment by mf-code** [comment]
[6411] - WuyV74xZVE6m

**Comment by mf-code** [comment]
[6411] - XTpQ6a1c7lJi

**Comment by mf-code** [comment]
[6411] - VTVJAbisrmhI

**Comment by mf-code** [comment]
[6411] - trpeTWz1FTue

**Comment by mf-code** [comment]
[6411] - cbyB2aLaojJZ

**Comment by mf-code** [comment]
[6411] - 4tSGoavfQTQZ

**Comment by mf-code** [comment]
[6411] - xcQgwh34gnWb

**Comment by mf-code** [comment]
[6411] - Hyc9fGoDTXGI

**Comment by mf-code** [comment]
[6411] - HCVAPPsgj6QU

**Comment by mf-code** [comment]
[6411] - lz9sDme8Gn7Z

**Comment by mf-code** [comment]
[6411] - 67A6si3OUjzG

**Comment by mf-code** [comment]
[6411] - openjdk8 - Allure report on Netlify: https://5fad021d95d1298d1fa60bca--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6411] - openjdk10 - Allure report on Netlify: https://5fad02efb6c17888eb915a7d--musing-swartz-6fc060.netlify.app

**Comment by vsevolod-adrianov** [comment]
Wait implementaion of list for jdi-light-mobile

**Pull request closed without merging**
