### PR TITLE
#2245 Text Field tests

### PR DESCRIPTION
**Pull request by Olesya24**

### CODE REVIEW

**Comment by mf-code** [comment]
[6234] - qqa3Vfnh9kmR

**Comment by mf-code** [comment]
[6234] - mEYYvC2lKZp1

**Comment by mf-code** [comment]
[6234] - q7xNVsuefAV7

**Comment by mf-code** [comment]
[6234] - UlqCqs9wJ3HK

**Comment by mf-code** [comment]
[6234] - ia3naLN6943m

**Comment by mf-code** [comment]
[6234] - xNoFz6WQwGQu

**Comment by mf-code** [comment]
[6234] - zSQ5oZxKh7ym

**Comment by mf-code** [comment]
[6234] - 74E2GfbArrXe

**Comment by mf-code** [comment]
[6234] - YtVDoq2F91zf

**Comment by mf-code** [comment]
[6234] - IP9HL8O5bCMg

**Comment by mf-code** [comment]
[6234] - dOEw8yjjXmuX

**Comment by mf-code** [comment]
[6234] - GhliBmA9FaNj

**Comment by mf-code** [comment]
[6234] - 85wUxAqm4B4a

**Comment by mf-code** [comment]
[6234] - x9NCJPncWAGZ

**Comment by mf-code** [comment]
[6234] - jcVacgX8pOsG

**Comment by mf-code** [comment]
[6234] - OVuVYCKreevT

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-mobile-tests/src/test/java/nativeapp_android/tests/TextFieldTests.java  1
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/elements/common/app/android/TextField.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6293268&bid=20473026)

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/elements/common/app/android/TextField.java  1
- jdi-light-mobile-tests/src/test/java/nativeapp_android/tests/TextFieldTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6293268&bid=20473026)

**Comment by mf-code** [comment]
[6274] - BknJtFwhhsVG

**Comment by mf-code** [comment]
[6274] - QpvWCz8emxdB

**Comment by mf-code** [comment]
[6274] - N7weQwNSCA3b

**Comment by mf-code** [comment]
[6274] - tVlhm2fCaJq0

**Comment by mf-code** [comment]
[6274] - kgQXHMTYejPO

**Comment by mf-code** [comment]
[6274] - ACr7bOWLpS4m

**Comment by mf-code** [comment]
[6274] - KIg8pFwvkHcw

**Comment by mf-code** [comment]
[6274] - qg09jAUx3oNx

**Comment by mf-code** [comment]
[6274] - zAMUUT80hFMQ

**Comment by mf-code** [comment]
[6274] - 9SatLLAEXbNg

**Comment by mf-code** [comment]
[6274] - NtzlzEKHOryS

**Comment by mf-code** [comment]
[6274] - ilSfPKLYpTDP

**Comment by mf-code** [comment]
[6274] - qKDAxQTVrPq6

**Comment by mf-code** [comment]
[6274] - lbxg29eDW63T

**Comment by mf-code** [comment]
[6274] - 3UI0f7KCXN93

**Comment by mf-code** [comment]
[6276] - tQ3MfRLB2u1U

**Comment by mf-code** [comment]
[6276] - evyYEHHkp21S

**Comment by mf-code** [comment]
[6274] - b7Lp9aAjj946

**Comment by mf-code** [comment]
[6276] - NgB9UhzshqxM

**Comment by mf-code** [comment]
[6274] - openjdk8 - Allure report on Netlify: https://5f85adb31179eb1e1b7066f9--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6276] - X2xFHmFYYzUp

**Comment by mf-code** [comment]
[6274] - openjdk10 - Allure report on Netlify: https://5f85aec81250bd1bc244d688--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6276] - rJIdVDQQ4ARz

**Comment by mf-code** [comment]
[6276] - iiIDjb0XPizA

**Comment by mf-code** [comment]
[6276] - kSrL4nuTnK9C

**Comment by mf-code** [comment]
[6276] - sjctgJ4DBsg3

**Comment by mf-code** [comment]
[6276] - QAC043GIIfag

**Comment by mf-code** [comment]
[6276] - ifxjmdy14cvi

**Comment by mf-code** [comment]
[6276] - myPg4QWXopkx

**Comment by mf-code** [comment]
[6276] - 1uAU5AOEIWKy

**Comment by mf-code** [comment]
[6276] - 6KkjsIdpvJ5G

**Comment by mf-code** [comment]
[6276] - OYxmAotjL1kn

**Comment by mf-code** [comment]
[6276] - 4PjOAYBku2Xt

**Comment by mf-code** [comment]
[6276] - openjdk8 - Allure report on Netlify: https://5f85bbb386ab042bf41d45c8--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6276] - openjdk10 - Allure report on Netlify: https://5f85bcaacdda7523b7153021--musing-swartz-6fc060.netlify.app

**Review by alexarm — APPROVED** [review]

**Pull request merged**
