### PR TITLE
Angular 1961

### PR DESCRIPTION
**Pull request by Sudalius**

### CODE REVIEW

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/IconsTests.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/SpinnerTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5548597&bid=18193673)

**Comment by mf-code** [comment]
[5345] - d42KTpcs

**Comment by mf-code** [comment]
[5345] - ntmhWJbp

**Comment by mf-code** [comment]
[5345] - kfzrE5a7

**Comment by mf-code** [comment]
[5345] - EaYwfOhT

**Comment by mf-code** [comment]
[5345] - Allure report on Netlify: https://5ec3a27c8cb584234387110e--musing-swartz-6fc060.netlify.app

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/IconsTests.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/SpinnerTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5548597&bid=18193673)

**Comment by mf-code** [comment]
[5367] - hXF64V1r

**Comment by mf-code** [comment]
[5367] - yP29h7nk

**Comment by mf-code** [comment]
[5367] - fnsz3LP4

**Comment by mf-code** [comment]
[5367] - IOBwCfcE

**Comment by mf-code** [comment]
[5367] - geb9pNIo

**Comment by mf-code** [comment]
[5367] - qkLztLAd

**Comment by mf-code** [comment]
[5367] - Allure report on Netlify: https://5ec64cb3a47307d5617b0bd8--musing-swartz-6fc060.netlify.app

**Comment by Sudalius** [comment]
Fixed classes and documentation has been added

**Comment by mf-code** [comment]
[5377] - ckdqOXM0

**Comment by mf-code** [comment]
[5377] - S7e6NMp9

**Comment by mf-code** [comment]
[5377] - eXLnfKVo

**Comment by mf-code** [comment]
[5377] - x5XtO0Id

**Comment by mf-code** [comment]
[5377] - 5YW4i24R

**Comment by mf-code** [comment]
[5378] - AyAn7rdT

**Comment by mf-code** [comment]
[5378] - ihJDgZ3z

**Comment by mf-code** [comment]
[5378] - zMIKWyIo

**Comment by mf-code** [comment]
[5378] - M8ULeURy

**Comment by mf-code** [comment]
[5378] - o2c7KSNQ

**Comment by mf-code** [comment]
[5377] - Xm0IU8gI

**Comment by mf-code** [comment]
[5377] - Allure report on Netlify: https://5ec7960fce81304953610c64--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5378] - iB7bYgM0

**Comment by mf-code** [comment]
[5378] - Allure report on Netlify: https://5ec7983d014008058a65b632--musing-swartz-6fc060.netlify.app

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/IconsTests.java  1
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/SpinnerTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5548597&bid=18193673)

**Comment by mf-code** [comment]
[5403] - vuYehVDO

**Comment by mf-code** [comment]
[5403] - zHfeqOkA

**Comment by mf-code** [comment]
[5403] - Q2rOlhcV

**Comment by mf-code** [comment]
[5403] - o3N7F8Si

**Comment by mf-code** [comment]
[5403] - ClAgNbQ4

**Comment by mf-code** [comment]
[5403] - n95COObd

**Comment by mf-code** [comment]
[5403] - Allure report on Netlify: https://5ecbcded45228a43c5799747--musing-swartz-6fc060.netlify.app

**Comment by Sudalius** [comment]
> create button to show/hide progress on click and check that spinner is not visible too

We should create different task for it

**Pull request merged**
