### PR TITLE
1536 form example

### PR DESCRIPTION
**Pull request by hellokitties**

### CODE REVIEW

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/example/composite/FormExampleTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=4815752&bid=16015459)

**Comment by mf-code** [comment]
[4456] - https://transfer.sh/FDwvj/jdi-performance.tar.gz

**Comment by mf-code** [comment]
[4456] - https://transfer.sh/w1i7W/jdi-light-examples.tar.gz

**Comment by mf-code** [comment]
[4456] - https://transfer.sh/oz28I/jdi-light-html-tests.tar.gz

**Comment by mf-code** [comment]
[4456] - Allure report on Netlify: https://5e1d933553bd684417fe35c1--musing-swartz-6fc060.netlify.com

**Pull request merged**
