### PR TITLE
1713 appium configuration

### PR DESCRIPTION
**Pull request by Inov92**
#1713

Hardcoded configuration for Android device crated
Lunching appium test ability added
Configuration updated

### CODE REVIEW

**Comment by Inov92** [comment]
Don't merge until @Nikolai812 (Nikolai Romanenko) approval

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
           

Complexity increasing per file
==============================
- jdi-light-mobile/src/main/java/com/epam/jdi/mobile/driver/get/DriverTypes.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5016554&bid=16540474)

**Comment by mf-code** [comment]
[4798] - https://transfer.sh/eUodS/jdi-light-html-tests.tar.gz

**Comment by mf-code** [comment]
[4798] - https://transfer.sh/MhsyY/jdi-performance.tar.gz

**Comment by mf-code** [comment]
[4800] - https://transfer.sh/Nj07d/jdi-performance.tar.gz

**Comment by Nikolai812** [comment]
Merging to jdi-mobile-web-remote

**Pull request merged**
