### PR TITLE
Refactored Checkbox element.

### PR DESCRIPTION
**Pull request by gbuh**
Refactored Checkbox element.

### CODE REVIEW

**Comment by mf-code** [comment]
[6166] - kYTVSlfa0X2a

**Comment by mf-code** [comment]
[6166] - kk96kT8o8fTF

**Comment by mf-code** [comment]
[6166] - H7B54wrV0mJV

**Comment by mf-code** [comment]
[6166] - CNZHCcEntYbH

**Comment by mf-code** [comment]
[6166] - cwagHbzaW3Je

**Comment by mf-code** [comment]
[6166] - USPBsnO7uZvl

**Comment by mf-code** [comment]
[6166] - o8ZxfqiGlFfw

**Comment by mf-code** [comment]
[6166] - h98Lf62ekhhc

**Comment by mf-code** [comment]
[6166] - KVvsu5Vyfobn

**Comment by mf-code** [comment]
[6166] - bzZFhWbtQedA

**Comment by mf-code** [comment]
[6166] - aGCaEMabyMUi

**Comment by mf-code** [comment]
[6166] - BjlTB698APTG

**Comment by mf-code** [comment]
[6166] - 3LFNgczZfX6W

**Comment by mf-code** [comment]
[6166] - jNTC6ec2BbvS

**Comment by mf-code** [comment]
[6166] - gNucx8A31NGB

**Comment by mf-code** [comment]
[6166] - UIRWifF1xzsf

**Comment by mf-code** [comment]
[6166] - rwdGNoRkd6FY

**Comment by mf-code** [comment]
[6166] - dytGikN3DCyt

**Comment by mf-code** [comment]
[6166] - 4tc6erzAsJoC

**Comment by mf-code** [comment]
[6166] - 1Ssqcew8VhRw

**Comment by mf-code** [comment]
[6168] - dvvkRS1tibkb

**Comment by mf-code** [comment]
[6168] - SsEqtQTUzIfz

**Comment by mf-code** [comment]
[6168] - ztxtzyQXGkl1

**Comment by mf-code** [comment]
[6168] - Ox8rELmist1u

**Comment by mf-code** [comment]
[6168] - nG1NghsY2tc5

**Comment by mf-code** [comment]
[6168] - 19QkSbF1csVj

**Comment by mf-code** [comment]
[6168] - 79rnWD8ONPHE

**Comment by mf-code** [comment]
[6168] - 2VHqcv0dssZx

**Comment by mf-code** [comment]
[6168] - eJYPCx3oj7Ay

**Comment by mf-code** [comment]
[6168] - s9o9OVRZZLgJ

**Comment by mf-code** [comment]
[6168] - hxXFBxoNa1dJ

**Comment by mf-code** [comment]
[6168] - stTELFqAMRw2

**Comment by mf-code** [comment]
[6168] - lRRh31dFYjzn

**Comment by mf-code** [comment]
[6168] - NN6iMm3DcUif

**Comment by mf-code** [comment]
[6168] - 4hGlS8Wb1mji

**Comment by mf-code** [comment]
[6168] - iniFg29ehI81

**Comment by mf-code** [comment]
[6168] - Gkjzo5di9GbP

**Comment by mf-code** [comment]
[6168] - GyboOJD2jYCp

**Comment by mf-code** [comment]
[6169] - Bg3I3QDGys5L

**Comment by mf-code** [comment]
[6169] - DvV8m7183y8I

**Comment by mf-code** [comment]
[6169] - DAUUh7fFphWY

**Comment by mf-code** [comment]
[6169] - oTLXBPeBJfGh

**Comment by mf-code** [comment]
[6169] - V3p7RFvw5XPx

**Comment by mf-code** [comment]
[6169] - E44qfjUvwZxe

**Comment by mf-code** [comment]
[6169] - 8S9XVEGuFszN

**Comment by mf-code** [comment]
[6169] - QDDKVILtaDho

**Comment by mf-code** [comment]
[6169] - 4pvbnsZLr4R2

**Comment by mf-code** [comment]
[6169] - SeDgBjE7DVEq

**Comment by mf-code** [comment]
[6169] - KaPF6WoL5R0K

**Comment by mf-code** [comment]
[6169] - YJceyy4r5ivT

**Comment by mf-code** [comment]
[6169] - jinJeQDhMKjB

**Comment by mf-code** [comment]
[6169] - aGFJ48XWIQi8

**Comment by mf-code** [comment]
[6169] - ietIl0mPW4XJ

**Comment by mf-code** [comment]
[6169] - fwJ3lCpjRcqu

**Comment by mf-code** [comment]
[6169] - 8NPG9G0rv1pI

**Comment by mf-code** [comment]
[6169] - L5ZS9dKrYvUi

**Comment by mf-code** [comment]
[6170] - s3Mxlx5ptQDG

**Comment by mf-code** [comment]
[6170] - C9zHTfh3MiGf

**Comment by mf-code** [comment]
[6170] - IEnilIkhfqwA

**Comment by mf-code** [comment]
[6170] - aYFcI0qGy61K

**Comment by mf-code** [comment]
[6170] - Il00MjRBq4AS

**Comment by mf-code** [comment]
[6170] - gR3muf0f02bx

**Comment by mf-code** [comment]
[6170] - Z2ib3CIATf6G

**Comment by mf-code** [comment]
[6170] - ZNFBC4WKIGgF

**Comment by mf-code** [comment]
[6170] - YPD5xSVWEIZw

**Comment by mf-code** [comment]
[6170] - BGajdBE37SCa

**Comment by mf-code** [comment]
[6170] - ec3VNbO3iem6

**Comment by mf-code** [comment]
[6170] - fcRMVH4nmOVY

**Comment by mf-code** [comment]
[6170] - cPoPRq9RxQE5

**Comment by mf-code** [comment]
[6170] - Qm1lsPmcMkgD

**Comment by mf-code** [comment]
[6170] - 3G4sLtrUHzLO

**Comment by mf-code** [comment]
[6170] - 9y90uhN3CazU

**Comment by mf-code** [comment]
[6170] - ZABnmDTZFzvd

**Comment by mf-code** [comment]
[6170] - YWEvEPoj41h3

**Comment by mf-code** [comment]
[6172] - 3blYSjHMAr2i

**Comment by mf-code** [comment]
[6172] - oYIqW6cJY6GD

**Comment by mf-code** [comment]
[6172] - hpXLrhVOaJQu

**Comment by mf-code** [comment]
[6172] - cqmPsOoSArkD

**Comment by mf-code** [comment]
[6172] - 3e5fVi3pR6M9

**Comment by mf-code** [comment]
[6172] - PUT7jW8rbOQi

**Comment by mf-code** [comment]
[6172] - ZjMgbxc1iNry

**Comment by mf-code** [comment]
[6172] - BUCB3nZEdwAk

**Comment by mf-code** [comment]
[6172] - openjdk8 - Allure report on Netlify: https://5f69c6bd6c60d00fcbf3c906--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6172] - openjdk10 - Allure report on Netlify: https://5f69c6f5f210d3f31ad0c436--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6175] - hHL72JExNhjx

**Comment by mf-code** [comment]
[6175] - Gts3zllCCCSj

**Comment by mf-code** [comment]
[6175] - vOk0tjKKbDgy

**Comment by mf-code** [comment]
[6175] - DLAsMhsuWOaw

**Comment by mf-code** [comment]
[6175] - Bq7mdQsN3gui

**Comment by mf-code** [comment]
[6175] - vbo0ouUZCcDl

**Comment by mf-code** [comment]
[6175] - q8aMRB5VTjAs

**Comment by mf-code** [comment]
[6175] - orws1GH5sgFY

**Comment by mf-code** [comment]
[6175] - 8c6QeIbT2sFk

**Comment by mf-code** [comment]
[6175] - ex3VaqNxE3Ig

**Comment by mf-code** [comment]
[6175] - ZSW3MVXV47h8

**Comment by mf-code** [comment]
[6175] - yhPvQpE0y80J

**Comment by mf-code** [comment]
[6175] - KaeCFn8zcHWy

**Comment by mf-code** [comment]
[6175] - kzCMdXLmaMML

**Comment by mf-code** [comment]
[6175] - HCdS2pCtvcXG

**Comment by mf-code** [comment]
[6175] - e7ozl0wv24Kk

**Comment by mf-code** [comment]
[6175] - aKpPkASh8631

**Comment by mf-code** [comment]
[6175] - 3tmViN02DtIu

**Comment by mf-code** [comment]
[6178] - wwCNIOtcbXKz

**Comment by mf-code** [comment]
[6178] - RgJb4Z4FlBqL

**Comment by mf-code** [comment]
[6178] - VSCd6Ylkp8VS

**Comment by mf-code** [comment]
[6178] - OtDZlBlvTLID

**Comment by mf-code** [comment]
[6178] - qBnD6gmfeY0j

**Comment by mf-code** [comment]
[6178] - HccK436zTPhc

**Comment by mf-code** [comment]
[6178] - 7XJLSlkUrY93

**Comment by mf-code** [comment]
[6178] - ifldv01ZNYpK

**Comment by mf-code** [comment]
[6178] - 7STrnmwVySk6

**Comment by mf-code** [comment]
[6178] - kawtnD1Uo8EX

**Comment by mf-code** [comment]
[6178] - bSvZ1HxJ7cIg

**Comment by mf-code** [comment]
[6178] - 986maCTU01Gh

**Comment by mf-code** [comment]
[6178] - u02efFAfSFO2

**Comment by mf-code** [comment]
[6178] - ToKERKTtHGqx

**Comment by mf-code** [comment]
[6178] - 8xd1VKyoq2NH

**Comment by mf-code** [comment]
[6178] - B46aPQg6oeY2

**Comment by mf-code** [comment]
[6178] - ZOljGzrpVdUb

**Comment by mf-code** [comment]
[6178] - I8WaGO2tF5bi

**Comment by mf-code** [comment]
[6185] - OQGlYrOTV2Pg

**Comment by mf-code** [comment]
[6185] - dBHpJNLvMqZH

**Comment by mf-code** [comment]
[6185] - OCVDhJbLz00e

**Comment by mf-code** [comment]
[6185] - hK33XWlNrjgX

**Comment by mf-code** [comment]
[6185] - bA1nEslGyJFq

**Comment by mf-code** [comment]
[6185] - w6F8STckYTtZ

**Comment by mf-code** [comment]
[6185] - qsQjjOu3bPDR

**Comment by mf-code** [comment]
[6185] - HlbW7OiL6VB2

**Comment by mf-code** [comment]
[6185] - H3LDz4IE9Rkm

**Comment by mf-code** [comment]
[6185] - nfaWMFf2zJoT

**Comment by mf-code** [comment]
[6185] - ktKrnoHEhDaq

**Comment by mf-code** [comment]
[6185] - AzvES8ie02nV

**Comment by mf-code** [comment]
[6185] - byR5weyeFth4

**Comment by mf-code** [comment]
[6185] - LLFaCmO96lQE

**Comment by mf-code** [comment]
[6185] - Q7ph6tavYCpX

**Comment by mf-code** [comment]
[6185] - An1UUapmPDC1

**Comment by mf-code** [comment]
[6185] - NHxUP2bllk6B

**Comment by mf-code** [comment]
[6185] - SPwsUgbr5KDK

**Comment by mf-code** [comment]
[6185] - openjdk8 - Allure report on Netlify: https://5f6ae3319fcca2b4bf86e30f--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6185] - openjdk10 - Allure report on Netlify: https://5f6ae452a45deb9682940945--musing-swartz-6fc060.netlify.app

**Review by AlexSofft — APPROVED** [review]

**Comment by mf-code** [comment]
[6188] -

**Comment by mf-code** [comment]
[6188] - Ucha5T0BZVAx

**Comment by mf-code** [comment]
[6188] -

**Comment by mf-code** [comment]
[6188] - POX9QlQWoSOE

**Comment by mf-code** [comment]
[6188] - AkKxOUhjg1uI

**Comment by mf-code** [comment]
[6188] - AEPDrqZT7g4i

**Comment by mf-code** [comment]
[6188] - N8WmsLHektUK

**Comment by mf-code** [comment]
[6188] - WELFUm7IAPZw

**Comment by mf-code** [comment]
[6188] - ZNVHzQw68i6u

**Comment by mf-code** [comment]
[6188] - eqdq8YEDPxE2

**Comment by mf-code** [comment]
[6188] - lUKNw9NbN20N

**Comment by mf-code** [comment]
[6188] - KiXRgMpnv58a

**Comment by mf-code** [comment]
[6188] - 5TFyDj17lQnV

**Comment by mf-code** [comment]
[6188] - 78SdEqJpN8pW

**Comment by mf-code** [comment]
[6188] - HKUMKAdbLRpA

**Comment by mf-code** [comment]
[6188] - En0k8lEy9KQt

**Comment by mf-code** [comment]
[6188] - nitfD8m5Ac25

**Comment by mf-code** [comment]
[6188] - TWSuILkXjKRj

**Comment by mf-code** [comment]
[6188] - openjdk8 - Allure report on Netlify: https://5f6bb26c38acbf302936ac6b--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6188] - openjdk10 - Allure report on Netlify: https://5f6bb3be9e294b316b75d259--musing-swartz-6fc060.netlify.app

**Pull request merged**
