### PR TITLE
Added Ripple element and test cases.

### PR DESCRIPTION
**Pull request by gbuh**
Added Ripple element and test cases.

### CODE REVIEW

**Comment by mf-code** [comment]
[6027] - uXyhRM0m62H2

**Comment by mf-code** [comment]
[6027] - lu506dbVypkM

**Comment by mf-code** [comment]
[6027] - V4JHXcHZ3EEq

**Comment by mf-code** [comment]
[6027] - kcZXY4Uedfva

**Comment by mf-code** [comment]
[6027] - S5ELZeev3Gt2

**Comment by mf-code** [comment]
[6027] - 4SnINIeHnWRI

**Comment by mf-code** [comment]
[6027] - K02utPAmbXmI

**Comment by mf-code** [comment]
[6027] - ulOmWXmAZ7x9

**Comment by mf-code** [comment]
[6027] - GCEt1QvUmQtG

**Comment by mf-code** [comment]
[6027] - qUsuHAhP6XDK

**Comment by mf-code** [comment]
[6027] - suIEr8CI9aAL

**Comment by mf-code** [comment]
[6027] - RwgvrK1eQk25

**Comment by mf-code** [comment]
[6027] - EbEdF6wZdhTH

**Comment by mf-code** [comment]
[6027] - e472JGkoX7cT

**Comment by mf-code** [comment]
[6027] - rUEhZBrKpus4

**Comment by mf-code** [comment]
[6027] - sg60VbWqkK3A

**Comment by mf-code** [comment]
[6027] - IK0hsxi0ms7n

**Comment by mf-code** [comment]
[6027] - ncHMZXLUHSz0

**Comment by mf-code** [comment]
[6027] - openjdk8 - Allure report on Netlify: https://5f52ad340f67a33895e75980--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6027] - openjdk10 - Allure report on Netlify: https://5f52aec80612fc37208206d9--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6032] - J9PXqvwesHup

**Comment by mf-code** [comment]
[6032] - vOge6AU4jNvb

**Comment by mf-code** [comment]
[6032] - kL6oHPd7tWQD

**Comment by mf-code** [comment]
[6032] - fgS5EbZrut7B

**Comment by mf-code** [comment]
[6032] - jj4Gk6iZGXxl

**Comment by mf-code** [comment]
[6032] - Y2Eswv1gVyA0

**Comment by mf-code** [comment]
[6032] - RNvteAN4QVKZ

**Comment by mf-code** [comment]
[6032] - ylcSH6JiefRT

**Comment by mf-code** [comment]
[6032] - pu45A1Wqxqmp

**Comment by mf-code** [comment]
[6032] - Ty6p7em0J5Jq

**Comment by mf-code** [comment]
[6032] - ZKtMVyMtn03p

**Comment by mf-code** [comment]
[6032] - r7GOH44FdSBh

**Comment by mf-code** [comment]
[6032] - 6Foxzw5961Uc

**Comment by mf-code** [comment]
[6032] - WqgzDeyP9KWi

**Review by AlexSofft — APPROVED** [review]

**Comment by mf-code** [comment]
[6032] - KtI4bjufh8wl

**Comment by mf-code** [comment]
[6032] - xgWkZOkDWBMe

**Comment by mf-code** [comment]
[6033] - n1lCrxQwdYYQ

**Comment by mf-code** [comment]
[6032] - pKfDgFupo71k

**Comment by mf-code** [comment]
[6033] - 0E4CmGB6vCuC

**Comment by mf-code** [comment]
[6033] - 1qw46BPOxvOV

**Comment by mf-code** [comment]
[6033] - VqrT2KBbjuQd

**Comment by mf-code** [comment]
[6033] - 5NgNhzTH5JNg

**Comment by mf-code** [comment]
[6032] - openjdk8 - Allure report on Netlify: https://5f55e0b3c1f0970878158992--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6033] - hcNIdpMbUod2

**Comment by mf-code** [comment]
[6032] - openjdk10 - Allure report on Netlify: https://5f55e21f080cf0a34862f594--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6033] - 9ughKyxwmckN

**Comment by mf-code** [comment]
[6033] - GIbnOfmUI28Q

**Comment by mf-code** [comment]
[6032] - jIsLdiVeQKZk

**Comment by mf-code** [comment]
[6033] - TvhyNrGOqfgr

**Comment by mf-code** [comment]
[6033] - jPS7NH8m2zd0

**Comment by mf-code** [comment]
[6032] - 3RWXINig2Dq3

**Comment by mf-code** [comment]
[6033] - 8MFdV7hoCT51

**Comment by mf-code** [comment]
[6033] - sDdK83CQLNPj

**Comment by mf-code** [comment]
[6032] - 7sQcX4kBmN9F

**Comment by mf-code** [comment]
[6032] - HEKcKjYGN6Py

**Comment by mf-code** [comment]
[6033] - 1tcegLnOuden

**Comment by mf-code** [comment]
[6033] - UqUKgMlEZeUe

**Comment by mf-code** [comment]
[6032] - Z2761laXTerV

**Comment by mf-code** [comment]
[6033] - f3Ce37Ytg4q1

**Comment by mf-code** [comment]
[6033] - ZGTqCM9rvCxS

**Comment by mf-code** [comment]
[6033] - F25cFxigv75N

**Comment by mf-code** [comment]
[6033] - hk33HLmA23qW

**Comment by mf-code** [comment]
[6032] - openjdk8 - Allure report on Netlify: https://5f55f005080cf0b88a62f173--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6032] - openjdk10 - Allure report on Netlify: https://5f55f144cbf55b17e43a2bfc--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6034] - lpUJcvWAkhSN

**Comment by mf-code** [comment]
[6034] - wjBLnbfltQ2v

**Comment by mf-code** [comment]
[6034] - UlAdpAUFF82p

**Comment by mf-code** [comment]
[6034] - hBctUcMlXryr

**Comment by mf-code** [comment]
[6034] - HffOw2glbKgq

**Comment by mf-code** [comment]
[6034] - 624vgJcxId2t

**Comment by mf-code** [comment]
[6034] - HUa94licUGri

**Comment by mf-code** [comment]
[6034] - dBiKsn4ZL1Ga

**Comment by mf-code** [comment]
[6034] - 4moyYh5SrQKE

**Comment by mf-code** [comment]
[6034] - Dq0Ne8fgODGo

**Comment by mf-code** [comment]
[6034] - FTNpXutHEdRi

**Comment by mf-code** [comment]
[6034] - 6UBZqsn6iFPT

**Comment by mf-code** [comment]
[6034] - vvXdkanR49Fp

**Comment by mf-code** [comment]
[6034] - CZHFASG7NCJP

**Comment by mf-code** [comment]
[6034] - YcHlXZK6vcW0

**Comment by mf-code** [comment]
[6034] - kPgbxy52KuhY

**Comment by mf-code** [comment]
[6034] - knxseQHHu8VS

**Comment by mf-code** [comment]
[6034] - Xhgg6uZdMfIS

**Comment by mf-code** [comment]
[6034] - 0D8PiGF8bmKq

**Comment by mf-code** [comment]
[6034] - GunnRaGcjnRd

**Comment by mf-code** [comment]
[6034] - 20gjJMQbonJ5

**Pull request merged**
