### PR TITLE
2389 Tab Bar tests

### PR DESCRIPTION
**Pull request by Olesya24**

### CODE REVIEW

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/elements/common/app/android/TabBar.java  1
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/asserts/TabBarAssert.java  1
- jdi-light-mobile-tests/src/test/java/nativeapp_android/tests/TabBarTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6418409&bid=20794639)

**Review by alexarm — APPROVED** [review]

**Comment by mf-code** [comment]
[6423] - L91tcDW0vu5H

**Comment by mf-code** [comment]
[6423] - EnqW7Z56K7tf

**Comment by mf-code** [comment]
[6423] - hI3fFFvJAWtv

**Comment by mf-code** [comment]
[6423] - TwZW4XCTPIdJ

**Comment by mf-code** [comment]
[6423] - 1KQqv4mHgNI5

**Comment by mf-code** [comment]
[6423] - Nw51Qa0lUy9s

**Comment by mf-code** [comment]
[6423] - jmlQNECqTONy

**Comment by mf-code** [comment]
[6423] -

**Comment by mf-code** [comment]
[6423] - JQXnFBMtRuVK

**Comment by mf-code** [comment]
[6423] - 5baw2b8sv9rE

**Comment by mf-code** [comment]
[6423] - VwjRKz5cQgv2

**Comment by mf-code** [comment]
[6423] - FfNnti89c80W

**Comment by mf-code** [comment]
[6423] - Ly9blDpFTmGa

**Comment by mf-code** [comment]
[6423] - WWZYQVuAbcow

**Comment by mf-code** [comment]
[6423] - dPa8NNHYr9uf

**Comment by mf-code** [comment]
[6423] - 6m6rakWQZHu5

**Comment by mf-code** [comment]
[6423] - RcSngSAN41LH

**Comment by mf-code** [comment]
[6423] - XcGE9nrMzFBp

**Comment by mf-code** [comment]
[6423] - openjdk8 - Allure report on Netlify: https://5fb40913a6dbdd4c08b06aff--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6423] - openjdk10 - Allure report on Netlify: https://5fb409f585325c69175ffa54--musing-swartz-6fc060.netlify.app

**Pull request merged**
