### PR TITLE
2057::CRONJOB_COMMENTS_PR is now Travis-level environment variable

### PR DESCRIPTION
**Pull request by clockworkbanana**

### CODE REVIEW

**Comment by mf-code** [comment]
[5608] - yvjoJB7e

**Comment by mf-code** [comment]
[5608] - qmpdrg0h

**Comment by mf-code** [comment]
[5608] - 4E33CNRz

**Comment by mf-code** [comment]
[5608] - C3vkYRnb

**Comment by mf-code** [comment]
[5608] - bjBXjlzs

**Comment by mf-code** [comment]
[5608] - openjdk8 - Allure report on Netlify: https://5ee1ec91bf5617d01735743f--musing-swartz-6fc060.netlify.app

**Comment by clockworkbanana** [comment]
Different PR would be created instead

**Pull request closed without merging**
