### PR TITLE
Added comments to related resources.

### PR DESCRIPTION
**Pull request by gbuh**
Added comments to related resources.

### CODE REVIEW

**Comment by mf-code** [comment]
[6047] - gCr96ADD6Bbo

**Comment by mf-code** [comment]
[6047] - 1AexOr5DQRfa

**Comment by mf-code** [comment]
[6047] - PqfQGZlsXHja

**Comment by mf-code** [comment]
[6047] - mwZBaVajvfjA

**Comment by mf-code** [comment]
[6047] - wa0L03TDqczs

**Comment by mf-code** [comment]
[6047] - vVknZcZMshfW

**Comment by mf-code** [comment]
[6047] - EN3RvzgWl6dF

**Comment by mf-code** [comment]
[6047] - CkGz9rWeCUvf

**Comment by mf-code** [comment]
[6047] - Z6kBY1wdbZnu

**Comment by mf-code** [comment]
[6047] - AgparV7YqhMj

**Comment by mf-code** [comment]
[6047] - dS2jd8yD7aT3

**Review by AlexSofft — APPROVED** [review]

**Comment by mf-code** [comment]
[6047] - BsIgo4sHcsAo

**Comment by mf-code** [comment]
[6047] - HKNWBP8XcbCO

**Comment by mf-code** [comment]
[6047] - 0Dx4JrrXm39F

**Comment by mf-code** [comment]
[6047] - UHOXAs3E2iYQ

**Comment by mf-code** [comment]
[6047] - Bs7ARtY9U26z

**Comment by mf-code** [comment]
[6047] - DcxWAUXXgNQu

**Comment by mf-code** [comment]
[6047] - eSoDbqQ3xs73

**Comment by mf-code** [comment]
[6047] - openjdk8 - Allure report on Netlify: https://5f5798b34c5ada2dd3bbb1f4--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6047] - openjdk10 - Allure report on Netlify: https://5f5799b1d127bd2990c06991--musing-swartz-6fc060.netlify.app

**Pull request merged**
