### PR TITLE
#2301 added iOS Tab bar

### PR DESCRIPTION
**Pull request by alyatertyshnikova**

### CODE REVIEW

**Comment by mf-code** [comment]
[6194] - xMAnit8qc19M

**Comment by mf-code** [comment]
[6194] - gu8bf7KWZMMJ

**Comment by mf-code** [comment]
[6194] - idyIQgD52020

**Comment by mf-code** [comment]
[6194] - uKryA0cUSjkE

**Comment by mf-code** [comment]
[6194] - MGNPDoFWYNMB

**Comment by mf-code** [comment]
[6194] - 6N0oTjBYYneI

**Comment by mf-code** [comment]
[6194] - cr7idrBLR6uo

**Comment by mf-code** [comment]
[6194] - qouEmv4o6oKG

**Comment by mf-code** [comment]
[6194] - AzG3P9efHcoH

**Comment by mf-code** [comment]
[6194] - j0jWT8QfPr2C

**Comment by mf-code** [comment]
[6194] - 1CAUcT5Yi49Q

**Comment by mf-code** [comment]
[6194] - 9SUt1R6oa3GT

**Comment by mf-code** [comment]
[6194] - 8ImaItM1I9sg

**Comment by mf-code** [comment]
[6194] - K2OYL4yZWbaU

**Comment by mf-code** [comment]
[6194] - ZtqZgBTV8ZlI

**Comment by mf-code** [comment]
[6194] - q6HUAkKwuY9k

**Comment by mf-code** [comment]
[6194] - GXALEe7yPJaJ

**Comment by mf-code** [comment]
[6194] - NX52S1kep0oe

**Comment by mf-code** [comment]
[6225] - N7V5Wrm6uZZ6

**Comment by mf-code** [comment]
[6225] - AF5k0HFFxDi5

**Comment by mf-code** [comment]
[6225] - JRXDaYEIIUEv

**Comment by mf-code** [comment]
[6225] - QsCl6SQur1PF

**Comment by mf-code** [comment]
[6225] - Y9eh914OOBVl

**Comment by mf-code** [comment]
[6225] - IknDMrhk5G7p

**Comment by mf-code** [comment]
[6225] - 6dWImWUMvTlN

**Comment by mf-code** [comment]
[6225] - SUYk4Iex4Hby

**Comment by mf-code** [comment]
[6225] - XDw3DOrcY6IY

**Comment by mf-code** [comment]
[6225] - ugF0MB8h6fPf

**Comment by mf-code** [comment]
[6225] - Gv1wIzEEyhIN

**Comment by mf-code** [comment]
[6225] - 7dW8BjkDndjO

**Comment by mf-code** [comment]
[6225] - uVyU6wHK7Cgj

**Comment by mf-code** [comment]
[6225] - 7jLhhyVdEt2n

**Comment by mf-code** [comment]
[6225] - F4jMP9KZnMUM

**Comment by mf-code** [comment]
[6225] - SB8dpZvZzAj7

**Comment by mf-code** [comment]
[6225] - JbJWHY5ko4af

**Comment by mf-code** [comment]
[6225] - PsZi3tZlroTs

**Comment by mf-code** [comment]
[6263] - ZF28e1I9Fljf

**Comment by mf-code** [comment]
[6263] - vzwi2DYVcuVN

**Comment by mf-code** [comment]
[6263] - O6jA8It0OyEt

**Comment by mf-code** [comment]
[6263] - 2Q9yfUpi9yQh

**Comment by mf-code** [comment]
[6263] - 40AvAxSFQG59

**Comment by mf-code** [comment]
[6263] - EIWZtyVJokmV

**Comment by mf-code** [comment]
[6263] - U7n6Lr8bfcDN

**Comment by mf-code** [comment]
[6263] - nzy53fcQHF7F

**Comment by mf-code** [comment]
[6263] - zBwI7aXAmqhv

**Comment by mf-code** [comment]
[6263] - cbk8PgaQdDFP

**Comment by mf-code** [comment]
[6263] - haEuk2StFTco

**Comment by mf-code** [comment]
[6263] - 7saSlGwd29qo

**Comment by mf-code** [comment]
[6263] - NpDi1LZKSnlx

**Comment by mf-code** [comment]
[6263] - qY6nBxkdxv1c

**Comment by mf-code** [comment]
[6263] - ZC6Hi2YTezxl

**Comment by mf-code** [comment]
[6263] - ClrxzVGqW697

**Comment by mf-code** [comment]
[6263] - wV8luKLx7yDy

**Comment by mf-code** [comment]
[6263] - uSYlgPrW8cWq

**Comment by mf-code** [comment]
[6263] - openjdk8 - Allure report on Netlify: https://5f843f76e6479b93583df18a--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6263] - openjdk10 - Allure report on Netlify: https://5f844058a642c9a6dffb1ece--musing-swartz-6fc060.netlify.app

**Review by alexarm — APPROVED** [review]

**Pull request merged**
