### PR TITLE
Investigate and fix angular tests failures for jdk 11, 12, 13 #2072

### PR DESCRIPTION
**Pull request by Innokentiy945**

### CODE REVIEW

**Comment by mf-code** [comment]
[6307] - pPdplwkvIsoy

**Comment by mf-code** [comment]
[6307] - gEC8ZMPak21R

**Comment by mf-code** [comment]
[6307] - 4zgugnyc3d50

**Comment by mf-code** [comment]
[6307] - n69INkMEGCmD

**Comment by mf-code** [comment]
[6307] - 6CHbIVPkyjpK

**Comment by mf-code** [comment]
[6307] - 3xTGBrSqAg9B

**Comment by mf-code** [comment]
[6307] - wyyfQAFMYRKn

**Comment by mf-code** [comment]
[6307] - Fke4mvaQT1KB

**Comment by mf-code** [comment]
[6307] - TDzrRzdDvHEC

**Comment by mf-code** [comment]
[6307] - eEQNB8FLIk40

**Comment by mf-code** [comment]
[6307] -

**Comment by mf-code** [comment]
[6307] - HX2roqajTe22

**Comment by mf-code** [comment]
[6307] - xKGjqtf4AdBx

**Comment by mf-code** [comment]
[6307] - eW8CT9ENn4U4

**Comment by mf-code** [comment]
[6336] - 54OXhFn7OGBi

**Comment by mf-code** [comment]
[6336] - truM8977zb1Y

**Comment by mf-code** [comment]
[6336] - am4OX33lrrAW

**Comment by mf-code** [comment]
[6336] - XfoyljXqmS0v

**Comment by mf-code** [comment]
[6336] - pquysuEglTTJ

**Comment by mf-code** [comment]
[6336] - P3AyJyQbk40s

**Comment by mf-code** [comment]
[6336] - K9NWVSaeQ6Pn

**Comment by mf-code** [comment]
[6336] - gtkN3ftMC8K7

**Comment by mf-code** [comment]
[6336] - Afgthy6sY9P7

**Comment by mf-code** [comment]
[6336] - gE9fbtHfiI6p

**Comment by mf-code** [comment]
[6336] - lm9UkJTIs2ek

**Comment by mf-code** [comment]
[6336] - 3kgevZSCMMHu

**Comment by mf-code** [comment]
[6336] - jwilOcndoy9y

**Comment by mf-code** [comment]
[6336] - pB0faEkSPTya

**Comment by mf-code** [comment]
[6336] - 1mRvuOC98KJk

**Comment by mf-code** [comment]
[6336] - X4ZHzWjNpu5P

**Comment by mf-code** [comment]
[6336] - 943k316rAHjA

**Comment by mf-code** [comment]
[6336] - AblpmwCAti4k

**Comment by mf-code** [comment]
[6336] - mO669O7PB9qJ

**Comment by mf-code** [comment]
[6336] - 8ukWXLHKepQs

**Comment by mf-code** [comment]
[6336] - R8KMnmeoTYXO

**Comment by mf-code** [comment]
[6336] - 9HDIsM0kxOzQ

**Comment by mf-code** [comment]
[6336] - lyP5X5shxvn3

**Comment by mf-code** [comment]
[6336] - 2yOAoZXR9Psd

**Comment by mf-code** [comment]
[6336] - pBuSySJhSn52

**Comment by mf-code** [comment]
[6336] - 9hOpMxXpl15i

**Comment by mf-code** [comment]
[6336] - KeXJhN6OD1Ai

**Comment by mf-code** [comment]
[6336] - mOj6r4wqXJVk

**Comment by Innokentiy945** [comment]
Useless task. Closed.

**Pull request closed without merging**
