### PR TITLE
2047 merge angular into master (second try)

### PR DESCRIPTION
**Pull request by AkioFaris**
A second try due to Codacy's error "Error getting analysis status for this pull request" https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=5606287

### CODE REVIEW

**Comment by mf-code** [comment]
[5474] - kCdFwxBG

**Comment by mf-code** [comment]
[5474] - uzmucn3L

**Comment by mf-code** [comment]
[5474] - 6BryXvY9

**Comment by mf-code** [comment]
[5474] - CDqOd6MN

**Comment by mf-code** [comment]
[5474] - 4Pm82DDN

**Comment by mf-code** [comment]
[5474] - 7sEb0sND

**Comment by mf-code** [comment]
[5474] - Allure report on Netlify: https://5ed2ac461c8448354b327a0a--musing-swartz-6fc060.netlify.app

**Comment by RomanIovlev** [comment]
Let's work in first one

**Pull request closed without merging**
