### PR TITLE
2048:Multiple JDKs for 2047-merge-unrelated-to-angular-tests branch

### PR DESCRIPTION
**Pull request by clockworkbanana**

### CODE REVIEW

**Comment by mf-code** [comment]
[5498] - 4CAQ2iOd

**Comment by mf-code** [comment]
[5498] - 5LqKeYYT

**Comment by mf-code** [comment]
[5498] - 3aizR77u

**Comment by mf-code** [comment]
[5498] - DcUMHKkJ

**Comment by mf-code** [comment]
[5498] - ufrO882q

**Comment by mf-code** [comment]
[5498] - 0sKZiTGA

**Comment by mf-code** [comment]
[5498] - ICgzLLlA

**Comment by mf-code** [comment]
[5498] - LXHWLB9q

**Comment by mf-code** [comment]
[5498] - NuR3twin

**Comment by mf-code** [comment]
[5498] - gZtbYj12

**Comment by mf-code** [comment]
[5498] - PPlY2IQo

**Comment by mf-code** [comment]
[5498] - z0Tnfj5L

**Comment by mf-code** [comment]
[5498] - AQDgG3k1

**Comment by mf-code** [comment]
[5498] - cFXYF7GA

**Comment by mf-code** [comment]
[5498] - PImnhUX7

**Comment by mf-code** [comment]
[5516] - lnE2jcCz

**Comment by mf-code** [comment]
[5516] - gMItz6oN

**Comment by mf-code** [comment]
[5516] - zJiNbQr0

**Comment by mf-code** [comment]
[5516] - er98i96O

**Comment by mf-code** [comment]
[5516] - SZITkfpc

**Comment by mf-code** [comment]
[5516] - QO54kJaS

**Comment by mf-code** [comment]
[5516] - YJZmfiqG

**Comment by mf-code** [comment]
[5516] - GijjbBVW

**Comment by mf-code** [comment]
[5516] - YXiYGClF

**Comment by mf-code** [comment]
[5516] -

**Comment by mf-code** [comment]
[5516] - drGMVw2p

**Comment by mf-code** [comment]
[5516] - Bhxxz0xd

**Comment by mf-code** [comment]
[5516] - e0W05548

**Comment by mf-code** [comment]
[5516] - QzNOrAwc

**Comment by mf-code** [comment]
[5516] - ZXLOIc8m

**Comment by mf-code** [comment]
[5521] - Z7HpO9W5

**Comment by mf-code** [comment]
[5521] - KlhxRs3Z

**Comment by mf-code** [comment]
[5521] - xsqtErLE

**Comment by mf-code** [comment]
[5521] - 3bkFaZlh

**Comment by mf-code** [comment]
[5521] - kP9WMTK5

**Comment by mf-code** [comment]
[5521] - 3ew1pmTu

**Comment by mf-code** [comment]
[5521] - iLZx91OF

**Comment by mf-code** [comment]
[5521] - Nev4nA8P

**Comment by mf-code** [comment]
[5521] - cTY5lQOi

**Comment by mf-code** [comment]
[5521] - 8GrMxXpx

**Comment by mf-code** [comment]
[5521] - xOUMrZrx

**Comment by mf-code** [comment]
[5521] - DE96bNzq

**Comment by mf-code** [comment]
[5521] - eXmrdkBO

**Comment by mf-code** [comment]
[5521] - uCUfvlSk

**Comment by clockworkbanana** [comment]
This PR is no longer needed.
See: https://github.com/jdi-testing/jdi-light/pull/2065

**Comment by mf-code** [comment]
[5585] - 9obc69K6

**Comment by mf-code** [comment]
[5585] - i6XT18Bd

**Comment by mf-code** [comment]
[5585] - IORNiQ03

**Comment by mf-code** [comment]
[5585] - 90UzvI2q

**Comment by mf-code** [comment]
[5585] - i1BqgEGN

**Comment by mf-code** [comment]
[5585] - prB3MqBj

**Comment by mf-code** [comment]
[5585] - openjdk8 - Allure report on Netlify: https://5edec4e82c3f111b9b7feecf--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5585] - openjdk9 - Allure report on Netlify: https://5edec4f59159fe181be0357d--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5585] - openjdk10 - Allure report on Netlify: https://5edec5012c3f11437a7fee5e--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5585] - openjdk11 - Allure report on Netlify: https://5edec550ee6b522ad705ff2e--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5585] - openjdk12 - Allure report on Netlify: https://5edec55d2c3f11efae7ff5dd--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5585] - openjdk13 - Allure report on Netlify: https://5edec569eca70bad7724a84b--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5587] - aS53jaRG

**Comment by mf-code** [comment]
[5587] - vabD9WnV

**Comment by mf-code** [comment]
[5587] - openjdk8 - Allure report on Netlify: https://5edf40d27ea72bf7691dad5c--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5587] - openjdk9 - Allure report on Netlify: https://5edf40de11e6fca3bb04039a--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5587] - openjdk10 - Allure report on Netlify: https://5edf40e8eab36009802f8097--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5587] - openjdk11 - Allure report on Netlify: https://5edf40eeeab360ab902f8555--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5587] - openjdk12 - Allure report on Netlify: https://5edf40f4e6b3e399bb1a0248--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5587] - openjdk13 - Allure report on Netlify: https://5edf40fad13254456c49c506--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5588] - I8cgRXQX

**Comment by mf-code** [comment]
[5588] - khS9xFLf

**Comment by mf-code** [comment]
[5588] - openjdk8 - Allure report on Netlify: https://5edf53a07ea72bb3071db2d6--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5588] - openjdk9 - Allure report on Netlify: https://5edf53ae2f7382e241cdab9e--musing-swartz-6fc060.netlify.app

**Pull request closed without merging**
