### PR TITLE
Adjusted LoginForm and FormsTests classes.

### PR DESCRIPTION
**Pull request by gbuh**
Adjusted LoginForm and FormsTests classes.

### CODE REVIEW

**Comment by mf-code** [comment]
[6115] - hBV8UHxA4mX8

**Comment by mf-code** [comment]
[6115] - oKrnmZtV8hy2

**Comment by mf-code** [comment]
[6115] - ZzjJtvVakvdW

**Comment by mf-code** [comment]
[6115] - LgQd2NOSJK4b

**Comment by mf-code** [comment]
[6115] - Ae8xBrhOFYPY

**Comment by mf-code** [comment]
[6115] - uJcV0agHqH7f

**Comment by mf-code** [comment]
[6115] - J8MpdlfQebrO

**Comment by mf-code** [comment]
[6115] - wlvoKDgja91H

**Comment by mf-code** [comment]
[6115] - RBnXYIay0Ues

**Comment by mf-code** [comment]
[6115] - ohzPeMBIgS6o

**Comment by mf-code** [comment]
[6115] - SCr8E4XADZ53

**Comment by mf-code** [comment]
[6115] - Ja7ne0sipmNG

**Comment by mf-code** [comment]
[6115] - LHlarWZ1kx69

**Comment by mf-code** [comment]
[6115] - NmyMLWXR0NTr

**Comment by mf-code** [comment]
[6115] - hPrs4m1Z8roI

**Comment by mf-code** [comment]
[6115] - wKf3f1s9RUWx

**Comment by mf-code** [comment]
[6115] - Hw7Dlv4fC5Qk

**Comment by mf-code** [comment]
[6115] - yo2QhcBTLcMk

**Comment by mf-code** [comment]
[6115] - openjdk8 - Allure report on Netlify: https://5f61dc9dce8eba681b4b5606--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6115] - openjdk10 - Allure report on Netlify: https://5f61dd63de76b75f0ea5d896--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6123] - BNomMul2GoiR

**Comment by mf-code** [comment]
[6123] - vmpfHTTdtyXJ

**Comment by mf-code** [comment]
[6123] - 1rfx0nwlxO6s

**Comment by mf-code** [comment]
[6123] - 8fNx92yW2ZiS

**Comment by mf-code** [comment]
[6123] - U9tkMCUL74Ma

**Comment by mf-code** [comment]
[6123] - pQQXWyAsG3ez

**Comment by mf-code** [comment]
[6123] - in5PRo3r9tnZ

**Comment by mf-code** [comment]
[6123] - ANBLKCVrriBA

**Comment by mf-code** [comment]
[6123] - nRfC8gnzRpPW

**Comment by mf-code** [comment]
[6123] - sGmLYdizGWyv

**Comment by mf-code** [comment]
[6123] - HivX5IRERBJS

**Comment by mf-code** [comment]
[6123] - 37n7CaYje0jC

**Comment by mf-code** [comment]
[6123] - MSCeJix7gE6V

**Comment by mf-code** [comment]
[6123] - dU8cQGs5873l

**Comment by mf-code** [comment]
[6123] - RkdusWmhYhYM

**Comment by mf-code** [comment]
[6123] - Ugl4T7gdCQzB

**Comment by mf-code** [comment]
[6123] - G0E2JehoXG2M

**Comment by mf-code** [comment]
[6124] - KSXaU5BLT7dO

**Comment by mf-code** [comment]
[6124] - LGg9CI6xxR5j

**Comment by mf-code** [comment]
[6124] - 0HVgiLHh8hcc

**Comment by mf-code** [comment]
[6124] - QWJhfFzFMpDN

**Comment by mf-code** [comment]
[6123] - openjdk8 - Allure report on Netlify: https://5f625de9f302851bcad86248--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6123] - openjdk10 - Allure report on Netlify: https://5f625ea46fed5c29fee1728c--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6124] - 50ILI2benoIX

**Comment by mf-code** [comment]
[6124] - gmoOOxiLgPuN

**Comment by mf-code** [comment]
[6124] - 8VSpmr1cypoF

**Comment by mf-code** [comment]
[6124] - hHT8Mp8aLQNA

**Comment by mf-code** [comment]
[6124] - n7Dxn5N0xGXf

**Comment by mf-code** [comment]
[6124] - cxBpUZ1viLUu

**Comment by mf-code** [comment]
[6124] - 1HVAxQptCGg5

**Comment by mf-code** [comment]
[6124] - T6WlQEBO5Nrc

**Comment by mf-code** [comment]
[6124] - egXG9KdIoNDG

**Comment by mf-code** [comment]
[6124] - mR3Rn8ekspLx

**Comment by mf-code** [comment]
[6124] - 8A3NXhF8EUa6

**Comment by mf-code** [comment]
[6124] - lGJtipswoRhE

**Comment by mf-code** [comment]
[6124] - E9py46LlbZ4V

**Comment by mf-code** [comment]
[6124] - JuqOV9wUoRZj

**Comment by mf-code** [comment]
[6124] - openjdk8 - Allure report on Netlify: https://5f626fb210604333dbd3d71d--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6124] - openjdk10 - Allure report on Netlify: https://5f6270869448354410ff9269--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6131] - vlMbIMt79r0s

**Comment by mf-code** [comment]
[6131] - WkK5KNigojyL

**Comment by mf-code** [comment]
[6131] - Omr75jFDkWTy

**Comment by mf-code** [comment]
[6131] - KARMe89UOXCn

**Comment by mf-code** [comment]
[6131] - zoXkT2tDPsd3

**Comment by mf-code** [comment]
[6131] - PJGG4Ywh70vQ

**Comment by mf-code** [comment]
[6131] - foGOoXH8QuFe

**Comment by mf-code** [comment]
[6131] - cW6CIirAx4cb

**Comment by mf-code** [comment]
[6131] - 9M5a0y1DgMgm

**Comment by mf-code** [comment]
[6131] - twz4BwlI1ygD

**Comment by mf-code** [comment]
[6131] - CAwusrR3fehc

**Comment by mf-code** [comment]
[6131] - FAbIcswiknN7

**Comment by mf-code** [comment]
[6131] - IYk7WfSakvGb

**Comment by mf-code** [comment]
[6131] - c8KMAyZmISWe

**Comment by mf-code** [comment]
[6131] - NiWYXjBjpazX

**Comment by mf-code** [comment]
[6131] - mNTRnFMaqTOg

**Comment by mf-code** [comment]
[6132] - 9vtmSNRKzZ2S

**Comment by mf-code** [comment]
[6132] - nEImLzSVYzTu

**Comment by mf-code** [comment]
[6131] - bkzjx6vkFLnY

**Comment by mf-code** [comment]
[6131] - ZZ3DfT5TMbUa

**Comment by mf-code** [comment]
[6132] - Q0HLmxmpBAfh

**Comment by mf-code** [comment]
[6132] - Wg8UlM9jy1A6

**Comment by mf-code** [comment]
[6131] - openjdk8 - Allure report on Netlify: https://5f634e9c924ff0ba1189f5b9--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6132] - XNpNDeMHrPcR

**Comment by mf-code** [comment]
[6132] - WzAAeSltCWyS

**Comment by mf-code** [comment]
[6131] - openjdk10 - Allure report on Netlify: https://5f634f706041ee762adc4032--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6132] - O4rcBbLHHpF6

**Comment by mf-code** [comment]
[6132] - xWQOq8CBkum8

**Comment by mf-code** [comment]
[6132] - Gp2frw10nvxz

**Comment by mf-code** [comment]
[6132] - E59ziM6KRgyA

**Comment by mf-code** [comment]
[6132] - eKBNesDOOhaW

**Comment by mf-code** [comment]
[6132] - h2mc8gxnNLwA

**Comment by mf-code** [comment]
[6132] - 5ak1J7kfbhyY

**Comment by mf-code** [comment]
[6132] - 9eRP1FjKxpw3

**Comment by mf-code** [comment]
[6132] - YEge8P0j0bGw

**Comment by mf-code** [comment]
[6132] - rAhyqQ8clUFh

**Comment by mf-code** [comment]
[6132] - kxdAAOMl5oaL

**Comment by mf-code** [comment]
[6133] - PlqawZq8J5OX

**Comment by mf-code** [comment]
[6132] - I3HlmpgThP7Y

**Comment by mf-code** [comment]
[6133] - ZHxZC3ieqW4G

**Comment by mf-code** [comment]
[6133] - cUd2Bf4jJ0si

**Comment by mf-code** [comment]
[6133] - xnVuchew35lh

**Comment by mf-code** [comment]
[6132] - openjdk8 - Allure report on Netlify: https://5f635b62106043a7e8d3cbfc--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6133] - YfyCQi6WmCiR

**Comment by mf-code** [comment]
[6132] - openjdk10 - Allure report on Netlify: https://5f635c31e55d1fe45810d1a5--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6133] - T2HAemjqUqqG

**Comment by mf-code** [comment]
[6133] - xwnA0zUfw8p5

**Comment by mf-code** [comment]
[6133] - FP761P0LOaWw

**Comment by mf-code** [comment]
[6133] - ugPZD5lbVKrm

**Comment by mf-code** [comment]
[6133] - CGirVfhs3PYU

**Comment by mf-code** [comment]
[6133] - FiZfc30RwI9g

**Comment by mf-code** [comment]
[6133] - qAt4zgAelADQ

**Comment by mf-code** [comment]
[6133] - RoeavOe7pWHm

**Comment by mf-code** [comment]
[6133] - lb21ATvfXXjT

**Comment by mf-code** [comment]
[6133] - 3kZCfSDAXY6C

**Comment by mf-code** [comment]
[6133] - 6feCbV3Q1M40

**Comment by mf-code** [comment]
[6133] - 3UPlJbWdG18k

**Comment by mf-code** [comment]
[6133] - Oo3RamhzdCZt

**Comment by mf-code** [comment]
[6133] - openjdk8 - Allure report on Netlify: https://5f6368f718a0780136339e7c--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6133] - openjdk10 - Allure report on Netlify: https://5f636a1018a078010a33d87c--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6148] - fJfNTx721VSh

**Comment by mf-code** [comment]
[6148] - t4bwGcSkmR8Z

**Comment by mf-code** [comment]
[6148] - 5IwJPtWyVUcl

**Comment by mf-code** [comment]
[6148] - 0dSmx1BLHIru

**Comment by mf-code** [comment]
[6148] - Qq49Va3KmOSH

**Comment by mf-code** [comment]
[6148] - 3tLz3WZST22f

**Comment by mf-code** [comment]
[6148] - LerfyCsIm56W

**Comment by mf-code** [comment]
[6148] - pzz8JoY6CmOs

**Comment by mf-code** [comment]
[6148] - r4NkEecgirbv

**Comment by mf-code** [comment]
[6148] - AGDUL1xZMZgO

**Comment by mf-code** [comment]
[6148] - QGQiJ80DknrY

**Comment by mf-code** [comment]
[6148] - IF655RAdAZVU

**Comment by mf-code** [comment]
[6148] - IWh1ma10Axum

**Comment by mf-code** [comment]
[6148] - 41l6QUlY2LlX

**Comment by mf-code** [comment]
[6148] - qjnNmytMK0UO

**Comment by mf-code** [comment]
[6148] - Mda7WCQHj1P1

**Comment by mf-code** [comment]
[6148] - 8DQrlZrFfRvc

**Comment by mf-code** [comment]
[6148] - openjdk8 - Allure report on Netlify: https://5f63cdb6d2dd5855c4cb042c--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6148] - openjdk10 - Allure report on Netlify: https://5f63cff9ac9e2e543494f5bd--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6151] - LgV2v5kKTgd7

**Comment by mf-code** [comment]
[6151] - l4r0A4OsFgCu

**Comment by mf-code** [comment]
[6151] - 4mpJfsc6pXGr

**Comment by mf-code** [comment]
[6151] - lzkwRbMPV7sq

**Comment by mf-code** [comment]
[6151] - g8Pg73dgjH0w

**Comment by mf-code** [comment]
[6151] - U24uVgXbvmCU

**Comment by mf-code** [comment]
[6151] - ZkMSSuk4Wrae

**Comment by mf-code** [comment]
[6151] - l65djTzeC380

**Comment by mf-code** [comment]
[6151] - 6L30moxwtp9C

**Comment by mf-code** [comment]
[6151] - 1bzJI0LwS5W0

**Comment by mf-code** [comment]
[6151] - rcwd5dQypuSN

**Comment by mf-code** [comment]
[6151] - zmlRA7pgEQnB

**Comment by mf-code** [comment]
[6151] - 1bDgeARZ9YTg

**Comment by mf-code** [comment]
[6151] - 12HWuuC8TidS

**Comment by mf-code** [comment]
[6151] - XJ349GV4sHTS

**Comment by mf-code** [comment]
[6151] - lF1933Vfmjam

**Comment by mf-code** [comment]
[6151] - vQOUzNZrfHDd

**Comment by mf-code** [comment]
[6152] - rGBrV1Ayv24o

**Comment by mf-code** [comment]
[6152] - gwsgUmHeGHFt

**Comment by mf-code** [comment]
[6152] - oYKg8x7hpNYt

**Comment by mf-code** [comment]
[6151] - 3bqBm8P1Bf4L

**Comment by mf-code** [comment]
[6152] - bVt3aw6OJ2rX

**Comment by mf-code** [comment]
[6152] - 37hCHXSzVAMP

**Comment by mf-code** [comment]
[6152] - HkQUewInNIN9

**Comment by mf-code** [comment]
[6151] - openjdk8 - Allure report on Netlify: https://5f646f66cde3a654695d5801--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6151] - openjdk10 - Allure report on Netlify: https://5f647063d3538f3372d957a0--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6152] - tEjxubMQxgcG

**Comment by mf-code** [comment]
[6152] - AyEAL3aTsAdr

**Review by AlexSofft — APPROVED** [review]

**Comment by mf-code** [comment]
[6152] - DHqRjq1GwEAr

**Comment by mf-code** [comment]
[6152] - uQ7YxdTGxEUI

**Comment by mf-code** [comment]
[6152] - VQhGALh4g5aX

**Comment by mf-code** [comment]
[6152] - XHwKWfvquolW

**Comment by mf-code** [comment]
[6152] - w47B7rhtOq0q

**Comment by mf-code** [comment]
[6152] - apdCdbxTV0T8

**Comment by mf-code** [comment]
[6152] - DBlWqcRLTAY3

**Comment by mf-code** [comment]
[6152] - Tj21Bt33zyRf

**Comment by mf-code** [comment]
[6152] - LkimE2sGbGYO

**Comment by mf-code** [comment]
[6152] - aHzxtcIRlF0A

**Comment by mf-code** [comment]
[6154] - X1g1HNQV5T5Y

**Comment by mf-code** [comment]
[6154] - gbnm5DzuntFS

**Comment by mf-code** [comment]
[6154] - uaGOpgCcbzif

**Comment by mf-code** [comment]
[6152] - openjdk8 - Allure report on Netlify: https://5f647b3ed2dd588309cb0200--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6154] - dQUWGF8WNC7S

**Comment by mf-code** [comment]
[6152] - openjdk10 - Allure report on Netlify: https://5f647c14e2535b76da7584ad--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6154] - Bwdyiu5gumkY

**Comment by mf-code** [comment]
[6154] - EdvFb9fUMfE5

**Comment by mf-code** [comment]
[6154] - Ixj8Ere2xrIv

**Comment by mf-code** [comment]
[6154] - iJtOwubhkNYU

**Comment by mf-code** [comment]
[6154] - mBnFX5wZNccT

**Comment by mf-code** [comment]
[6154] - BzcyiWMGiU6X

**Comment by mf-code** [comment]
[6154] - x1bPz8qInxWd

**Comment by mf-code** [comment]
[6154] - Is7jsWxNw2dh

**Comment by mf-code** [comment]
[6154] - 0E3DA9umwBgJ

**Comment by mf-code** [comment]
[6154] - Opj4Kik5nD3A

**Comment by mf-code** [comment]
[6154] - zif7xXMS5sxg

**Comment by mf-code** [comment]
[6154] - v8ya26Nas9uA

**Comment by mf-code** [comment]
[6154] - 4bMCoITzFL40

**Comment by mf-code** [comment]
[6154] - 7Xqk9njwxZjO

**Comment by mf-code** [comment]
[6154] - openjdk8 - Allure report on Netlify: https://5f6488fc3c135a5483c05f75--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6154] - openjdk10 - Allure report on Netlify: https://5f648a17dabbdf556441963b--musing-swartz-6fc060.netlify.app

**Pull request closed without merging**
