### PR TITLE
Renamed fields in Contacts class according to renamed UI fields

### PR DESCRIPTION
**Pull request by SChepinog**
#1543

### CODE REVIEW

**Comment by OBraunEPAM** [comment]
Review is in progress.

**Comment by SChepinog** [comment]
Tests were passed and all fields were filled

**Comment by mf-code** [comment]
[4022] - https://transfer.sh/O2p1e/jdi-performance.tar.gz

**Comment by mf-code** [comment]
[4022] - https://transfer.sh/CKl3r/jdi-light-html-tests.tar.gz

**Comment by mf-code** [comment]
[4022] - https://transfer.sh/5jprW/jdi-light-examples.tar.gz

**Comment by mf-code** [comment]
[4022] - Allure report on Netlify: https://5df2286a67ef71cbaf299dd8--musing-swartz-6fc060.netlify.com

**Pull request merged**
