### PR TITLE
#2485 created testng.xml for android tests

### PR DESCRIPTION
**Pull request by AleksandraMalygina**

### CODE REVIEW

**Comment by mf-code** [comment]
[6400] - LIan5h59Y7JY

**Comment by mf-code** [comment]
[6400] - lDxBpRRhCC9T

**Comment by mf-code** [comment]
[6400] - FzOQPqgEMLoq

**Comment by mf-code** [comment]
[6400] - olOk57tOYkX8

**Comment by mf-code** [comment]
[6400] - S1zny4u7J58M

**Comment by mf-code** [comment]
[6400] - WNuLrvSZDyQx

**Comment by mf-code** [comment]
[6400] - ja61ohbCv39E

**Comment by mf-code** [comment]
[6400] - AbV7MiEQ8Vka

**Comment by mf-code** [comment]
[6400] - fdnEmgzNRfy0

**Comment by mf-code** [comment]
[6400] - Yop3QLwBz9LG

**Comment by mf-code** [comment]
[6400] - hT8vbQgSfjBO

**Comment by mf-code** [comment]
[6400] - boVwXuPGhn8g

**Comment by mf-code** [comment]
[6400] - t9Mmmy9XSt6w

**Comment by mf-code** [comment]
[6400] - cajtg99hTEs6

**Comment by mf-code** [comment]
[6400] - gt2VHfExhq2d

**Comment by mf-code** [comment]
[6400] - NEXJ6ir8IsOL

**Comment by mf-code** [comment]
[6400] - P2fraQcXmJRL

**Comment by mf-code** [comment]
[6400] - jaPwlkRfQzr4

**Comment by mf-code** [comment]
[6400] - openjdk8 - Allure report on Netlify: https://5fa9185da3d8638f922032c5--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6400] - openjdk10 - Allure report on Netlify: https://5fa9193588ec6942879bc9e1--musing-swartz-6fc060.netlify.app

**Review by alexarm — APPROVED** [review]

**Pull request merged**
