### PR TITLE
Bottomsheet

### PR DESCRIPTION
**Pull request by vsevolod-adrianov**
close bottom sheet after tests

### CODE REVIEW

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/TableUnitTests.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6416538&bid=20789188)

**Comment by mf-code** [comment]
[6367] - BK4XIPDqo4p9

**Comment by mf-code** [comment]
[6367] - 7WLZ9apCWrQs

**Comment by mf-code** [comment]
[6367] - zouLs4TMFXH8

**Comment by mf-code** [comment]
[6367] - 4QoD7ppVqJEv

**Comment by mf-code** [comment]
[6367] - zZupAaVyHBoX

**Comment by mf-code** [comment]
[6367] - auldoGMRWNDF

**Comment by mf-code** [comment]
[6367] - EXFBEpyAoWDT

**Comment by mf-code** [comment]
[6367] - T2sQxyeHRiQM

**Comment by mf-code** [comment]
[6367] - xZ7W2G2wX2Rp

**Comment by mf-code** [comment]
[6367] - RCYq8cOaOjaY

**Comment by mf-code** [comment]
[6367] - V8sXfA65A0tK

**Comment by mf-code** [comment]
[6367] - 8Ewq9ObCBJ71

**Comment by mf-code** [comment]
[6367] - nD6vcuVHX2ZV

**Comment by mf-code** [comment]
[6389] - 0hI9emNy67N5

**Comment by mf-code** [comment]
[6389] - Uvrd92p8SjlJ

**Comment by mf-code** [comment]
[6389] - mfQzQBA9kT5M

**Comment by mf-code** [comment]
[6389] - 2TSEBn1N1Y0V

**Comment by mf-code** [comment]
[6389] - 07rXoJCqSNwU

**Comment by mf-code** [comment]
[6389] - 9f7RepGN4Igb

**Comment by mf-code** [comment]
[6389] - Q38nZMMfXyBG

**Comment by mf-code** [comment]
[6389] - 8cDKw7jDKATJ

**Comment by mf-code** [comment]
[6389] - 86CJldN0dO3T

**Comment by mf-code** [comment]
[6389] - tBbNv4ryz54W

**Comment by mf-code** [comment]
[6389] - chK31orcbfzB

**Comment by mf-code** [comment]
[6389] - wimrVXVvmGhe

**Comment by mf-code** [comment]
[6389] - FjwOyjUdIr7x

**Comment by mf-code** [comment]
[6391] - AAEnlcjKtk3q

**Comment by mf-code** [comment]
[6391] - d0Gq5x6wU25u

**Comment by mf-code** [comment]
[6391] - VeVQQhYcjHxc

**Comment by mf-code** [comment]
[6391] - U4GXgnk8ZwKQ

**Comment by mf-code** [comment]
[6391] - TqenRiM8zaup

**Comment by mf-code** [comment]
[6391] - LQUYk9O9Joj8

**Comment by mf-code** [comment]
[6391] - iVLtSLdx7Tyx

**Comment by mf-code** [comment]
[6391] - LKVBZuoDl92J

**Comment by mf-code** [comment]
[6391] - 36Q9kVx0roGc

**Comment by mf-code** [comment]
[6391] - fZRvOp8agD2A

**Comment by mf-code** [comment]
[6391] - uy12fFg2HhZp

**Comment by mf-code** [comment]
[6391] - KR8Qb7c0JM6a

**Comment by mf-code** [comment]
[6391] - y0mXZO840nDy

**Comment by mf-code** [comment]
[6391] - tA8RSjqNO0y2

**Comment by Innokentiy945** [comment]
Useless test. Closed.

**Pull request closed without merging**
