### PR TITLE
1448 abstract toast

### PR DESCRIPTION
**Pull request by NataliaTikhomirova**
#1448

### CODE REVIEW

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/composite/section/ToastsTests.java  1
- jdi-light-bootstrap/src/main/java/com/epam/jdi/light/ui/bootstrap/elements/composite/AbstractToast.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/42_/jdi-light/pullRequest?prid=4671836&bid=15635252)

**Comment by mf-code** [comment]
[4049] - https://transfer.sh/LPcxl/jdi-performance.tar.gz

**Comment by mf-code** [comment]
[4049] - https://transfer.sh/OZh9Q/jdi-light-html-tests.tar.gz

**Comment by mf-code** [comment]
[4049] - https://transfer.sh/13KAqM/jdi-light-examples.tar.gz

**Comment by mf-code** [comment]
[4049] - Allure report on Netlify: https://5df374909857d4ef8307c700--musing-swartz-6fc060.netlify.com

**Pull request merged**
