### PR TITLE
1529 dropdown

### PR DESCRIPTION
**Pull request by hellokitties**
https://github.com/jdi-testing/jdi-light/issues/1529

### CODE REVIEW

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-html-tests/src/test/java/io/github/epam/example/complex/DropdownExampleTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/42_/jdi-light/pullRequest?prid=4737377&bid=15813393)

**Comment by mf-code** [comment]
[4394] - https://transfer.sh/mU7nL/jdi-light-examples.tar.gz

**Comment by mf-code** [comment]
[4394] - https://transfer.sh/RDDf1/jdi-performance.tar.gz

**Comment by mf-code** [comment]
[4394] - https://transfer.sh/OPP9a/jdi-light-html-tests.tar.gz

**Comment by mf-code** [comment]
[4394] - Allure report on Netlify: https://5e05d4f464a22c94a89759d0--musing-swartz-6fc060.netlify.com

**Pull request merged**
