### PR TITLE
divider classes removed

### PR DESCRIPTION
**Pull request by AlexSofft**

### CODE REVIEW

**Review by Ammar-Barry — APPROVED** [review]

**Comment by mf-code** [comment]
[6149] - Ssnj0FMc7yL8

**Comment by mf-code** [comment]
[6149] - J6qI97o8lZCV

**Comment by mf-code** [comment]
[6149] - kfbNaI7eOT6r

**Comment by mf-code** [comment]
[6149] - GsVEdBmDArMO

**Comment by mf-code** [comment]
[6149] - HpH6TSjXR50n

**Comment by mf-code** [comment]
[6149] - Vc4FjKAdRtZr

**Comment by mf-code** [comment]
[6149] - rC87FWKPp9Ml

**Comment by mf-code** [comment]
[6149] - uRCPbxD4LXZO

**Comment by mf-code** [comment]
[6149] - R42aQG7iB6JB

**Comment by mf-code** [comment]
[6149] - uKWDqZl6ywGT

**Comment by mf-code** [comment]
[6149] - OCfb9i0W5PIf

**Comment by mf-code** [comment]
[6149] - o4NdaE0PSqGp

**Comment by mf-code** [comment]
[6149] - ATwbkzxdjHMi

**Comment by mf-code** [comment]
[6149] - 41QCNNhOfThE

**Comment by mf-code** [comment]
[6149] - mbNnTJKzwl8B

**Comment by mf-code** [comment]
[6149] - YOynCDilq5Qq

**Comment by mf-code** [comment]
[6149] - 9DPp9wOow7qx

**Comment by mf-code** [comment]
[6149] - a2MY4JK72fqq

**Comment by mf-code** [comment]
[6149] - openjdk8 - Allure report on Netlify: https://5f63db0160ac367265a5e4b1--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6149] - openjdk10 - Allure report on Netlify: https://5f63dc1185b37367f390fbef--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6150] - RPYHhQcrNL2N

**Comment by mf-code** [comment]
[6150] - OIoak0UJIZqF

**Comment by mf-code** [comment]
[6150] - g6GTKnaIrZ9n

**Comment by mf-code** [comment]
[6150] - KtvJ7fPznkvx

**Comment by mf-code** [comment]
[6150] - P2S91yFTsKQw

**Comment by mf-code** [comment]
[6150] - 03JhfCtvvieA

**Comment by mf-code** [comment]
[6150] - XxFwgd7VYz9L

**Comment by mf-code** [comment]
[6150] - PkIkbKjugLEi

**Comment by mf-code** [comment]
[6150] - 7eJ0KyXa39N1

**Comment by mf-code** [comment]
[6150] - sVQ5zZFgqwr8

**Comment by mf-code** [comment]
[6150] - hNpqUMY2VGsb

**Comment by mf-code** [comment]
[6150] - UtD2vaMzj5Mh

**Comment by mf-code** [comment]
[6150] - 5VaKDewXp99Y

**Comment by mf-code** [comment]
[6150] - wWMPBIGQrM7g

**Comment by mf-code** [comment]
[6150] - ESJUrFwiHdGH

**Comment by mf-code** [comment]
[6150] - xEuzElOQi0PH

**Comment by mf-code** [comment]
[6150] - GEbTL7VvnGng

**Comment by mf-code** [comment]
[6150] - OQoXZwEdGFgw

**Comment by mf-code** [comment]
[6150] - openjdk8 - Allure report on Netlify: https://5f63f0a495757784c0fce908--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6150] - openjdk10 - Allure report on Netlify: https://5f63f18a04d16484060b7ee0--musing-swartz-6fc060.netlify.app

**Pull request merged**
