### PR TITLE
1607 made set text work with slash

### PR DESCRIPTION
**Pull request by hellokitties**
https://github.com/jdi-testing/jdi-light/issues/1607

### CODE REVIEW

**Comment by codacy-review** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/42_/jdi-light/pullRequest?prid=4729557&bid=15791198)

**Comment by mf-code** [comment]
[4355] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4355] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4355] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4355] - Allure report on Netlify: https://5e02235fd2bde50fdfdc6415--musing-swartz-6fc060.netlify.com

**Comment by mf-code** [comment]
[4385] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4385] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4385] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4385] - Allure report on Netlify: https://5e038637e0f80a4721286a83--musing-swartz-6fc060.netlify.com

**Pull request merged**
