### PR TITLE
266 add additional bdd steps

### PR DESCRIPTION
**Pull request by 886-59-936**
Added requested steps.
Added commented tests as examples for new issue https://github.com/jdi-testing/jdi-light/issues/1747

### CODE REVIEW

**Comment by mf-code** [comment]
[4843] - Could not save metadata Could not save metadata Could not save metadata

**Comment by mf-code** [comment]
[4843] - Allure report on Netlify: https://5e57cf6b23a3a5025c0af709--musing-swartz-6fc060.netlify.com

**Comment by mf-code** [comment]
[4843] - Allure report on Netlify: https://5e57cf6b23a3a5025c0af709--musing-swartz-6fc060.netlify.com

**Comment by RomanIovlev** [comment]
Please leave only changes in DropdownSteps.java  and DropDown.feature and I will accept

**Pull request merged**
