### PR TITLE
modified DataTableTests.tableParamsTest() to fail

### PR DESCRIPTION
**Pull request by dexguitar**

### CODE REVIEW

**Comment by mf-code** [comment]
[4572] - https://transfer.sh/15EwfL/jdi-light-examples.tar.gz

**Comment by mf-code** [comment]
[4572] - https://transfer.sh/MjDem/jdi-performance.tar.gz

**Comment by mf-code** [comment]
[4572] - https://transfer.sh/pCMZF/jdi-light-html-tests.tar.gz

**Comment by mf-code** [comment]
[4572] - Allure report on Netlify: https://5e299d86ecedb701e3a658a4--musing-swartz-6fc060.netlify.com

**Comment by RomanIovlev** [comment]
not actual now

**Pull request closed without merging**
