### PR TITLE
SearchView added (for pages Always Expanded and Filter)

### PR DESCRIPTION
**Pull request by Syzygy9**

### CODE REVIEW

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-mobile-tests/src/test/java/nativeapp_android/tests/SearchViewTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6330930&bid=20570821)

**Comment by mf-code** [comment]
[6277] - gZimrdMuHx5N

**Comment by mf-code** [comment]
[6277] - UyoCiwROaYKu

**Comment by mf-code** [comment]
[6277] - gTlFiXvMUgoO

**Comment by mf-code** [comment]
[6277] - 6jyLdNKZqu32

**Comment by mf-code** [comment]
[6277] - Nvhve1sjT8oz

**Comment by mf-code** [comment]
[6277] - oo97JM6Ho0YM

**Comment by mf-code** [comment]
[6277] - HHVZvNJVFKu0

**Comment by mf-code** [comment]
[6277] - YUP1WrdHgJgM

**Comment by mf-code** [comment]
[6277] - kjNGM2Q2qJjG

**Comment by mf-code** [comment]
[6277] - ySHva0klqbKw

**Comment by mf-code** [comment]
[6277] - M4HapsgLPm4W

**Comment by mf-code** [comment]
[6277] - Sr9lxstUjX4f

**Comment by mf-code** [comment]
[6277] - Hu2SbrkLDeIE

**Comment by mf-code** [comment]
[6277] - wUckbvrfVQ4t

**Comment by mf-code** [comment]
[6277] - pZ17P0vS1osG

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/asserts/SearchViewFieldAssert.java  1
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/asserts/SearchViewButtonAssert.java  1
- jdi-light-mobile-tests/src/test/java/nativeapp_android/tests/SearchViewTests.java  1
- jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/elements/common/app/android/SearchViewField.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6330930&bid=20570821)

**Review by alexarm — APPROVED** [review]

**Pull request merged**
