### PR TITLE
Task2419 combine statements

### PR DESCRIPTION
**Pull request by tsvetaevAlex**

### CODE REVIEW

**Comment by mf-code** [comment]
[6278] - pagwNHrQ6RlJ

**Comment by mf-code** [comment]
[6278] - MCDlwocBKlJ8

**Comment by mf-code** [comment]
[6278] - Y773PaB1sV54

**Comment by mf-code** [comment]
[6278] - jxF34kcpU6YS

**Comment by mf-code** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=6332081&bid=20573373)

**Comment by mf-code** [comment]
[6278] - NNeOC4y1BTyB

**Comment by mf-code** [comment]
[6278] - Syy8vKCqR5by

**Comment by mf-code** [comment]
[6278] - GE7y1duNlCp3

**Comment by mf-code** [comment]
[6278] - gnhwEYexp3AZ

**Comment by mf-code** [comment]
[6278] - V3RcWE6tzGqy

**Comment by mf-code** [comment]
[6278] - aEImNzgGVS7k

**Comment by mf-code** [comment]
[6278] - fxfH02N24Zwe

**Comment by mf-code** [comment]
[6278] - lak9HMl3HhOH

**Comment by mf-code** [comment]
[6278] - QsNdjEKlertn

**Comment by mf-code** [comment]
[6278] - HfoOcV8Oyum7

**Comment by mf-code** [comment]
[6278] - UsVjbXgigIBh

**Comment by mf-code** [comment]
[6278] - mJkYwYr0Ba1T

**Comment by mf-code** [comment]
[6278] - openjdk8 - Allure report on Netlify: https://5f85d76619d32844ffdc7662--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6278] - openjdk10 - Allure report on Netlify: https://5f85d8f119d3283e80dc7b97--musing-swartz-6fc060.netlify.app

**Review by alexarm — APPROVED** [review]

**Pull request merged**
