### PR TITLE
Adjusted Angular Select elements classes and tests.

### PR DESCRIPTION
**Pull request by gbuh**
Adjusted Angular Select elements classes and tests.

### CODE REVIEW

**Comment by mf-code** [comment]
[5919] - SXiyq3UD8M1t

**Comment by mf-code** [comment]
[5919] - kgJkuaklM75z

**Comment by mf-code** [comment]
[5919] - zK7prJgv2mff

**Comment by mf-code** [comment]
[5919] - 6UmYOQmC2evx

**Comment by mf-code** [comment]
[5919] - J3Lo5w1A3AVM

**Comment by mf-code** [comment]
[5919] - 6rVInCPQYZwf

**Comment by mf-code** [comment]
[5919] - NrXWQEL9nTmX

**Comment by mf-code** [comment]
[5919] - hvj4v5hfP9YF

**Comment by mf-code** [comment]
[5919] - txNGHxV0L5a4

**Comment by mf-code** [comment]
[5919] - rc3UWjqTXldu

**Comment by mf-code** [comment]
[5919] - 1uBk7989cHQu

**Comment by mf-code** [comment]
[5919] - P5ys22qmu93D

**Comment by mf-code** [comment]
[5919] - RYh43gDPONCz

**Comment by mf-code** [comment]
[5919] - RQjA1jr1v63S

**Comment by mf-code** [comment]
[5919] - openjdk8 - Allure report on Netlify: https://5f4632f37880eb138eb31873--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[5919] - openjdk10 - Allure report on Netlify: https://5f463334f9454c728607d98e--musing-swartz-6fc060.netlify.app

**Review by AlexSoftt — APPROVED** [review]

**Pull request merged**
