### PR TITLE
Added ExpansionPanel element and test cases.

### PR DESCRIPTION
**Pull request by gbuh**
Added ExpansionPanel element and test cases.

### CODE REVIEW

**Comment by mf-code** [comment]
[6090] - KG6gljcTnaWy

**Comment by mf-code** [comment]
[6090] - Th3ZgihGFrYJ

**Comment by mf-code** [comment]
[6090] - sNmiYPnAZpgf

**Comment by mf-code** [comment]
[6090] - xuDklmdB7VfA

**Comment by mf-code** [comment]
[6090] - PbKM40sXzqCu

**Comment by mf-code** [comment]
[6090] - NzRlekobW1YF

**Comment by mf-code** [comment]
[6090] - FLbvWVqZ55qM

**Comment by mf-code** [comment]
[6090] - CuMyGAMTbRao

**Comment by mf-code** [comment]
[6090] - nyVgcgrFaF7T

**Comment by mf-code** [comment]
[6090] - iC1gNPLilSEU

**Comment by mf-code** [comment]
[6090] - Ng7o27PyKFdo

**Comment by mf-code** [comment]
[6090] - vVzCubTnf3Rc

**Comment by mf-code** [comment]
[6090] - YZGvblZYgkWW

**Comment by mf-code** [comment]
[6090] - OBHOOcEkzeUJ

**Comment by mf-code** [comment]
[6090] -

**Comment by mf-code** [comment]
[6090] - tSqi3WgkBt0c

**Comment by mf-code** [comment]
[6090] - NyrVDTPe2hl0

**Comment by mf-code** [comment]
[6090] - openjdk8 - Allure report on Netlify: https://5f5bce9d74362611baf05dff--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6090] - openjdk10 - Allure report on Netlify: https://5f5bcfaaed9ebe172a5b7e9e--musing-swartz-6fc060.netlify.app

**Review by AlexSofft — APPROVED** [review]

**Pull request merged**
