### PR TITLE
2350 refactor spinner tests

### PR DESCRIPTION
**Pull request by AlexSofft**

### CODE REVIEW

**Review by Ammar-Barry — APPROVED** [review]

**Comment by mf-code** [comment]
[6155] - ugmYLh3htq35

**Comment by mf-code** [comment]
[6155] - rcWG56tKJ15D

**Comment by mf-code** [comment]
[6155] - IctJBVsSuTk8

**Comment by mf-code** [comment]
[6155] - hTF8bGrSxjQJ

**Comment by mf-code** [comment]
[6155] - ldDT3Q7pbn1z

**Comment by mf-code** [comment]
[6155] - 5ZiMBt6q1n1c

**Comment by mf-code** [comment]
[6155] - 8fLNh0wSsSkv

**Comment by mf-code** [comment]
[6155] - yiIJrojWbDD6

**Comment by mf-code** [comment]
[6155] - 3ytqGLU4AwvI

**Comment by mf-code** [comment]
[6155] - VYoIyrWMsP3q

**Comment by mf-code** [comment]
[6155] - Gi7UuHviCx9n

**Comment by mf-code** [comment]
[6155] - FDfqLJyhNTcu

**Comment by mf-code** [comment]
[6155] - rT7erCTiODjH

**Comment by mf-code** [comment]
[6155] - BZbMeIslmIem

**Comment by mf-code** [comment]
[6155] - vsn26APbW1aV

**Comment by mf-code** [comment]
[6155] - 0oHN8LHbw8n1

**Comment by mf-code** [comment]
[6155] - e8M6ux8lR7U5

**Comment by mf-code** [comment]
[6155] - CtTHIUsKYf7u

**Comment by mf-code** [comment]
[6155] - openjdk8 - Allure report on Netlify: https://5f649a01042c3813ea75910a--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6155] - openjdk10 - Allure report on Netlify: https://5f649be1b73507120b976f1c--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6158] - f2PNVs6YMuXN

**Comment by mf-code** [comment]
[6158] - XztvBHSrFk9u

**Comment by mf-code** [comment]
[6158] - ZQAwELW67IcT

**Comment by mf-code** [comment]
[6158] - wQK4XNMwHT4k

**Comment by mf-code** [comment]
[6158] - sJ5kwBMGW3wd

**Comment by mf-code** [comment]
[6158] - 3oNAkZzZrFmv

**Comment by mf-code** [comment]
[6158] - f6Iw8iW7euoR

**Comment by mf-code** [comment]
[6158] - xlXEeSDcJ7Uu

**Comment by mf-code** [comment]
[6158] - axl37bUBoIQg

**Comment by mf-code** [comment]
[6158] - tqnjA0zkguwv

**Comment by mf-code** [comment]
[6158] - uW51Yu9qyhnI

**Comment by mf-code** [comment]
[6158] - k95WT4P4pGF7

**Comment by mf-code** [comment]
[6158] - Pobct8DgFzIn

**Comment by mf-code** [comment]
[6158] - dzzzNcgkciQN

**Comment by mf-code** [comment]
[6158] - 73cSLaLMqAho

**Comment by mf-code** [comment]
[6158] - mTh80iVuqHfX

**Comment by mf-code** [comment]
[6158] - q9YhYSUJ6Nzk

**Comment by mf-code** [comment]
[6158] - openjdk8 - Allure report on Netlify: https://5f64b948f2d71438645f2844--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6158] - openjdk10 - Allure report on Netlify: https://5f64ba5fa77a42425a181a7a--musing-swartz-6fc060.netlify.app

**Comment by mf-code** [comment]
[6164] - lnZSeExDfQ6O

**Comment by mf-code** [comment]
[6164] - Yuz2lsqxwAJY

**Comment by mf-code** [comment]
[6164] - JrzkzVItgJJA

**Comment by mf-code** [comment]
[6164] - JXUjyKQeMUlS

**Comment by mf-code** [comment]
[6164] - 88g3WRJ69QJB

**Comment by mf-code** [comment]
[6164] - 9sVZxrziqcWs

**Comment by mf-code** [comment]
[6164] - GNttxzuGLqOG

**Comment by mf-code** [comment]
[6164] - 1qMDx0gMbDKm

**Comment by mf-code** [comment]
[6164] - 7Xnp93Clqf1A

**Comment by mf-code** [comment]
[6164] - b52CJQEN70Ai

**Comment by mf-code** [comment]
[6164] - GnjsZNUqPB92

**Comment by mf-code** [comment]
[6164] - SMzIThwOjje8

**Comment by mf-code** [comment]
[6164] - Xg7WZCiQIXM0

**Comment by mf-code** [comment]
[6164] - 8RMFKLyp41oL

**Comment by mf-code** [comment]
[6164] - VR3VZazew3pZ

**Comment by mf-code** [comment]
[6164] - GUjDZ3yKCi13

**Comment by mf-code** [comment]
[6164] - pO1tjxYv9wFN

**Comment by mf-code** [comment]
[6164] - 5ThinWPxm6tc

**Comment by mf-code** [comment]
[6167] - o8uZ0ejVXMvq

**Comment by mf-code** [comment]
[6167] - TwU4igYFO8iC

**Comment by mf-code** [comment]
[6167] - e24shLzOxi1c

**Comment by mf-code** [comment]
[6167] - 0Y60SaRWuMLj

**Comment by mf-code** [comment]
[6167] - DSDDe4BNMz6t

**Comment by mf-code** [comment]
[6167] - mIa3VEdDwRe7

**Comment by mf-code** [comment]
[6167] - 8oNzeF7LRnRj

**Comment by mf-code** [comment]
[6167] - ML5Je0lGSiLc

**Comment by mf-code** [comment]
[6167] - XgciwFTwR69F

**Comment by mf-code** [comment]
[6167] - zHtJSrXP2xeO

**Comment by mf-code** [comment]
[6167] - TfqDRcFB5yK6

**Comment by mf-code** [comment]
[6167] - U9cl3ijm3tN4

**Comment by mf-code** [comment]
[6167] - TlcFcz02WBGc

**Comment by mf-code** [comment]
[6167] - w5CeCoEGxBuB

**Comment by mf-code** [comment]
[6167] - gfDLpkJSCL0S

**Comment by mf-code** [comment]
[6167] - patDlbJM1NYy

**Comment by mf-code** [comment]
[6167] - oLQtHEKjEIsa

**Comment by mf-code** [comment]
[6167] - p7MaIOFteADn

**Pull request merged**
